### ISSUE TITLE
libigl from the dev branch brakes a tutorial from Directional

### ISSUE THREAD

**Issue by copyme** [libigl/libigl#1042]
First of all, sorry for not being too specific about this problem. I report it here because I think it may be a bug introduced by the recent changes to libigl. 

So, the tutorial [103 of the Directional](https://avaxman.github.io/Directional/tutorial/#103-streamline-tracing) library works well with libigl from the master branch but when compiled with the current dev branch we can observe unexpected behavior.  I did not have luck in nailing down the issue so I report it here because it seems to be libigl related.

For more see [#13 (Directional)](https://github.com/avaxman/Directional/issues/13).

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [X] Mac OS X
- [X] Linux

**Comment by jdumas** [comment]
This could be related to #994

**Comment by jdumas** [comment]
More precisely, this looks like a precision issue with the condition on `t` and `u` for deciding whether two segments intersect, which somehow stops the streamlines from being propagated. Not sure what is the best way to solve this though.

**Comment by jdumas** [comment]
The `eps` parameter is already exposed as an argument to the function. But it's used both to test whether the lines are considered parallel (check on the determinant), and to decide whether to return true/false based on how much the parameters `t` and `u` are within the range `[eps, 1-eps]`. The streamline code is already part of Directional, but the `segment_intersect` function should stay in libigl (since it's useful in many cases).

**Comment by alecjacobson** [comment]
not sure there's anything to do here. please reopen if there is.
