### ISSUE TITLE
Integrate ApproxMVBB in this library

### ISSUE THREAD

**Issue by gabyx** [libigl/libigl#1044]
It would probably of interest to integrate the ApproxMVBB functionality into this Library if its useful:
https://github.com/gabyx/ApproxMVBB
- eigen3, openmp.
It also has an optional kdTree implementation (but would probably not fulfill the requirement "no complex datastrctures"... :-P

Maybe somebody or even me has time for this if its welcome :-)

Regards.

**Comment by gabyx** [comment]
I just though it would be nice to have direct integration of my library into your framework, such that user do not need to have another dependency...

**Comment by jdumas** [comment]
Unless there is an algorithm in libigl that relies on your library, I don't see the point of adding *more* dependencies to libigl itself. Especially if your library already uses Eigen and has a clean interface. We usually provide wrapper around popular libraries (such as triangle, tetgen or CGAL) that have a non-Eigen interface to make it easier to integrate with code using libigl. As such I don't think your library needs to be integrated into libigl, it seems perfectly fine as it is.

Let me know if I missed anything, but otherwise I'll be closing this thread.

**Comment by cdcseacave** [comment]
I recently had a look over `ApproxMVBB` and I think it is worth integrating here, as currently is much more complex than it needs to, and can benefit from a rewrite; for ex the initial oriented bounding box used to start the optimization is computed using a huge and complex diameter based algo, and can be easily replaced with 10 lines of code based on eigen vector decomposition of the points covariance matrix. And there are more examples like that, including the whole `tetgen` dependency for orientation computation that can be replaced by exactly 4 lines of code, as perfect precision is not needed since the point cloud is approximated with a sparse one, where the points are sufficiently well apart, and a simple point cloud normalization to median 0 and variance 1 will guaranty good behavior for this operation.

**Comment by gabyx** [comment]
Good points. My approach was based on the papers given in the readme. It guarantees some kind of epsilon boundary criterion for the min. volume. The code is quite complex, and maybe its much better to simplify the procedure as described. convhull and such still need to be precise and correctly implemented with predicates. do you use these as well in libigl? 

the thing about the diameter is probably, can not remember, that the whole principle component analysis gives rather random output for special shapes and is not the same as the diameter computation (which i did not understand in detail too complex, but basically a random algorithm). But I think its a good start to just try to use the eigenvectors, we could of course also make it general that the points can have a mass (weight) where we compute the eigenvecs of the tensor of inertia as a start :)

what do you mean with tetgen?


Von meinem iPhone gesendet

**Comment by gabyx** [comment]
It would be a cool idea, too much dependencies. I needed as well the shewchuck predicates and hardware flags. maybe somebody could rewrite it in a festure/v2 branch. The code so far implemented is basically the rewrite of the research code of the people in the papers.
