### ISSUE TITLE
Eigen version used by libigl

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#1046]
The version of Eigen fetched by the cmake scripts is quite old. Will anything go wrong if I replace external/eigen with, say, Eigen 3.3.7? (Newer Eigen contains features like SparseRef needed by other dependencies in my project). I skimmed the tutorial docs but don't see anything about which version(s) of Eigen libigl requires internally.

**Comment by jdumas** [comment]
Depends which function you are using. I have been compiling statically with eigen 3.3.7 for my own project and it was fine, but I'm not using anything fancy from libigl. It's definitely on the todolist of things to update (also in terms of unit tests).

**Comment by jdumas** [comment]
@alecjacobson mentioned reporting a couple of scary bugs at the time Eigen 3.3 came out, but I cannot find his message about which specific issues/bug reports on Eigen's board. Those bugs are probably fixed by now, but it means that in the meantime libigl was not updated to Eigen 3.3. You're more likely to encounter compilation issues with codepath not covered by the explicit template instantiation in libigl, but otherwise should be fine.

As for libigl itself, we first need to reenable unit testing for CGAL on all platforms in the CI (#996) and maybe expand our unit test coverage a little bit, before we can upgrade to Eigen 3.3. There's no immediate timeline on this, but will not happen before SIGGRAPH for sure :D

**Comment by evouga** [comment]
FYI: With the new version of Eigen, it is essential to compile with -DEIGEN_STRONG_INLINE=inline in MSVC. The difference in compilation time is 80 seconds vs 10 hours.

**Comment by alecjacobson** [comment]
I lost track of the Eigen 3.3 update pull request. Is there PR already prepared for this? @danielepanozzo ?

**Comment by jdumas** [comment]
Right now we build against Eigen 3.3 on Travis. The question left is whether we should change the default to be 3.3 before or after we make the new release. There's current one big PR but it's more about preparing the ground for the new python bindings (and thus should be merged after we tag the new release).

**Comment by alecjacobson** [comment]
What's the remaining PR for the release?

>

**Comment by jdumas** [comment]
Nothing critical as of right now. There are small bugfixes in the PRs that we could merge. Then it's just a matter of updating the changelog/doc accordingly and tagging the new release.

**Comment by alecjacobson** [comment]
Let's do it ! (probably on Tuesday :-)

>

**Comment by evouga** [comment]
For context, the reason I wanted Eigen 3.3 is to use Spectra (https://spectralib.org/), a very nice Eigen-compatible header-only ARPACK replacement, along with the libigl tools, but Spectra only works with Eigen 3.3.
