### ISSUE TITLE
Running libigl for windows visual studio 2017

### ISSUE THREAD

**Issue by petrasvestartas** [libigl/libigl#1052]
[Describe your issue]

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

Can someone give instructions how to build with cmake libigl for windows visual studio 64bit 2017?

I tried to go to tutorial page, but there is now clear step by step instructions. Why is that so? 

I am totally new user and just would like to test any simple example file. 

Do I need to install any existing libraries like Eigen? 

Would it be difficult to make step by step installation with screenshots or youtube video since it is very popular library?

**Comment by jdumas** [comment]
Hi. Any CMake tutorial for Windows will help you get libigl up and running. See e.g. [this page](https://cmake.org/runningcmake/).

Note that CMake is not strictly _required_ (at least for the core part of the library), as you can use both libigl and eigen as header-only libraries (just add the folders to the include paths of you project configuration).

**Comment by evouga** [comment]
I strongly recommend you download the libigl example project (https://github.com/libigl/libigl-example-project) and start from there. It contains some template code for the main.cpp file as well as a working CMake makefile (CMakeLists.txt). I start all of my libigl projects from this template.

Like @jdumas says, you want to install cmake (very easy on Windows) as well as libigl. Open it and

1. In the "Where is the source code:" box, type in the path to the libigl-example-project folder.
2. In the "Where to build the binaries:" box, type in the same path, but append "/build".

So on my machine for instance, the two paths are
C:/Users/evouga/Documents/libigl-example-project
C:/Users/evouga/Documents/libigl-example-project/build.

Next, make sure that libigl is in a place that cmake can find it. By far the easiest it to place libigl in the same parent folder as your project (C:/Users/evouga/Documents/libigl in my case). Otherwise cmake may have trouble finding the libigl files and you will need to go mess around with environment variables etc.

Now click "configure." CMake will ask you to pick which toolchain to use (I recommend "use default native compilers" if you have MSVC installed correctly on your system). Hopefully you don't get any errors. Then click "generate" and then click "open project." CMake will have automatically generated an MSVC .sln and you should be able to compile the example project from within MSVC.

**Comment by jdumas** [comment]
While we may improve the documentation on the website in the future (contributions welcome!), I think the original question has been answered, so I'll close this for now.
