### ISSUE TITLE
Cannot install all the tutorial

### ISSUE THREAD

**Issue by thelagrangian** [libigl/libigl#1083]
I was able to follow the tutorial to install the library. And then I entered the libigl/tutorial directory, and did the following,
mkdir build
cd build
cmake ../
make

But after all these, I only got the 101_FileIO_bin file, but no other tutorials. (For example, I did not get the 102_DrawMesh_bin file). I had the same result on both ubuntu and macos.

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] Mac OS X
- [x] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
Hi. You need to either build the tutorial from the root directory (and go into `build/tutorial/` to run them), or enable manually the modules you want to enable if you are building from the `tutorial/` folder). By default building from the tutorial folder only enable the "core" module. Since pretty much every other tutorial needs at least OpenGL for the viewer, this is why you are getting only the first one.

**Comment by thelagrangian** [comment]
Thank you, jdumas. It is really helpful.
