### ISSUE TITLE
igl::opengl::glfw::Viewer does not draw labels

### ISSUE THREAD

**Issue by copyme** [libigl/libigl#1104]
I wanted to draw some labels, but it looks like the method `add_label` does not work. Even in the example 105 I do not see any labels even though they are added.
 
![image](https://user-images.githubusercontent.com/456607/53725481-c1cbd400-3e74-11e9-919a-3b29cf507581.png)

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [X] Linux

PS. I tried the code from the current master and dev.

**Comment by jdumas** [comment]
This is not the first time this issue pops up (#1089). @alecjacobson @danielepanozzo the tutorial 105 has calls to `.add_label()`, so people are expecting to see labels, but the labels do not show up because ImGui is not enabled on this tutorial.

Two options:
- Either remove the labels from tutorial 105,
- Or enable ImGui in tutorial 105 to show how to display labels.

Let me know which one you would like.

**Comment by alecjacobson** [comment]
Let's enable imgui for just 105

**Comment by jdumas** [comment]
Ok, done in #1105
