### ISSUE TITLE
Compilation error with MINGW64 compiler

### ISSUE THREAD

**Issue by paulelian-tabarant** [libigl/libigl#1148]
Hello,

I am currently developing a C++ application which uses, among other libs, the IGL library. The problem is that I need to compile it under a Windows environment using MINGW64 (g++ compiler for Windows) and when doing so, I get the following error :

> C:/msys64/mingw64/include/igl/SortableRow.h: In member function 'bool igl::SortableRow<T>::operator==(const igl::SortableRow<T>&) const':
> C:/msys64/mingw64/include/igl/SortableRow.h:49:32: error: expected unqualified-id before 'void'
>
         const SortableRow<T> & THIS = *this;
                                ^
I could not figure out why I get it. The big mess is that the g++ version inside MINGW64 is the same as the one I use in my development environment (Linux-based). It seems that the MINGW64-based compiler does not work the same. Any idea of what could be wrong ?

Thank you very much in advance,

Paul-Elian

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by jdumas** [comment]
Why cannot you use the MSVC compiler on Windows? From our experience, trying to do any graphical application with mingw on Windows brings nothing but trouble...

**Comment by paulelian-tabarant** [comment]
I did not consider it because my program is embedded inside a VR application which actually uses mingw in order to compile its sources. I'm going to see with maintainers if I could do it with MSVC, thanks for the advice

**Comment by paulelian-tabarant** [comment]
About the MSVC compiler, the main problem is that my project needs a lot of Linux libs dependencies which can be easily installed inside the mingw environment.

**Comment by jdumas** [comment]
Well, maybe you should run it on linux directly then? I mean don't get me wrong, it'd be nice if we could support mingw builds, and if have an easy fix for the error above we'd be happy to merge it. But it already takes a lot of time to ensure a consistent build on all three OS using the default compilers (MSVC on Windows). Going with cross-compiling tools like mingw is often a sign that you probably have some dependencies that you should try to remove instead... otherwise headaches will ensue.

**Comment by paulelian-tabarant** [comment]
Yes, I think that this is what I'm going to do indeed. I completely understand, I was just wondering if it was somehow related to a previously reported error. Thanks for all !

**Comment by jdumas** [comment]
From the look of your error message, I suspect maybe `THIS` is a macro replaced by `void`, and thus generating an error message. You can try to rename it see if it helps. As to where the macro would be coming from, one could only guess. I'll close this as a won't fix though, since we do not officially support mingw builds.
