### ISSUE TITLE
override the existing `load` function for meshes, or create a new viewerplugin?

### ISSUE THREAD

**Issue by xarthurx** [libigl/libigl#1161]
The pre-defined `draw_viewer_menu()` from the ImGuiMenu is pretty good as a starting point, however, for the default mesh load function, it seems I cannot get the vertex, faces etc. as a normal `igl::readOBJ` does.

For replacing or adding the functionality, is there a recommended way for doing this?
I'm currentlly using a user-defined button to do this task, which made the default `load` button useless.

Thanks.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by xarthurx** [comment]
BTW, I know `viewer.data().V` can be accessed for the vertex data.
But more generally, some docs on the viewer system and how we can extend it would be great!

**Comment by jdumas** [comment]
What would you suggest to improve documentation? Better documentation in the header files? Another tutorial? Documentation may be a bit scarce for some things, but hopefully the viewer and the plugin are relatively simple so you can have a look at the source code directly.

Anyway, to answer your question: you can customize the behaviour of the "load" button by overriding the `virtual bool load(std::string filename)` method of a `ViewerPlugin`. Typically, you can have your own menu plugin that inherits from `ImGuiMenu`, and then customize what happens when you load/save a file (if the method return `true` it will return there and not call the `Viewer::load()` method).

Now, if you want to add functions to the ImGui menu, you can either implement your own `draw_custom_window()` method, or provide a functional callback `callback_draw_custom_window` (both styles are supported). The former is more customizable, but the latter is quicker to setup as it doesn't require you to define your own derived class. Similarly, if you want to modify/replace the current menu by a new one, you can copy the content of the libigl imgui plugin and modify it to your convenience, by providing either `draw_viewer_window()` or `draw_viewer_menu()` (the former defines the menu position and size, and then calls the latter to fill its content).

**Comment by xarthurx** [comment]
@jdumas 
Thank you so much for the thorough explanation, and understand now.

For the documentation, I would say an example setup like the `libigl-example-project` would be great.
That one is very good for a basic cmake setup for a start-up, but quite limited to understand all the `callback` and other mechanisms that libigl build upon different libs, like the imgui.

I personally went through the course assignments I found on **eth-igl** to have a better understanding, though that one is customised for the course and don't have all the functionality needed.

Anyhow, for someone new to this great library, a more user-friendly starter setup would be super helpful if he/she don't need to go into each header files to read the doc and figure out little by little what is needed to change. 

I think this will also reduce the number of issues (like this one) and reduce the work on your side (which is quite responsive I super appreciated!).

**Comment by jdumas** [comment]
Well it's also work to create an extensive documentation, but improving it is pretty high on our todo-list =)
We'll keep your comments in mind, and see what we can do.

I'll close this thread unless you have further question about the viewer.
