### ISSUE TITLE
an undesired gray silhouette for screen captures

### ISSUE THREAD

**Issue by jhwang7628** [libigl/libigl#1221]
I use the function `draw_buffer` as shown in one of the tutorials to draw a bunny and found that there's a gray silhouette (see attachment) esp on black background. I imagine it might be an artifact of the rendering loop. Any help getting rid of these is much appreciated. 

![tmp](https://user-images.githubusercontent.com/7445300/59251759-6d589300-8bdf-11e9-8aaf-f42c28794e31.png)

**Comment by BruegelN** [comment]
Do you mean the shadow e.g. on the back of the bunny?
You might have a look at tutorial [606 AmbientOcclusion](https://libigl.github.io/tutorial/#baking-ambient-occlusion) or play around with the lighting position to reduce this effect for your given model (see [ViewerCore.h#L116](https://github.com/libigl/libigl/blob/master/include/igl/opengl/ViewerCore.h#L116)).

**Comment by jdumas** [comment]
Those grey transparent pixels are most likely due to anti-aliasing, not ambient occlusion (which we don't do by default). You can try to turn it off by commenting [this line](https://github.com/libigl/libigl/blob/f6b406427400ed7ddb56cfc2577b6af571827c8c/include/igl/opengl/glfw/Viewer.cpp#L144) (for the viewer itself), or by modifying [this line](https://github.com/libigl/libigl/blob/f6b406427400ed7ddb56cfc2577b6af571827c8c/include/igl/opengl/ViewerCore.cpp#L266) for the`draw_buffer` command. Let me know if that works for you.

**Comment by BruegelN** [comment]
Due to the light background I didn't saw the anti-aliasing effects 🤦‍♂ I'm sorry, I thought you where talking about the shaddows (pink below), my fault.
Downloading the image and using preview it's obvious what you meant.
<img width="669" alt="Bildschirmfoto 2019-06-11 um 14 21 55" src="https://user-images.githubusercontent.com/9728182/59271598-759ee580-8c54-11e9-8d38-77b1122be902.png">
Increasing the image size to e.g. (2560, 1600) instead of (1280,800) should make anti-aliasing also much less visible.

_____
@jdumas I was assuming at least if you use igl::opengl::ViewerData::set_colors() ambient, specular and diffuse lighing is simulated, see https://github.com/libigl/libigl/blob/master/include/igl/opengl/ViewerData.cpp#L135 . But nevermind I misunderstood the question anyway 😅

**Comment by jdumas** [comment]
Yes there is ambient/specular and diffuse lighting, but ambient _occlusion_ is a different topic, and not straightforward to implement in a satisfying manner.

**Comment by jhwang7628** [comment]
> Those grey transparent pixels are most likely due to anti-aliasing, not ambient occlusion (which we don't do by default). You can try to turn it off by commenting [this line](https://github.com/libigl/libigl/blob/f6b406427400ed7ddb56cfc2577b6af571827c8c/include/igl/opengl/glfw/Viewer.cpp#L144) (for the viewer itself), or by modifying [this line](https://github.com/libigl/libigl/blob/f6b406427400ed7ddb56cfc2577b6af571827c8c/include/igl/opengl/ViewerCore.cpp#L266) for the`draw_buffer` command. Let me know if that works for you.

I've tried the first approach and it did not do anything. `diff` shows that two images are identical after commenting out the line. For the second approach, I changed the multisample count to 8 for both framebuffer and renderbuffer, and this time images are different but the silhouette persists.

**Comment by jhwang7628** [comment]
Also, if possible I'd like to have anti-alising, so disabling it is less attractive. I am trying to understand the root cause of this problem. After reading the commented link on anti-aliasing and how MSAA is implemented in OpenGL, I wonder if the cause is the interpolation of the color buffer for the subsamples. It seems that I am just blending a few samples of black (caused by the shadow) and a few samples of white (caused by inactive samples). In this case then setting the default value for the color buffer to black might alleviate this problem? Is this possible?

FYI this is the paragraph on MSAA I found that might be relevant to this problem:
> The fragment shader is run with the vertex data interpolated to the center of the pixel and the resulting color is then stored inside each of the covered subsamples. Once the color buffer's subsamples are filled with all the colors of the primitives we've rendered, all these colors are then averaged per pixel resulting in a single color per pixel.

**Comment by jdumas** [comment]
You can also try to remove the alpha channel and the grey silhouette should become black. Btw, this grey silhouette is exactly the by-product of antialiasing. If you removing, the silhouette is gonna become aliased. Maybe [this article](https://learnopengl.com/Advanced-OpenGL/Anti-Aliasing) on anti-aliasing can help you figure out what you want, and modify the code accordingly?

**Comment by jhwang7628** [comment]
I see. Can you suggest a way to remove the alpha channel?

**Comment by jdumas** [comment]
Edit the picture with Gimp/Imagemagicks (if you only need 1 screenshot). Or change the `GL_RGBA` into `GL_RGB` in the libigl code, change 4 into 3, etc.
