### ISSUE TITLE
Python Binding Tutorial 405_AsRigidAsPossible-AttributeError: 'pyigl.glfw.Viewer' object has no attribute 'core'

### ISSUE THREAD

**Issue by YuliangXiu** [libigl/libigl#1225]
#### Describe your issue

AttributeError: 'pyigl.glfw.Viewer' object has no attribute 'core'

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Hi. Try changing `.core` into `.core()` in the tutorial, that ought to do the trick.

**Comment by YuliangXiu** [comment]
This change does not work.

`Traceback (most recent call last):
  File "405_AsRigidAsPossible.py", line 108, in <module>
    viewer.core().is_animating = True
AttributeError: 'pyigl.glfw.Viewer' object has no attribute 'core'`

**Comment by BruegelN** [comment]
This error is due to missing python bindings for `core()`. Maybe have a look at #1227 .
[This line](https://github.com/libigl/libigl/blob/6787393cd1a71816a912129f14cccb5cff674dbf/python/modules/py_igl_opengl_glfw.cpp#L376) does the trick.
Afterwards you need to run `cmake` and `make` and it should be fixed :)

**Comment by YuliangXiu** [comment]
It works, thanks for the help!
