### ISSUE TITLE
Why force static linkage of MSVC runtime?

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#1229]
#### Describe your issue

When compiling code using the new version of libigl, CMake outputs the following message:
"MSVC -> forcing use of statically-linked runtime."
and as it states, sets the program to link statically against MSVC's runtime libraries (/MT).

Why is this? The old libigl worked fine with /MD, as does the new version, when I manually change the compile flags back myself.

Forcing /MT is not a trivial decision, as it requires propagating this decision to all external libraries linked by the application...

#### Check all that apply (change to `[x]`)
- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by evouga** [comment]
Looking more into this: it looks like there's an MSVC_RUNTIME variable that needs to be set in order to prevent libigl from using static linking by default. Note that there's already a USE_MSVC_RUNTIME_LIBRARY_DLL CMake variable that's set by GLFW and exposed as a CMake option, but it does not work because it's overridden by MSVC_RUNTIME.

It would be nice to:
 - restore /MD by default on Windows, unless there is a reason libigl needs /MT: /MD is less likely on average to cause link conflicts with external libraries
 - expose MSVC_RUNTIME as a CMake option() and make it work correctly with GLFW's USE_MSVC_RUNTIME_LIBRARY_DLL

**Comment by jdumas** [comment]
From what I remember, we've added this [LibiglWindows.cmake](https://github.com/libigl/libigl/blob/f6b406427400ed7ddb56cfc2577b6af571827c8c/cmake/LibiglWindows.cmake) (that sets `MSVC_RUNTIME` to `static` by default), because of Embree, and more specifically to be able to compile and link the unit tests. Embree has this [msvc_post.cmake](https://github.com/embree/embree/blob/e766297adcdaf8e5d8dd996c15aed753255230fd/common/cmake/msvc_post.cmake) file that will mess around with `/MT` and `/MD` flags. Now, you should be able to override this `MSVC_RUNTIME` (it's not an option, CMake options can only be ON/OFF) if you set it yourself before including libigl (maybe you have to `FORCE` the setting of the variable, since it is cached).

Anyway, you could argue that we shouldn't set `EMBREE_STATIC_RUNTIME` to true, and maybe you're right. If you can make a PR that changes this behaviour, but that can still compiles the embree unit tests on AppVeyor without, we'd be happy to review it. We want to link statically against embree in the client code so we don't have to move dll around, and that should be the default option.

**Comment by evouga** [comment]
To be clear, here are the problems:
 - libigl now statically links the C++ runtime by default. This makes the library harder to use for most Windows users.
 - libigl has added a flag MSVC_RUNTIME to control the runtime settings. This is a good idea (if it defaults to dynamic linking) but this flag should a) be documented and b) appear in the CMake GUI.
 - MSVC_RUNTIME is not correctly tied to the subordinate options in the external libraries, such as USE_MSVC_RUNTIME_LIBRARY_DLL
 - subordinate options like USE_MSVC_RUNTIME_LIBRARY_DLL appear in the CMake GUI, despite not doing what they say

If the cause of all of these problems are some internal misconfigured unit tests, I am happy to send a pull request that deletes them vigor...

**Comment by jdumas** [comment]
I understand those problems. But please remember that none of the libigl maintainers are Windows users, so we support Windows to the best of our ability, but since we don't use Windows every day Windows support is more of a by-product.

The requirements are pretty simple. We favour static linkage by default, so that user don't have to move around dlls, and when you build from source with your project libigl should also be statically linked to your project. It's ok to add configuration options to accommodate different use case.

If you want to give it a shot feel free to do so.

**Comment by dpshamonin** [comment]
Dear @jdumas,
Could you please fix this linking issues. I am getting the same errors after update to the latest version (below). Spend quite some time trying to figure out what is changed and why. If @evouga already have good solution I will appreciate the linking fix.

igl.lib(writeWRL.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in ...
...
libcpmt.lib(xwctomb.obj) : error LNK2005: _Getcvt already defined in msvcprt.lib(MSVCP140.dll)

**Comment by BruegelN** [comment]
@dpshamonin as a quickfix you could change the runtime library manually: https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019#to-set-this-compiler-option-in-the-visual-studio-development-environment

Depending on what you mean by "update to the latest version" (from 2.0.0 to 2.1.0/current master branch?) it might be required to let cmake generate a new solution. To do so remove/backup old build-dir, run CMake again and then compile everthing again.

**Comment by dpshamonin** [comment]
Yes, it is on the master branch. I don't like temp or hack fixes in projects files. They will be overwritten by CMake every time you press **Generate**.

I have two projects in my solution:
1. DLL project **Multi-threaded DLL (/MD)** which compiles and runs well. 
2. Google Unit test **static** app, with all my unit tests. For this linking is broken after **libiglWindows.cmake** was introduced.

**Comment by evouga** [comment]
@dpshamonin As a quick fix, try adding

`set(MSVC_RUNTIME "dynamic")`

near the beginning of your CMakeLists.txt file. It should make most linking work like in the previous libigl version (unless you are using Embree? I'm not sure).

@jdumas I use Windows but I'm pretty novice when it comes to CMake or how the various external libraries work.

**Comment by jdumas** [comment]
Ok. I will try to take a look at a proper fix whenever I have some free cycles then.
