### ISSUE TITLE
Mesh Mesh Intersection

### ISSUE THREAD

**Issue by ryanlukejohns** [libigl/libigl#1248]
#### Describe your issue
[not an issue, just asking to be pointed in the right direction]

I'm trying to get the polyline of intersection between two triangle mesh objects, example below:
![image](https://user-images.githubusercontent.com/17732384/60849837-e05c2600-a1ec-11e9-9bc0-e806f40d1dd1.png)

If left alone, my strategy would probably be to use [intersect_other](https://github.com/libigl/libigl/blob/master/include/igl/copyleft/cgal/intersect_other.h) to first find the triangles that intersect, and then loop through each triangle intersection pair to find the line of intersection (i.e. jump to step five of Moller's fast triangle-triangle intersection), and then sort and combine these.

But...I thought I'd check if something like this is already implemented somewhere I'm not looking or if there's a better strategy to consider.  In my case, the relevant mesh surfaces are clean open triangle meshes.

Thanks!

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by alecjacobson** [comment]
For the case where the inputs are manifold and you don't worry about
co-planar intersections you could use:

https://github.com/libigl/libigl/blob/master/include/igl/extract_non_manifold_edge_curves.h

on the combined mesh to identify the non manifold edges (along the
intersection curve).

**Comment by ryanlukejohns** [comment]
This is super helpful, thank you!  Actually I didn't know about ```igl::cgal::remesh_self_intersection``` which is super helpful for this.

**Comment by dnjiang** [comment]
@alecjacobson I tried to follow the instructions in this thread but I'm having some trouble. We are looking to do the same type of operation as described by the original poster: we have two surface meshes and we want to find the line (or lines) of intersection where they cross.

The problem is that I'm very new with libigl. I have an application which compiles and runs but I can't seem to figure out how to use the output from extract_non_manifold_edge_curves(). Once we get the edge curves using this function, we need to get the 3D coordinates associated with each edge.

I tried to find some example usage of extract_non_manifold_edge_curves() but I didn't find anything...maybe I'm just looking in the wrong places. A worked example showing how to get the 3D coordinates from the edge curves would probably be sufficient to solve this problem for me.

In case it helps, here is some pseudo code representing the operation as we currently have it:
//Assume we start with VA, FA, VB and FB as the vertex and face matrices of the two input surfaces

//The first step is to combine the surfaces into a single mesh
vector<MatrixXd> PointCollection[2];
PointCollection[0] = VA;
PointCollection[1] = VB;

vector<MatrixXi> FaceCollection[2];
FaceCollection[0] = FA;
FaceCollection[1] = FB;

MatrixXd VC;
MatrixXi FC;
igl::combine(PointCollection, FaceCollection, VC, FC);

//The second step is to remesh the combination
MatrixXd VFinal;
MatrixXi FFinal;
MatrixXi _1;
VectorXi _2, _3;
igl::copyleft::cgal::remesh_self_intersections(
      VC, VF,
      igl::copyleft::cgal::RemeshSelfIntersectionsParam(false, false, false),
      VFinal, FFinal,
      _1, _2, _3);

//Get the edges for the combined and remeshed faces
MatrixXi E, uE;
MatrixXi EMAP;
vector<vector<int>> uE2E;
igl::unique_edge_map(FFinal, E, uE, EMAP, uE2E);

//Actually get the collection of intersecting edges
vector<vector<size_t>> curves;
igl::extract_non_manifold_edge_curves(FFinal, EMAP, uE2E, curves);

//And then "curves" has a bunch of stuff that I don't know what to do with.

**Comment by ryanlukejohns** [comment]
So, I ended up doing this a bit differently because I also needed the inside faces in addition to the edges.  As one of my surfaces was closed, I remeshed self intersections, found faces that were inside the other shape using fast_winding_number, and could then get the boundary loop of that.  Maybe not the best approach...but did the trick for me!

Quickly glancing over your code, I _think_ that in your case "curves" is referencing indices in "E" where E is an (#FFinal x 3) by 2 list of indices referencing VFinal.  So:
```VFinal.row(E(curves[i][j],0))``` is the first point on the jth edge of the ith intersection curve, and 
```VFinal.row(E(curves[i][j],1))``` is the second point on the jth edge of the ith curve.
