### ISSUE TITLE
How to add a face overlay?

### ISSUE THREAD

**Issue by ghost** [libigl/libigl#1269]
#### Describe your issue
I checked the Overlays section of the tutorial and read the exposition therein for overlayed points and edges. I was wondering if there is any API for overlayed faces, like add_faces (I didn't find it). If there is, please let me know. If not, I have to draw the overlayed faces manually, right? But how to render one part of the mesh in one color, while another part in another color? Thank you.
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
There is no overlay for faces, you need to draw them as part of a triangle mesh. Note that you can have multiple meshes (ViewerData) now, so that should make it easier. If you want to render parts of a mesh in different color, you can add a color attribute to either faces or vertices, depending on which one you need.

**Comment by zhfsu** [comment]
Thank you very much, jdumas. I drew the face overlay manually using multiple meshes and now my code works as desired. When working with multiple meshes, however, I noticed some counter-intuitive behavior when elements like faces or edges coincide. I will start a new thread on it. Thank you again for your help. This ticket can be closed.
