### ISSUE TITLE
BUG in the framefield quad meshing in IGLlib

### ISSUE THREAD

**Issue by danielepanozzo** [libigl/libigl#129]
From a personal email:

Hi Daniele,

I was using your igllib library (which is really amazing btw) and trying to run the FrameField example here: http://libigl.github.io/libigl/tutorial/506_FrameField/main.cpp

The example code crashed with some kind of out of index error.

The culprit was these three lines from https://github.com/libigl/libigl/blob/master/include/igl/comiso/miq.cpp

Eigen::Matrix<typename DerivedV::Scalar, 3, 1> p0 = V.row(Fcut(f,0));
Eigen::Matrix<typename DerivedV::Scalar, 3, 1> p1 = V.row(Fcut(f,1));
Eigen::Matrix<typename DerivedV::Scalar, 3, 1> p2 = V.row(Fcut(f,2));

I'm not totally familiar with what's going on, but I think the cutting of the mesh could lead to new vertices being created, so that Fcut could reference a new vertice which is not present in V. So Vcut should be referenced instead.

Replacing the 3 lines with

Eigen::Matrix<typename DerivedV::Scalar, 3, 1> p0 = Vcut.row(Fcut(f,0));
Eigen::Matrix<typename DerivedV::Scalar, 3, 1> p1 = Vcut.row(Fcut(f,1));
Eigen::Matrix<typename DerivedV::Scalar, 3, 1> p2 = Vcut.row(Fcut(f,2));

removed the out of index error and produced a result which seemed reasonable. I'm not sure if that is the correct fix though.

---Noah

**Comment by danielepanozzo** [comment]
Thanks for the bug fix, the code seems wrong and your fix correct, but I am puzzled since I cannot reproduce it on my machine. Even in debug mode with all the checks enabled, it runs fine for me. 
Before committing the fix, I would like to be able to reproduce it and to make sure that the problem goes away after the fix. Could you please tell me exactly how to reproduce it? Did you use a different mesh?

Thanks!

**Comment by nduncan-cs130** [comment]
Hi Daniele,

I used the code here without any changes: http://libigl.github.io/libigl/tutorial/506_FrameField/main.cpp

so I used the original mesh and constraints file.

My OS is Ubuntu and the compiler is GCC 4.7.3

Maybe the ComISO solver is producing slightly different results because I didn't build it with the same set of solver packages as you did? Here is the output I got from cmake when I was building it: http://pastebin.com/cTTxpqT0

I also think I'm using a slightly different version of Eigen. Because I had to modify this file https://github.com/libigl/libigl/blob/master/include/igl/comiso/frame_field.cpp at lines 216-230:

from

  //olga: is
  Eigen::MatrixXd R;
  Eigen::VectorXd S;
  Eigen::VectorXi b; b.resize(F.rows(),1);
  Eigen::MatrixXd bc; bc.resize(F.rows(),3);
  int num = 0;
  for (unsigned i=0; i<F.rows(); ++i)
    if(thetas_c[i])
      {
        b[num] = i;
        bc.row(num) = theta2vector(TPs[i],thetas(i));
        num++;
      }
  b.conservativeResize(num,Eigen::NoChange);
  bc.conservativeResize(num,Eigen::NoChange);

to

  //olga: is
  Eigen::MatrixXd R;
  Eigen::VectorXd S;
  Eigen::MatrixXi b; b.resize(F.rows(),1);
  Eigen::MatrixXd bc; bc.resize(F.rows(),3);
  int num = 0;
  for (unsigned i=0; i<F.rows(); ++i)
    if(thetas_c[i])
      {
        b(num, 0) = i;
        bc.row(num) = theta2vector(TPs[i],thetas(i));
        num++;
      }
  b.conservativeResize(num,Eigen::NoChange);
  bc.conservativeResize(num,Eigen::NoChange);

to get the code to compile.

Let me know if you need any more info.

Thanks,
Noah

**Comment by danielepanozzo** [comment]
Got it! I can reproduce it with gcc 4.7, but not with clang, very strange since this is indeed an indexing bug. I pushed your fix to the main repository.

I suggest to use the same version of Eigen for both comiso and libigl, this is quite easy if you follow the new compilation isntructions for comiso in the tutorial: http://libigl.github.io/libigl/tutorial/tutorial.html#chapter1:introductiontolibigl

I am closing this issue for now, please let me know if you have any other problem.

Thanks,
Daniele
