### ISSUE TITLE
compile without embree?

### ISSUE THREAD

**Issue by tbarton16** [libigl/libigl#1302]
#### Describe your issue
i cannot compile the python bindings without this error.

libigl/external/embree/kernels/common/device.cpp:111:5: error: no member named 'rayStreamFilterFuncs' in
      namespace 'embree::sse41'; did you mean simply 'rayStreamFilterFuncs'?
    SELECT_SYMBOL_DEFAULT_SSE42_AVX_AVX2_AVX512KNL_AVX512SKX(enabled_cpu_features,rayStreamFilterFuncs);

i have an old mac. is the package functional without this library? all i need are a few functions.
i have to use python 2.7. so that i can import the python module to houdini. houdini python is 2.7 
#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ x] Mac OS X
- [ ] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jiangzhongshi** [comment]
Regarding the question: during cmake, you can try to invoke `cmake -DLIBIGL_WITH_EMBREE=OFF ../`

However, from my experience, this kind of problem is usually not because of the Embree itself, but rather due to the linking to the wrong python version. 
https://github.com/libigl/libigl/blob/master/python/CMakeLists.txt#L25 specifies the versions 3.x
you can try to change them to 2.7, and also set PYTHON_LIBRARIES and PYTHON_INCLUDE_DIR on the previous lines.

**Comment by daviesthomas** [comment]
I had same issue and resolved by building from python sub directory and disabling embree.

cd python
mkdir build
cd build
cmake -DLIBIGL_WITH_EMBREE=OFF -DLIBIGL_USE_STATIC_LIBRARY=ON ..
make

**Comment by BruegelN** [comment]
Just wanted to let you know that this is indeed an bug with embree: https://github.com/embree/embree/issues/262
I've tried it on my 2014 MBP with latest macOS + XCode/Clang and ran into the same issue.
However the solution suggested by @jiangzhongshi is the way to go for now.
