### ISSUE TITLE
Embree CMake Bug on Mac

### ISSUE THREAD

**Issue by qnzhou** [libigl/libigl#131]
The following line causes the flag ``-stdlib=libc++`` to be added for gcc compilers on mac, which breaks the compilation of the tutorial.

https://github.com/embree/embree/blob/master/common/cmake/gcc.cmake#L40

**Comment by alecjacobson** [comment]
@danielepanozzo I asked James to paste this here because we should settle on a support policy for GCC on mac os x. It seems this particular problem is embree's "fault". But I foresee possible issues down the line.

Should we write that we support gcc or clang on mac os x or should we explicitly write that only clang is supported?

**Comment by danielepanozzo** [comment]
I vote for only clang, gcc is painful to support on mac and there are no "official" releases of gcc for mac. 

I would go for:
MacOSX: Clang
Linux: GCC
Windows: VS 2015

**Comment by alecjacobson** [comment]
I'm inclined to agree. By " official" do you mean released built in by
Apple?

**Comment by danielepanozzo** [comment]
Yes, Apple was shipping a version of gcc 4.2 with xcode a while ago, but it is now discontinued and they only ship clang with the new versions of xcode.

**Comment by alecjacobson** [comment]
OK. So this one's filed away as a bug in _Embree_'s cmake and not high priority for libigl because of the "non-standard" build setup.
