### ISSUE TITLE
Reveal name of failing mesh during unit test

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1321]
In a unit test that applies the pattern:

```
TEST_CASE("my test", "[igl]")
{
  const auto test_case = [](const std::string &param)
  {
    ...
  };
  test_common::run_test_cases(test_common::all_meshes(), test_case);
}
```

If I run `ctest -R "my test"` I see the output for a failure as:

```
ctest -R "my test"
Test project /usr/local/libigl/build
    Start 48: my test
1/1 Test #48: my test .......................***Failed    0.02 sec
```

How can I get the name of the failing mesh(es)?

(Running `ctest` with the `--verbose` flag doesn't reveal it)

**Comment by alecjacobson** [comment]
(I'm just assuming this pattern is the correct thing to do based on existing tests. But perhaps this is not the right way to do multiple tests in catch2...)

**Comment by jdumas** [comment]
You can also run `./libigl_test <test_name>` and see the log of the test on stdout. It should also be recorded into the folder `Testing/Temporary/` where a copy of the stdout of the last failing test should be displayed. Finally, there is something known as [DYNAMIC_SECTION](https://github.com/catchorg/Catch2/blob/master/docs/other-macros.md), which can be used to isolated test sections dynamically (but it has some [limitations](https://github.com/catchorg/Catch2/blob/master/docs/limitations.md)). Honestly though we might as well hardcode one section per mesh being tested, since the list is fixed and known in advance.

**Comment by alecjacobson** [comment]
Thanks. That let's me print messages that I code into the test at least.

Meanwhile, I found that I could overload our `run_test_cases` and add an `INFO( ... ) ` command that will append failures with a "message". Then in verbose mode, `ctest` will print something like this:
```
48: ...............................................................................
48: 
48: /usr/local/libigl/tests/include/igl/icp.cpp:50: FAILED:
48:   REQUIRE( 1e-12 > (R-R0).norm() )
48: with expansion:
48:   0.0 > 0.0000013909
48: with message:
48:   cube.obj
```

I'll push this at least. I like what you suggest about sections as an ultimate goal.
