### ISSUE TITLE
Decimation fails

### ISSUE THREAD

**Issue by cdcseacave** [libigl/libigl#1359]
I am testing the decimation functionality and more often then not it fails in the following assert:
```
for(int j = 0;j<i;j++) assert(std::abs(S.row(j).dot(ei)) < 1e-10);
```
in `per_vertex_point_to_plane_quadrics.cpp`

I'm using the header only version on Windows 10 x64, VC2019.

I fails on any mesh a bit more complex (>1M faces) when trying to decimate to <20%. All are manifold meshes. I'm using the `qslim` weights.

**Comment by jdumas** [comment]
Can you share the mesh that is failing, along with a minimal code to reproduce?

**Comment by cdcseacave** [comment]
Pls find them bellow; you only need to add a way to read the PLY file, I am not familiar enough with igl to do that quick. Thx!
[globe.zip](https://github.com/libigl/libigl/files/3888493/globe.zip)

PS: is there a special reason for using `int` for indices or can be switched to `unsigned int` (doubling the range)?

**Comment by cdcseacave** [comment]
Commenting out that assert, fails later in `circulation` in what looks like an infinite loop that keeps growing the memory through: `N.push_back(fi);`

**Comment by 714865387** [comment]
> 注释掉该断言，稍后会`circulation`在看起来像无限循环的情况下失败，该循环通过以下方式不断增加内存：`N.push_back(fi);`
Hello, I have encountered the same problem as you, how do you solve it, thank you very much

**Comment by alecjacobson** [comment]
The input model is too messy to process with `decimate` directly. Decimate requires a manifold input mesh (boundaries are OK if you follow `qslim`). Your model has:
 - 5 unreferenced vertices
 - 660 combinatorially duplicate faces 
 - 74 geometrically degenerate faces
 - 2 conflictingly oriented edges 

> PS: is there a special reason for using `int` for indices or can be switched to `unsigned int` (doubling the range)?
Most methods are templated well enough to use larger ints.

I also wonder _why_ though. The maximum int32 is  2,147,483,647. Do you really have meshes with 2 trillion elements? I don't think libigl is a good library for such data since everything is always assumed to fit in memory.

It's often convenient to use `-1` as a special "NotanIndex" type placeholder.

Meanwhile using things like `size_t` has caused a nightmare with windows/linux/mac-os differences. If anything, I wish we would use `int` _more often_ throughout the code.
