### ISSUE TITLE
MatlabWorkspace.h does not compile. (can't find mat.h)

### ISSUE THREAD

**Issue by psarahdactyl** [libigl/libigl#1392]
#### Describe your issue
I am trying to export some of my matrices into a format that I can work with in matlab. (DMAT works fine for now) But when I try to save those same matrices to a matlab workspace, I can't compile.
...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [x] I have tried the `dev` branch and the problem persists

**Comment by alecjacobson** [comment]
Can you paste your full compilation error?

Did you add IGL_WITH_MATLAB=ON to your cmake and igl::matlab to your target?

**Comment by jdumas** [comment]
Just FYI, if you want to save/load matrices to work with Matlab, you can `#include <unsupported/Eigen/SparseExtra>` and use `saveMarket()` or `saveMarketVector()` (for sparse matrices and vectors).

**Comment by psarahdactyl** [comment]
> Did you add IGL_WITH_MATLAB=ON to your cmake and igl::matlab to your target?

No, at first I hadn't added those to my cmake file. But after adding them, I couldn't generate build files because the FindMATLAB.cmake doesn't find my version of matlab. 

Unrelated to this specific issue, but FindMOSEK.cmake also does not support the latest version(s) of it.

@jdumas I will try your suggestion!

**Comment by alecjacobson** [comment]
`LIBIGL_RESTRICTED_MATLAB` and `igl_restricted::matlab` are the new keywords necessary to use the `igl/matlab` stuff.

The mosek module is fading from support. I think it's unlikely to stay maintained by me because they keep changing subtle things in the API. Would be happy to merge PRs for it though. Please open a new issue for that if it's important.
