### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by roaasoloh** [libigl/libigl#1405]
#### Describe your issue
I'm using python-binding, applying principal curvature using the command: 

`v1, v2, k1, k2 = igl.principal_curvature(v, f)
`

but I'm getting the error:

`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
`

v are in this format:

`[[  56.09962091  -50.70284252   74.43154099]
 [ -81.66580634   31.11304083  -96.20692408]
 [ -63.04710378   20.05579935  -73.14550082]
 [ -74.68074967  -46.74132945 -125.53300517]
 [ -82.86191115  138.50006684    4.60130311]
 [  73.56470904 -118.43376944  -71.32137773]
 [  -4.92233919 -159.90066014  -27.83674232]
 [ -75.62714176   28.23358687  -78.90299045]
 [ -81.53924671  121.62689731   52.15735424]
 [-119.16738782   84.67573099   64.81959086]
 [ 115.65943449  -56.67805099  -75.6967053 ]
 [ -80.48401851   20.7915225   -68.63223673]
 [-142.29170674 -108.38603014  -36.96969018]
 [  98.64894284   50.12674432   58.67070153]
 [ -28.13477169   83.20510976  107.46559988]
 [-144.66277425   68.30107727   49.66061848]
 [  29.54206082  143.22321321  -55.06127287]
 [   4.90252259   69.73588386 -132.70296423]
 [-102.13321016  -67.17764799 -111.93319288]
 [-166.21385932   13.10544553  -15.81392708]
 [ -38.58577129  144.34755316   28.37260346]
 [  56.31233339  -61.38765368   64.17787867]
 [ -90.93979735    0.38020425  -79.89511472]
 [ -96.76884596   21.71346256  -64.96037686]
...
 [  74.58292415 -124.48759489   -5.62172548]
 [-174.78859069  -11.99712938  -11.00922369]
 [  87.27561955   69.94477948 -108.91576776]
 [ 117.33246385  -69.39698438   16.03177459]
 [ 103.92915334   60.71174874  -89.2834191 ]
 [  11.60050005  104.17767979   85.44092131]
 [  45.99420387  -75.99419561 -145.5603443 ]
 [ -75.78031523    8.32746322  -78.40591649]
`

and f are: 

`[[  0 165 425]
 [  0 836 165]
 [  0 128 836]
 [  0 107 128]
 [  0 542 107]
..
 [  0 425 164]
 [425 120 834]
 [425 165 120]
 [165 726 120]
 [165 836 726]
`

As well if I used the gaussian curvature it prints out the results but with giving `nan` values!!! 

`[       nan 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531
 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531
 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531
 6.28318531 6.28318531 6.28318531 3.15422311 6.28318531 6.28318531
 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531
 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531
 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531
 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531
 6.28318531 6.28318531 6.28318531 3.14159265        nan 6.28318531
 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531
`
 as well the error in the title.

Please any help!
...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jiangzhongshi** [comment]
Hi,

Can you post here the complete file, or v/f so that we can check?

**Comment by teseoch** [comment]
@roaasoloh is this sill an issue (i.e., can you try to get the latest version of the bindings)?
if so, can you provide us with the input?

**Comment by tillns** [comment]
Hi,
I'm currently using the latest igl Python binding, and the error still seems to be present. 

Here are the vertices:
`[[ 1.02215743e+00  1.51858025e+01  1.09268203e-02]
 [ 6.26542628e-01  1.53214903e+01 -2.67589599e-01]
 [ 3.61615956e-01  1.50164423e+01 -1.61229614e-02]
 [ 5.84533632e-01  1.49415302e+01  1.44851089e-01]
 [ 8.74769270e-01  1.47847586e+01  4.29917634e-01]
 [-8.27025771e-01  1.69986820e+01 -1.17356527e+00]
 [-1.12477744e+00  1.70413914e+01 -1.13215625e+00]
 [-1.40026188e+00  1.67737274e+01 -8.59123290e-01]
 [-1.03100395e+00  1.67560978e+01 -9.10715699e-01]
 [ 3.35406125e-01  1.56724138e+01 -6.62138402e-01]
 [ 2.28211939e-01  1.53945293e+01 -4.22880620e-01]
 [ 9.14253175e-01  1.56641665e+01 -5.48225403e-01]
 [-2.14428991e-01  1.54236002e+01 -3.92413497e-01]
 [ 1.21344462e-01  1.51487093e+01 -1.96694657e-01]
 [-3.38915527e-01  1.51461639e+01 -1.54734567e-01]
 [-3.09857893e+00  1.33291245e+01  1.35811174e+00]
 [-2.67857695e+00  1.36087933e+01  1.19380152e+00]
 [-2.81388450e+00  1.38037472e+01  1.13650143e+00]
 [-2.91740561e+00  1.40242128e+01  1.06645668e+00]
 [-3.45888901e+00  1.35071783e+01  1.48832488e+00]
 [-2.51650620e+00  1.34234858e+01  1.24288428e+00]
 [-3.66784978e+00  1.37902460e+01  1.51888084e+00]
 [-2.97310019e+00  1.42834148e+01  9.81191933e-01]
 [-1.46837425e+00  1.53315210e+01  2.42557898e-01]
 [-1.04321468e+00  1.54301844e+01 -1.14068240e-02]
 [-1.23892570e+00  1.55935936e+01 -1.90569367e-02]
 [-1.47737443e+00  1.50593319e+01  4.02298689e-01]
 [-8.24701250e-01  1.51975393e+01  6.36637118e-03]
 [-9.56804931e-01  1.59133129e+01 -3.65977734e-01]
 [-1.50627029e+00  1.57050619e+01 -6.28381921e-03]
 [-1.31856656e+00  1.45267353e+01  5.63859105e-01]
 [-1.33342600e+00  1.48189297e+01  4.61312950e-01]
 [-1.72300303e+00  1.43726091e+01  7.75573313e-01]
 [-8.64554107e-01  1.48195562e+01  2.28964135e-01]
 [-1.86069405e+00  1.45354557e+01  7.51255095e-01]
 [-4.27961636e+00  1.44336128e+01  1.64600301e+00]
 [-4.19462347e+00  1.46003504e+01  1.34666049e+00]
 [-4.60378790e+00  1.46022406e+01  1.56086349e+00]
 [-4.24766588e+00  1.41562271e+01  1.96538568e+00]
 [-3.87627745e+00  1.41725483e+01  1.59095132e+00]
 [-4.26743889e+00  1.47390881e+01  1.18650198e+00]
 [-3.80739594e+00  1.47956753e+01  8.67102265e-01]
 [-4.61431313e+00  1.47941227e+01  1.29830432e+00]
 [-1.98495793e+00  1.46906786e+01  7.20991373e-01]
 [-3.83621073e+00  1.35950527e+01  1.87037373e+00]
 [-4.03461838e+00  1.39363356e+01  1.88785946e+00]
 [-4.17098475e+00  1.37470522e+01  2.15245485e+00]
 [-4.04657888e+00  1.34257956e+01  2.18223882e+00]
 [-2.03729367e+00  1.58202181e+01  7.95904920e-03]
 [-1.63920426e+00  1.58852720e+01 -1.18278429e-01]
 [-1.58006334e+00  1.61571579e+01 -3.38202596e-01]
 [-1.16387630e+00  1.62426834e+01 -4.91907477e-01]
 [-1.52152789e+00  1.64382896e+01 -5.75112820e-01]
 [-1.18533814e+00  1.60011959e+01 -3.44520450e-01]
 [-1.87111449e+00  1.56162119e+01  1.60564169e-01]
 [-6.85220242e-01  1.62924671e+01 -6.86592042e-01]
 [-4.47239351e+00  1.52189274e+01  7.93192148e-01]
 [-4.09945488e+00  1.52452316e+01  6.86623693e-01]
 [-3.78725958e+00  1.56826143e+01  4.50750589e-01]
 [-4.50520277e+00  1.49947910e+01  1.01141381e+00]
 [-4.41786432e+00  1.54150000e+01  6.38589382e-01]
 [-4.90080976e+00  1.50180149e+01  1.08429730e+00]
 [-3.97376031e-01  1.60602646e+01 -7.03448176e-01]
 [-3.74214697e+00  1.52272787e+01  6.65865123e-01]
 [-2.08264017e+00  1.55742788e+01  2.08431736e-01]
 [-1.04331914e-02  1.63712578e+01 -1.07154083e+00]
 [ 2.15754181e-01  1.61016026e+01 -9.89566624e-01]
 [-4.25718641e+00  1.49578371e+01  9.37130868e-01]
 [-4.96398735e+00  1.48356962e+01  1.34925461e+00]
 [-3.82829833e+00  1.49913502e+01  8.07891071e-01]
 [-3.31974268e+00  1.52186747e+01  7.42534339e-01]
 [-3.14399981e+00  1.54564667e+01  5.88997006e-01]
 [-3.22912908e+00  1.50636902e+01  7.73096561e-01]
 [-3.01924086e+00  1.53157911e+01  6.38373673e-01]
 [-2.96205282e+00  1.51177616e+01  7.03146935e-01]
 [-2.06288528e+00  1.24228849e+01  2.02705288e+00]
 [-2.19795227e+00  1.19648695e+01  2.14035177e+00]
 [-1.86553538e+00  1.19877329e+01  1.90443981e+00]
 [-1.62759721e+00  1.24274025e+01  1.70791709e+00]
 [-2.35120702e+00  1.26209373e+01  1.92072010e+00]
 [-2.74466228e+00  1.26713142e+01  2.38331842e+00]
 [-2.44261146e+00  1.24589624e+01  2.38310719e+00]
 [-2.64533997e+00  1.27133646e+01  1.80600500e+00]
 [-1.14120710e+00  1.65062866e+01 -6.91442966e-01]
 [-7.99112976e-01  1.65115604e+01 -7.80329525e-01]
 [-7.01908350e-01  1.67254868e+01 -9.62717712e-01]
 [ 4.28085476e-02  1.67142658e+01 -1.23504829e+00]
 [-2.62791902e-01  1.68195572e+01 -1.21769094e+00]
 [-5.43560684e-01  1.69204979e+01 -1.20009041e+00]
 [ 3.93261194e-01  1.66182003e+01 -1.25269508e+00]
 [-5.29929221e-01  1.55458708e+01 -3.49375665e-01]
 [-1.05931602e-01  1.56618662e+01 -5.81269503e-01]
 [-2.42505342e-01  1.58176594e+01 -6.51046455e-01]
 [-7.28466392e-01  1.57568760e+01 -3.52411300e-01]
 [-3.65626359e+00  1.27726164e+01  2.29647946e+00]
 [-3.15349841e+00  1.27535849e+01  2.26246667e+00]
 [-3.37589622e+00  1.30097933e+01  1.82376230e+00]
 [-3.83905959e+00  1.30692844e+01  2.23415065e+00]
 [ 1.52630761e-01  1.58349810e+01 -7.69919276e-01]
 [-2.91528583e+00  1.29233246e+01  1.59830344e+00]
 [-3.63127995e+00  1.32700100e+01  1.86770439e+00]
 [ 8.96006644e-01  1.58968573e+01 -7.91312814e-01]
 [ 6.17836177e-01  1.59854231e+01 -9.31819320e-01]
 [ 7.80324399e-01  1.65311203e+01 -1.25628507e+00]
 [ 9.36897397e-01  1.62695065e+01 -1.15414822e+00]
 [ 1.17340827e+00  1.64397488e+01 -1.22304785e+00]
 [-2.08464432e+00  1.31073389e+01  1.31697559e+00]
 [-2.31934929e+00  1.32477808e+01  1.28588784e+00]
 [-8.22448850e-01  1.14440985e+01  2.33826637e+00]
 [-3.31479132e-01  1.16452503e+01  2.40074897e+00]
 [-7.00218320e-01  1.22449722e+01  2.10973883e+00]
 [-1.21817994e+00  1.20080137e+01  2.11527967e+00]
 [-1.34812403e+00  1.13420486e+01  2.00543141e+00]
 [-3.10586005e-01  1.22015953e+01  2.24432254e+00]
 [ 1.10748686e-01  1.18011599e+01  2.54542851e+00]
 [-1.83257031e+00  1.30504351e+01  1.31848216e+00]
 [-1.14571118e+00  1.26081638e+01  1.67572796e+00]
 [-3.33431929e-01  1.28185377e+01  1.85208845e+00]
 [-7.83530831e-01  1.28284769e+01  1.65771508e+00]
 [-1.60642397e+00  1.31228065e+01  1.26882577e+00]
 [-1.45657182e+00  1.33292799e+01  1.16343248e+00]
 [-3.80986691e-01  1.42460413e+01  6.61965013e-01]
 [ 1.60498634e-01  1.46545477e+01  3.79292339e-01]
 [-4.76209730e-01  1.44780045e+01  4.27075177e-01]
 [ 4.05402705e-02  1.39981956e+01  1.00156534e+00]
 [-8.79025817e-01  1.41337767e+01  5.88034153e-01]
 [-6.53751075e-01  1.36992292e+01  1.01807082e+00]
 [-2.33129546e-01  1.47943268e+01  1.31088212e-01]
 [ 6.56033456e-01  1.43591175e+01  8.23918402e-01]
 [-9.06346679e-01  1.44724798e+01  4.23165113e-01]
 [-1.69066238e+00  1.70055561e+01 -1.00406909e+00]
 [-1.98240495e+00  1.68099079e+01 -8.17710102e-01]
 [-2.00127220e+00  1.66608353e+01 -6.98744416e-01]
 [-1.98660028e+00  1.64827728e+01 -5.55569828e-01]
 [-1.42390454e+00  1.70440083e+01 -1.07535601e+00]
 [-1.88429880e+00  1.69264469e+01 -9.18407917e-01]
 [-4.65453911e+00  1.55118427e+01  6.09600544e-01]
 [-4.00878811e+00  1.57520304e+01  3.95148546e-01]
 [-4.20696068e+00  1.58328953e+01  3.32732797e-01]
 [-4.39612150e+00  1.59165754e+01  2.66819358e-01]
 [-4.82226515e+00  1.55929003e+01  5.66667140e-01]
 [-4.89495993e+00  1.57005444e+01  4.96629655e-01]
 [-4.61194229e+00  1.59850807e+01  2.08205447e-01]
 [-1.46934128e+00  1.39177942e+01  9.04371500e-01]
 [-1.41364479e+00  1.36192541e+01  1.02806151e+00]
 [-1.58536196e+00  1.41725998e+01  8.20194006e-01]
 [-5.26477480e+00  1.50886946e+01  1.09077322e+00]
 [-4.88144398e+00  1.51670532e+01  9.08426821e-01]
 [-5.33226061e+00  1.51931305e+01  9.70792830e-01]
 [-4.87420893e+00  1.52982864e+01  7.76006043e-01]
 [-5.15095854e+00  1.53525982e+01  7.72956550e-01]
 [-5.39703655e+00  1.54342747e+01  7.27277219e-01]
 [-1.99899125e+00  1.60562019e+01 -1.93821073e-01]
 [-1.98044920e+00  1.62791691e+01 -3.85390818e-01]
 [-5.71529770e+00  1.59262161e+01  2.16169864e-01]
 [-5.36502743e+00  1.58959112e+01  2.93171704e-01]
 [-5.26872873e+00  1.59972219e+01  1.75761983e-01]
 [-5.88986969e+00  1.57348766e+01  3.88431132e-01]
 [-5.60119963e+00  1.56201601e+01  5.31922936e-01]
 [-5.13491726e+00  1.58538265e+01  3.39448482e-01]
 [-3.55214930e+00  1.56208572e+01  5.00333428e-01]
 [-3.32855105e+00  1.55520210e+01  5.45418978e-01]
 [ 2.04475820e-01  1.24835634e+01  2.35692239e+00]
 [ 2.88747549e-01  1.33266315e+01  1.66389930e+00]
 [-5.40960550e+00  1.55389547e+01  6.29134059e-01]
 [-5.03724909e+00  1.57449303e+01  4.51465189e-01]
 [-3.87171030e+00  1.43948498e+01  1.34267843e+00]
 [-3.66223884e+00  1.42352142e+01  1.17742920e+00]
 [-3.32766461e+00  1.46023350e+01  9.00593817e-01]
 [-3.89018106e+00  1.45347185e+01  1.16053009e+00]
 [-2.97836351e+00  1.45734110e+01  8.84457886e-01]
 [-6.27600729e-01  1.32094650e+01  1.42048478e+00]
 [-2.65142411e-01  1.34307480e+01  1.34341788e+00]
 [-2.96008158e+00  1.48633814e+01  7.87366867e-01]
 [-3.35672712e+00  1.47819843e+01  8.58308554e-01]
 [-2.07759786e+00  1.48675728e+01  6.59182847e-01]
 [-1.85132360e+00  1.50457048e+01  5.54185033e-01]
 [-2.12201858e+00  1.50809212e+01  5.49951255e-01]
 [-1.69667256e+00  1.53898096e+01  2.82827497e-01]
 [-1.88912034e+00  1.54498110e+01  3.03457916e-01]
 [-2.11803269e+00  1.53230581e+01  3.94719005e-01]
 [ 5.89326203e-01  1.39331388e+01  1.25981712e+00]
 [-4.89546585e+00  1.60170097e+01  1.73375115e-01]]`

and here the faces:
`[[  0   1   2]
 [  3   4   0]
 [  2   3   0]
 [  5   6   7]
 [  7   8   5]
 [  9  10  11]
 [ 12  10   9]
 [ 13   1  10]
 [  2   1  13]
 [ 13  10  14]
 [ 11  10   1]
 [ 15  16  17]
 [ 17  18  19]
 [ 17  19  15]
 [ 12  14  10]
 [ 15  20  16]
 [ 18  21  19]
 [ 22  21  18]
 [ 23  24  25]
 [ 26  24  23]
 [ 26  27  24]
 [ 28  29  25]
 [ 30  31  32]
 [ 33  31  30]
 [ 34  32  31]
 [ 31  33  27]
 [ 31  27  26]
 [ 31  26  34]
 [ 35  36  37]
 [ 35  38  39]
 [ 14  27  33]
 [ 40  37  36]
 [ 41  40  36]
 [ 27  14  12]
 [ 40  42  37]
 [ 43  34  26]
 [ 44  45  46]
 [ 47  44  46]
 [ 39  38  45]
 [ 45  44  21]
 [ 45  21  39]
 [ 48  49  50]
 [ 50  49  51]
 [ 52   8   7]
 [ 19  21  44]
 [ 21  22  39]
 [ 28  53  29]
 [ 29  53  49]
 [ 29  49  54]
 [ 53  28  55]
 [ 51  49  53]
 [ 53  55  51]
 [ 56  57  58]
 [ 59  57  56]
 [ 56  58  60]
 [ 61  59  56]
 [ 28  62  55]
 [ 57  59  63]
 [ 49  64  54]
 [ 48  64  49]
 [ 65  55  62]
 [ 66  65  62]
 [ 40  67  42]
 [ 42  67  59]
 [ 42  59  68]
 [ 67  40  69]
 [ 67  69  63]
 [ 63  59  67]
 [ 41  69  40]
 [ 69  41  70]
 [ 69  70  71]
 [ 69  71  63]
 [ 61  68  59]
 [ 72  70  41]
 [ 70  72  73]
 [ 70  73  71]
 [ 72  74  73]
 [ 75  76  77]
 [ 78  75  77]
 [ 79  80  81]
 [ 81  75  79]
 [ 79  82  80]
 [ 52  50  83]
 [ 83  50  51]
 [  8  52  83]
 [ 51  84  83]
 [ 83  84  85]
 [ 83  85   8]
 [ 51  55  84]
 [ 86  85  84]
 [ 55  86  84]
 [ 85  86  87]
 [ 85  87  88]
 [ 85  88   8]
 [ 86  55  65]
 [ 65  89  86]
 [ 88   5   8]
 [ 90  24  27]
 [ 90  27  12]
 [ 12  91  90]
 [ 90  91  92]
 [ 90  92  93]
 [ 90  93  24]
 [ 94  95  96]
 [ 94  96  97]
 [ 91   9  98]
 [ 12   9  91]
 [ 98  92  91]
 [ 95  80  82]
 [ 99  96  95]
 [ 95  82  99]
 [ 92  98  66]
 [ 66  62  92]
 [ 62  93  92]
 [ 96 100  97]
 [ 15 100  96]
 [ 96  99  20]
 [ 96  20  15]
 [ 25  24  93]
 [ 28  25  93]
 [ 62  28  93]
 [ 19  44 100]
 [100  44  47]
 [ 15  19 100]
 [ 47  97 100]
 [101   9  11]
 [101 102   9]
 [ 65  66 103]
 [ 98   9 102]
 [ 66  98 102]
 [102 104  66]
 [104 105 103]
 [103  66 104]
 [106 107  82]
 [ 82 107  99]
 [ 79 106  82]
 [108 109 110]
 [108 110 111]
 [108 111 112]
 [ 20  99 107]
 [113 110 109]
 [109 114 113]
 [ 79 115 106]
 [116 111 110]
 [110 113 117]
 [110 118 116]
 [117 118 110]
 [ 77 112 111]
 [ 78  77 111]
 [116  78 111]
 [ 75  78 115]
 [ 75 115  79]
 [119 115  78]
 [ 78 116 119]
 [116 120 119]
 [121 122 123]
 [124 122 121]
 [121 123 125]
 [125 126 121]
 [121 126 124]
 [122 127 123]
 [  2 127 122]
 [122 124 128]
 [122   4   3]
 [128   4 122]
 [122   3   2]
 [127  13  14]
 [  2  13 127]
 [ 14  33 127]
 [129 123 127]
 [ 33 129 127]
 [130 131 132]
 [133 134 132]
 [132 134 130]
 [129 125 123]
 [131 130 135]
 [  7   6 134]
 [133   7 134]
 [136 137 138]
 [138 139 140]
 [138 140 136]
 [ 60  58 137]
 [136  60 137]
 [141 140 139]
 [142 141 139]
 [125 143 144]
 [120 126 144]
 [144 126 125]
 [145  30  32]
 [145 143  30]
 [143 125 129]
 [143 129  30]
 [146 147 148]
 [148 147 149]
 [148 149 150]
 [147  56  60]
 [ 61  56 147]
 [146  61 147]
 [ 60 149 147]
 [149  60 136]
 [136 150 149]
 [150 140 151]
 [136 140 150]
 [152  50  52]
 [ 48  50 152]
 [ 52 153 152]
 [154 155 156]
 [157 155 154]
 [153  52   7]
 [153   7 133]
 [155 158 159]
 [157 158 155]
 [ 58  57 160]
 [160  57  63]
 [ 63 161 160]
 [114 162 113]
 [ 63  71 161]
 [117 113 162]
 [163 117 162]
 [158 164 165]
 [158 165 159]
 [151 141 164]
 [164 141 165]
 [166  35  39]
 [ 39 167 166]
 [166 167 168]
 [166 168 169]
 [166 169  35]
 [ 22 170 167]
 [ 39  22 167]
 [170 168 167]
 [120 171 126]
 [126 171 172]
 [126 172 124]
 [140 141 151]
 [168 170 173]
 [173 174 168]
 [168 174 169]
 [142 165 141]
 [174 173  74]
 [ 72  41 174]
 [ 74  72 174]
 [ 41 169 174]
 [ 33  30 129]
 [ 36  35 169]
 [ 41  36 169]
 [120 116 118]
 [118 117 171]
 [118 171 120]
 [175 176 177]
 [177 176 178]
 [177 178 179]
 [177 179 180]
 [172 171 117]
 [163 172 117]
 [ 26  23 176]
 [175  43 176]
 [ 43  26 176]
 [ 23 178 176]
 [178  23  25]
 [178  25  29]
 [ 29 179 178]
 [172 163 124]
 [179  29  54]
 [ 54 180 179]
 [163 181 124]
 [ 54  64 180]
 [128 124 181]
 [ 89  65 103]
 [182 155 159]
 [156 155 182]
 [159 165 182]
 [182 165 142]]`

Using these two variables, you can just call the principal curvature function like
`igl.principal_curvature(v, f)`
and then get the error
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

The mesh is a small cutout from a bigger one focusing on the problematic region, which I found out was a relatively small convex cut. The same mesh used to work for me when I didn't have this convex cut in it. See the image below that shows the cut.
![image](https://user-images.githubusercontent.com/11144916/152563242-002db5fa-6fc4-4ea2-a0d5-7610f357cd7d.png)
I assume that the bug happens, because all vertices in the local region (radius is two times the average edge length) are considered for the curvature estimation. However, due to this convex cut, not all of these surrounding vertices are connected to the vertex in question, so that may cause the issue somehow. 

I tried with two different conda versions (Python 3.7 and 3.9) on Ubuntu 20.04.3 LTS and with one conda version (Python 3.9) on Mac OS Big Sur (11.3). Hope this helps.

**Comment by alecjacobson** [comment]
This example works fine now. Assuming it's fixed. Please reopen on https://github.com/libigl/libigl-python-bindings/issues if still an issue.
