### ISSUE TITLE
Unable to use in a project without cmake

### ISSUE THREAD

**Issue by snshn** [libigl/libigl#1428]
#### Describe your issue

I wanted to build a simple C/C++ program that uses libigl and it turned out to be harder than it is with other C++ libraries. The OS  is Ubuntu 19.10 x86_64.

First off, a quick question: why is this library not available via homebrew/apt? If Activision and Epic Games use it and it's GPL, one would think everybody should be able to quickly obtain it without having to go through the process of building. Whatever the reason for that may be, it's outside of the scope of this report, just being curious.
Ok, plowing ahead. I cloned it, built using cmake and did `sudo make install`. Had to install `libblas-dev`, otherwise it went smooth.

main.cpp:
```cpp
#include <igl/readSTL.h>
#include <igl/opengl/glfw/Viewer.h>

Eigen::MatrixXd V;
Eigen::MatrixXi F;

int main(int argc, char *argv[])
{
  // Load a mesh in STL format
  igl::readSTL("mesh.stl", V, F);

  // Plot the mesh
  igl::opengl::glfw::Viewer viewer;
  viewer.data().set_mesh(V, F);
  viewer.launch();
}
```
Running `g++ main.cpp -o my-first-video-game` at first was complaining about Eigen/Core. I go into external/, find that Eigen thing, do the usual cmake ritual, `sudo make install`... doesn't work. I shrugged. Eventually did this `sudo ln -s /usr/local/include/eigen3/Eigen /usr/include/Eigen` and was able to... get to the next error:

```
In file included from main.cpp:1:
/usr/local/include/igl/readSTL.h:64:12: fatal error: readSTL.cpp: No such file or directory
   64 | #  include "readSTL.cpp"
      |            ^~~~~~~~~~~~~
compilation terminated.
```
So the header files include code files, not the other way around? That's very odd. 

This seems like a very good library but the compilation is either oriented at static-only linking (which doesn't work for me, since I want to release my software under a different license than GPLv2 -- likely BSD or Apache), or it implies that every project uses CMAKE and the library is never installed globally -- neither for development nor for running.

I don't really want to use cmake for my project and would like to know if it's feasible to invest time trying to use this library in my project. Thank you.

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by jdumas** [comment]
Hi. If you don't want to use CMake, then restrict your usage to functions that are directly under `include/igl` and nothing else. Those only depend on Eigen, which is another header-only library, and you should be able to compile those without much trouble.

The reason that libigl's headers include a `.cpp` is that we are separating templated function *declarations* from their *definitions*. If the flag `-DIGL_STATIC_LIBRARY`  is defined, then the `.cpp` in not included and the library is compiled with explicit template instantation of the most common types.

And the reason we don't provide an easy way to use libigl's optional modules outside of CMake is that package management in C++ is hot garbage. You should never `sudo make install` something yourself. We also do not provide packages for Linux/macOS because libigl is primarily intended to be used for research code, where relying on libraries installed system-wide is really a **bad** idea. The reason is that research code is often written once, and never updated again. Bundling static versions of your dependencies is basically the only way to ensure you can still compile and run your code 10 years later.

Now, libigl is an open-source project and everyone can contribute. If you want to help package libigl for macOS or Linux we'd be happy to help. But in-source building with CMake will remain be the priority, and the recommended way to use libigl in a project (at least for the foreseeable future).

**Comment by snshn** [comment]
That answers all my questions, thank you.

**Comment by jdumas** [comment]
Btw the license of libigl is MPL, which is a permissive license. I don't see how static-only linking could be an issue for you, but let me know if we can help.

**Comment by snshn** [comment]
I like releasing code into the public domain, or at least using truly free licenses (like BSD and Apache), ergo static linking usually gets in the way of being able to distribute something. I'll look into MPL to see if it may let me use libigl in my project. Thank you for your help, that is very kind of you.
