### ISSUE TITLE
Mesh refinement

### ISSUE THREAD

**Issue by chopwohaa** [libigl/libigl#1433]
Does anyone know if libigl has an implementation for mesh refinement? Like [Corefinement](https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#fig__coref_fig)  in CGAL. Or I should implement it by myself  as flowing steps :

- tri-tri intersection test to create sub-areas(polygons),

-  triangulation polygons.

So, how to implement the first step in libigl?
 #### Thanks.

**Comment by alecjacobson** [comment]
See remesh_intersections

**Comment by chopwohaa** [comment]
#### thanks for the help! 
`intersect_other()` with `stitch_all=true` works nice for me.  More  small question for that

1. `remesh_intersections()` can run parallel? 

2.  If already know which triangles intersected. I can skip intersection detection call `remesh_intersections()` directly, how to build parameter `offending` handly.  I already read intersect_other.cpp but doesn't make sense, sorry for that.

**Comment by alecjacobson** [comment]
1. This is unfortunately complicated because we use CGAL low level types which use unsafe reference counting so even reading could cause a race condition. I believe if all of your inputs start as float, then it should be safe (but beware). 

2. Yes this is possible but probably not documented. @qnzhou  this seems useful to pull out as a function. What do you think?
