### ISSUE TITLE
Python bindings hang/stuck on pre_draw callback

### ISSUE THREAD

**Issue by MichaelRabinovich** [libigl/libigl#1449]
Hey all,

I can't seem to be able to run a minimal libigl python example with an animation (setting is_animating to True, max fps to 30, and some pre_draw callback).
It seems I got a hang-up window when I set any pre_draw callback. In particular I can't seem to run the python version of the ARAP (405) tutorial.

Thanks,
Michael

**Comment by jdumas** [comment]
Are you using the old python bindings from the master branch, or the [new ones](https://libigl.github.io/libigl-python-bindings/) installed via conda?

**Comment by danielepanozzo** [comment]
I think the old ones, the new ones do not have a wrapper for the viewer. 

@MichaelRabinovich We are planning to completely remove the old bindings in a matter of weeks, we recommend to not use them anymore. If you like the viewer it would be great if you could contribute a similar set of wrapper for the new bindings. We are not planning on supporting it since it is a lot of work and we are mostly happy using alternatives such as https://skoch9.github.io/meshplot/

**Comment by MichaelRabinovich** [comment]
Yes the old ones :) Ok too bad, I am missing a bunch of useful features from the igl viewer such as callbacks and picking infrastructure, and in general the ability to run all igl tutorials. Hard to model and play with deformations with a jupyter notebook, I think.

Anyhow meshplot seems nice, and also https://github.com/sunreef/PyIGL_viewer (which I might add some missing features to).
