### ISSUE TITLE
 -march=native

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1450]
Should we be enabling this flag?

For example, adding something like 

```
# https://stackoverflow.com/q/46724267/148668
include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-march=native" COMPILER_SUPPORTS_MARCH_NATIVE)
if(COMPILER_SUPPORTS_MARCH_NATIVE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
endif()

```

**Comment by jdumas** [comment]
People can always set `CMAKE_CXX_FLAGS` to whatever they want if they want to enable it, it's a pretty small change on their side. I don't think enabling it unconditionally is a good idea (it should at least be an option), since it makes applications less portable.

**Comment by alecjacobson** [comment]
What's meant by "portable" here? Like compiling on one machine but running on another? That's probably not the common case for libigl (i.e., we could make an option to opt-out of this).

**Comment by jdumas** [comment]
I would prefer the option to be opt-in rather than opt-out. Power users interested in enabling the flag can already do so very easily (compile with `cmake -DCMAKE_CXX_FLAGS="-march=native" ..`). Why should we maintain additional logic to enable it by default with an option to remove it?

There are plenty of cases where we don't want to enable `-march=native`:
1. For CI with Github Actions, maybe that could lead to subtle bugs that are hardware-dependent and difficult to reproduce
2. When compiling libigl for package managers like Hunter and vpkg, the option should be disabled
3. When compiling libigl into a docker image to be run on multiple machines
4. When compiling libigl into a binary lib for the python bindings for conda
5. When compiling libigl on a HPC cluster where nodes have diverse hardware.

Making the option ON by default will produce incompatible behavior in the cases described above, and in a non-obvious way (you only find out when you deploy on another machine).

**Comment by alecjacobson** [comment]
1-5 sound like power user stuff. Everyday users want fast code on their
computer.

**Comment by jdumas** [comment]
... I don't know what to say. We depend on github action to provide stable CI testing and ensure we have a (somewhat) stable `master` branch (case 1). We already have community support for packaging via hunter/vcpkg (case 2), as well as existing conda package for python bindings (case 4). PyMesh is available via docker image and depends on libigl (case 3). Everyone in Daniele's group is running libigl on a heterogeneous HPC cluster at NYU (case 5), where I've already experienced problems due to using `-march=native` in the past. I don't think I'm pulling hairs with those 5 examples, there's all real-world usages that would be impacted by the change you are proposing.

Can you give me a good reason why `cmake -DCMAKE_CXX_FLAGS="-march=native"` is not a satisfactory solution to your problem? Do you have any benchmark that supports a substantial performance gain using `-march=native` as opposed to the current performance in release?

I mean, people who want "fast code" would run gentoo and compile their own libc with march=native... The average user probably not gonna see the difference.

**Comment by alecjacobson** [comment]
huh? Aren't these all cases of "power users" with esoteric setups or automated builds that can easily **_opt out_** of any default optimizations?

**Comment by jdumas** [comment]
I just described 5 real-world usages of libigl that would be broken by silently enabling march=native as default. It looks like to me you are the one being selfish by wanting to enable the option by default because it would benefit your own personal use-case, despite the fact that it is already super easy to enable march=native. You're telling me "I want things to be fast" without giving me any quantifiable benchmark to prove it, and advocate for making breaking changes that would force other maintainers, or every student using libigl on a HPC cluster, to be aware of the change and to explicitly disable the option.

**Comment by alecjacobson** [comment]
Jeremie, please try to avoid ad hominem attacks on this public forum.

I think we just have different ideas of what the "common case" is. Probably we wouldn't settle that without some kind of poll of users.

My working estimate is that we have a lot of users in two major groups: A) researchers compiling code that runs on the machine they're sitting in front of, and B) researchers using libigl precompiled via some automated build process (docker/conda/etc.). There are surely other groups: C) researchers running code on hetero HPC clusters, and D) app-developers deploying executables/libraries on different hardwares, and E) other people not falling into these groups.

If I consider A) and B) to be the common case, then -march=native by default to benefit A) and opt out to maintain good behavior on B) is not unreasonable. I'd like to hear more about the numerical issues you mentioned at the top. That alone could be a good reason not to do this.

HPC users strike me as exactly the people who would be overriding default flags anyway to squeeze out HP (high performance). So, my assumption would be that these are power users who have already set march to whatever min sse they have on the cluster. Perhaps, this is still too much of a common gotcha or these users are not really HP power users but rather more typical users using a HP-cluster as just a cluster to run a bunch of jobs. In those cases, that might be enough reason to avoid this.

libigl is for first and foremost for researchers (largely covered by A),B),C) ), so as a matter of principle I don't consider app developers D) as part of "optimizing for the common case". Maybe I'm miscounting researchers that also fall into app-deployment case. That alone would also be a good reason to not do this.

Finally, I'm not really dead set on this particular march=native thing. IIRC, back in March I had a situation that benefited a lot from it and wondered if we should flip in on by default (I forgot what the situation is now. If I remember, I can I'd post as a benchmark example). I found this thread recently when searching for the cmake gibberish that I need to add to my project to enable it and then reread your post and wondered about "portability".

I _am_ worried if we start making decisions that hurt the common use cases of researchers in favor of the gihub actions, cmake best practices, etc. (this worry echoes in https://github.com/libigl/libigl/issues/1676 regarding build time, and https://github.com/libigl/libigl/pull/1687 regarding run time).

I'm closing this issue for now. I don't think this conversation is leading to agreement on march=native and I'm happy to leave as is. If there's strong disagreement about the common use cases, we should probably start a separate thread for that or discuss offline (especially if it evokes an emotional response).

**Comment by jdumas** [comment]
Well, it's pretty clear you and I disagree on this particular issue. A survey would be a good way to come to a decision, provided we can poll a sufficient and relevant number of users. I just don't understand why you are so insistent on enabling the option by default, when we already have a perfectly acceptable solution that maintains the status quo. You are being dismissive towards the 5 real-world examples I gave you because they are "power user stuff" according to your own opinion. At least please give me some quantitative benchmark data to justify your pushing back.

The HPC use case is definitely not power-user stuff. It's already hard enough dealing with compilation environment on a HPC cluster. Tracking down compilation-related bugs due to heterogeneous hardware is something I'd like to spare people. The main concern is compiling on a node with AVX, and running the job on a node that doesn't support AVX. You get a runtime error and it's not super obvious why it fails. HPC users mostly want to run 10k jobs on multiple nodes. Individual performance doesn't matter _that_ much, because it is hard to measure on a heterogeneous environment, so you actually don't want to enable all the AVX/SSE stuff.

My experience with CMake is that `CMAKE_CXX_FLAGS` should be set by the _client_, **not** by a 3rdparty lib included in your project. Libraries shouldn't impose global compilation flags on a downstream project, it causes a lot of integration issues (e.g. different 3rdparty libraries get compiled with incompatible flags).

I understand that libigl is primarily geared towards researchers, but the project now has 2.7k stars and is used by a lot of people, including industry and hobbyist that are not necessarily researchers. At some point you have to decide whether you want to evolve libigl following best practices in open-source development, or stick with the "hackily-cobbled-together" feeling of research code. I believe github actions, CI testing, code review and PR checks, cmake best practices provide stability, reproducibility and make libigl more accessible to the masses. I don't think the goal is mutually exclusive with "research", but maybe we order our priorities differently. I tend to follow the philosophy "_make it work, make it right, make it fast_", and favor long-term maintenance over read-only code that becomes impossible to debug over time. Speed optimization comes after that.

I also care about compilation times, and I think #1676 is a situation that would _benefit_ from best practices regarding packaging and semantic versioning of libigl. I just want to tread carefully because I think having "reproducible builds" should remain a primary objective.
