### ISSUE TITLE
Remeshing in libigl

### ISSUE THREAD

**Issue by lukkio88** [libigl/libigl#1467]
Hi,

Is there any re-meshing algorithm in libigl? From the tutorial you provide the "N-rosy fields", which constructs direction field on a mesh but I can't see any use for re-meshing.

...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] I have tried the `dev` branch and the problem persists

See https://libigl.github.io/CONTRIBUTING/#bugreport for more tips.

**Comment by BruegelN** [comment]
To do so you might use the generated parametrization as input for libQEX (https://github.com/hcebke/libQEx) see also: https://github.com/libigl/libigl/issues/49 and https://github.com/libigl/libigl/issues/1000

**Comment by lukkio88** [comment]
What's the license in libQEX?

**Comment by melMass** [comment]
https://github.com/hcebke/libQEx/blob/master/LICENSE

**Comment by gaoalexander** [comment]
Hello @BruegelN @danielepanozzo,

I am as well interested in using the parametrization obtained via MIQ, as input to LibQEx, in order to extract an explicit quad mesh.

It seems this should be straightforward enough, however I am unsure of how exactly to go from one data format to the other.  The output of libigl-MIQ is as follows: 
```
// UV                 #UV by 2 list of vertices in 2D
// FUV                #FUV by 3 list of face indices in UV
```

Whereas the input format to libQEx ([code here](https://github.com/hcebke/libQEx/blob/c0a4dc69d9b22685d07ea4c8f1ea4e92dd407264/interfaces/c/qex.h#L78)) is defined as:
```
// in_uvs             #The per-halfedge UVs. Precondition: in_uvs->size() == in_triMesh->n_halfedges()
```

I am wondering whether you have some guidance as to how exactly to go from libigl's output format to libqex's input format?

Thanks very much for your help.

**Comment by alecjacobson** [comment]
This triangle mesh remesher is written using libigl https://github.com/sgsellan/botsch-kobbelt-remesher-libigl

It'd be really cool to merge it into libigl but not sure that's going to happen.
