### ISSUE TITLE
Fix unit tests which are causing FPE.

### ISSUE THREAD

**Issue by jdumas** [libigl/libigl#1478]
#### Describe your issue

See #1001 and #1477. We need to properly fix this before enabling FPE.

#### Check all that apply (change to `[x]`)
- [x] Linux

**Comment by BruegelN** [comment]
At least for `igl::signed_distance()` it should be fairly easy to fix.
The lower/upper bound is set to std::numerical_limit::min()/max() unless otherwise specified: https://github.com/libigl/libigl/blob/master/include/igl/signed_distance.cpp#L232-L233.
As lower/upper bounds get squared later on https://github.com/libigl/libigl/blob/master/include/igl/signed_distance.cpp#L124-L129 this will result in an overflow.
By only squaring if `lower/upper != std::numerical_limit::min()/max()` at least the _default_ behavior would by fixed.
