### ISSUE TITLE
png (stb) module without cmake

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1481]
The main library can be easily compiled in header only mode without using cmake. For example,

```
#include <igl/read_triangle_mesh.cpp>
int main()
{
  Eigen::MatrixXd V;
  Eigen::MatrixXi F;
  igl::read_triangle_mesh("foo.obj",V,F);
}
```
will compile as long as igl and Eigen are included. For example, with:

```
clang -I $LIBIGL -I $LIBIGL/external/eigen3 A.cpp -o A
```

STB's compilation/linking appears to be somehow tied to file preparation done by cmake(?). So attempting to compile simple program like this:

```
#include <igl/png/writePNG.h>
int main(int argc, char *argv[])
{
  Eigen::Matrix<unsigned char,Eigen::Dynamic,Eigen::Dynamic> R,G,B,A;
  igl::png::writePNG(R,G,B,A,"foo.png");
}
```

by including paths to igl, Eigen and stb via

```
clang++ -I $LIBIGL/include -I $LIBIGL/external/eigen3/ -I $LIBIGL/external/stb/ B.cpp -o B
```

fails with error

```
/usr/local/libigl/external/stb/igl_stb_image.h:4:10: fatal error: 'igl_stb_image_export.h' file not found
```

It appears this file is prepared by cmake in the `build/` directory. If I further (and awkwardly) try to include this directory via:

```
clang++ -I $LIBIGL/include -I $LIBIGL/external/eigen3/ -I $LIBIGL/stb/ -I $LIBIGL/build/stb_image B.cpp -o B
```

then I get a linker error

```
Undefined symbols for architecture x86_64:
  "igl::stbi_write_png(char const*, int, int, int, void const*, int)", referenced from:
      igl::png::writePNG(Eigen::Matrix<unsigned char, -1, -1, 0, -1, -1> const&, Eigen::Matrix<unsigned char, -1, -1, 0, -1, -1> const&, Eigen::Matrix<unsigned char, -1, -1, 0, -1, -1> const&, Eigen::Matrix<unsigned char, -1, -1, 0, -1, -1> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in bad-45116c.o
ld: symbol(s) not found for architecture x86_64
```

Is it not possible to use stb and the igl::png module in header only mode?

The current cmake puts some download/created files in `external/` and some in `build/`. Is there a good rationale for that?

(probably related to this mess https://github.com/libigl/libigl/pull/1417 )

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [x] Mac OS X
- [ ] Linux

**Comment by alecjacobson** [comment]
Ah, a "solution" is to also include the cpp file (and still include both the external/... and build/... paths 

```
#include <igl/png/writePNG.h>
#include <igl_stb_image.cpp>
int main(int argc, char *argv[])
{
  Eigen::Matrix<unsigned char,Eigen::Dynamic,Eigen::Dynamic> R,G,B,A;
  igl::png::writePNG(R,G,B,A,"foo.png");
}```

compiles and links with:

```
clang++ -I $LIBIGL/include -I $LIBIGL/external/eigen3/ -I $LIBIGL/stb/ -I $LIBIGL/build/stb_image B.cpp -o B
```

This is not obvious, documented, or convenient. Can't we just merge stb into the main library and make it header only?

**Comment by jdumas** [comment]
Why is being able to compile without CMake important? I mean it's nice to be able to do so for the main lib, but we cannot maintain a separate header-only build for all modules that depend on third-party libs, that's too much engineering work. So we have to draw the line somewhere. On a side-note, I recommend reading this blog post on why [header-only libraries are bad](https://schneide.blog/2018/04/30/c-header-only-libraries-are-bad/).

Let's take a step back and look at the situation:
1. Some third-party libraries need some functions to be implemented in a .cpp.
2. Libs like stb do that via a `#define STB_IMAGE_IMPLEMENTATION` to keep the implementation in the .h. It doesn't mean that stb is almost "header-only", just that they crammed both .cpp and .h into the same file.
3. Multiple libs each integrate their own version of stb, which cause collisions and violations of the ODR.
4. This means integration of third-party libs like stb need to be protected, e.g. by keeping the implementations in the `igl` namespace.
5. When integrating a third-party lib to libigl, I would like to keep code changes to a minimum, to facilitate future updates.

Now, while we could just copy stb into the libigl namespace and slap all functions with a `IGL_INLINE`, I am opposed to this option in general because of 5. Even though this is appealing and updates to stb are infrequents, I feel that:
1. This is not a viable long-term solution in general;
2. We'll have the same problem for all third-party libraries we want to integrate;
3. The more modifications we have to do to integrate third-party code into libigl, the less likely it'll be we'll adopt future updates, and more the likely we'll be to lock ourselves into an old version.


Here are a couple of technical solutions I can think of:
1. Include directly `stb_image.h`, and have the client `#define STB_IMAGE_IMPLEMENTATION` in their own applications.
   **Pros**: No modification to stb required. Client can use whichever version of stb they want.
   **Cons**: Each example code has to implement stb image functions. Works with non-CMake builds.
2. Provide a libigl-implementation of stb function, via `#define IGL_IMPLEMENTATION`.
   **Pros**: Less code for the client to type, no modification of stb code required. Works with non-CMake builds.
   **Cons**: If multiple libs do that, this still results in duplicated definitions.
3. Keep the current CMake-based solution.
   **Pros**: No modification of stb code required. Isolated implementation (only igl-namespaced function are exposed). stb version can still be overridden by client code.
   **Cons**: Doesn't work with non-CMake builds.
4. Wrap `stb_image.h` around a `namespace igl {}`.
   **Pros**: Works with non-CMake build, hopefully little modifications to stb code is required -> easier to update.
   **Cons**: Might be tricky since stb is written in C (`extern "C"`). libigl is no longer header-only (needs to implement `STB_IMAGE_IMPLEMENTATION`). Version of stb is bundled with libigl (user cannot use their own version).
5. Mark every stb function with `IGL_INLINE` and make it truly header-only?
   **Pros**: Would keep libigl header-only, works with non-CMake builds.
   **Cons**: Might be a lot of work, we'll never update stb anymore (too much work), pollutes headers with stb internal code. Not guaranteed to work.


Let me know if you agree with this list of pros and cons and if you see any other technical solution. I'm trying to think not only about stb, but about all the third-party libs we include in libigl and that we want to be able to update easily.

**Comment by alecjacobson** [comment]
The first question is easy. Not everyone or every project uses cmake.

The rest of your response (and that think-piece article) seems to instead post the question "Why is being able to compile header-only important?" Not sure we can settle that here.

Can we somehow set up the cmake into stages (1: external "submodule" fetching and 2: build procress) ? Where there's a stage for downloading external dependencies and preparing whatever these build/stb_image/ files are? And can we put those files into external instead?

Then if I'm not using cmake to generate my build routine, I only have to use it to generate the external dependencies and they're organized in a reasonable way.

**Comment by jdumas** [comment]
I understand why it's interesting to be able to compile without CMake. I'm just saying that at some point, you don't want to have to maintain two separate building instructions (= 1 readme + 1 cmake), since inevitably 1 of them will get out of date (and only 1 of them is tested with CI). So the instructions on how to build third-party dependencies into libigl = you need to read what CMake is doing. I'm definitely open to make this process easier though, and reduce the amount of "cmake magic" that is happening, but it always comes at a cost (less work for cmake, more work for us).

Outside of headers and source files, there's always compiler options and defines which are specific to certain libs/platforms. E.g. embree probably needs to be compiled with very specific flags. One option is to have CMake "export" the rules needed to compile third-party libs and whatnot, and have the client build system consumes it. But without knowing what build system the other project is using, it's hard to say what needs to be done exactly to support that. And if your build system == raw command line, I'd say that's really suicidal after a certain point :D
