### ISSUE TITLE
igl::slice obsolete as of Eigen 3.4 ? 

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1485]
Looks like Eigen supports arbitrary index list slicing as of 3.4:

https://eigen.tuxfamily.org/dox-devel/group__TutorialSlicingIndexing.html

Does this make `igl::slice` obsolete? If we're sure that Eigen now covers all use cases captured by `igl::slice` (e.g., repeated indices), perhaps we should phase it out.

Similarly `igl::slice_into`

**Comment by ikoruk** [comment]
Eigen 3.4 is now out officially

**Comment by alecjacobson** [comment]
Just for dense matrices, right? Do we know if it supports repeated, unsorted indices, empty arrays, etc. etc.?

**Comment by ikoruk** [comment]
Yes it seems to be only for dense matrices. Details here: https://eigen.tuxfamily.org/dox/group__TutorialSlicingIndexing.html

I haven't tried it yet but sequences and unsorted indices seem fine. Empty arrays I would assume. I don't think slice is obsolete, but it might be worth it anyway to upgrade the Eigen dependency since there are a lot of other improvements: https://eigen.tuxfamily.org/index.php?title=3.4
