### ISSUE TITLE
Switch to static build

### ISSUE THREAD

**Issue by Roipo** [libigl/libigl#1516]
I tried switching to build as static lib for an existing code and got many compilation errors due to missing include files that didn't happen before. The problem is that the code relied too much on files that were not explicitly included in it, but in cpp files in libigl, which are no longer included when using as a lib. I looked a bit and it the way includes are split between the h and the cpp seems a bit random. Is there a pattern? I can simply include all the right files in the code, but is there a recommended way to avoid this altogether?

- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
I can't say that headers are split in the best way possible between .h and .cpp in libigl, but if you have missing includes when switching to the static lib version, then it means you ... need to add them. Using header-only templated code means that oftentimes, you expose the "private" code needed to implement any given function. When switching to static compilation, this "private" code (including other headers needed by function X) is no longer exposed to the client, so the client has to include all the headers they need, instead of having them implicitly pulled in by another header.

That being said if the shortcoming is with a missing public header in a .h file inside libigl (e.g. missing `<Eigen/Core>` or missing `<vector>`), then you should definitely submit a PR so we can fix this on the libigl side.

Otherwise for your own code you might have some luck with helper tools such as https://include-what-you-use.org/

**Comment by alecjacobson** [comment]
If the errors are coming from your code, then you'll need to include the
appropriate headers. Don't rely on libigl's headers to include them for you
(also because they might change if you update and then you just get the
errors later).

Putting whether we abide by it aside, the intended policy for includes is
that our .h files include only exactly what they need to define types in
the function definitions and all other includes are in the .cpp files.

>
