### ISSUE TITLE
Crash in tutorial example 718_IterativeClosestPoint

### ISSUE THREAD

**Issue by syerokhin** [libigl/libigl#1531]
#### Describe the bug

Compiled and run in VS2017  win32, DEBUG.
Steps to reproduce;
1) Run example
2) Press R to set initial transform
3) Do aligning iterations (press Space) repeatedly even after alignment becomes quite good.

Crash happens on line
X.row(x) += B(x,b)*V.row(F(FI(x),b));
in random_points_on_mesh.cpp.

At that point FI(x) gives exactly the same index as number of rows in F matrix (10540).
Thus code tries to access next row after last in F matrix.

#### Check all that apply (change to `[x]`)
- [ x] Windows
- [ ] macOS
- [ ] Linux

**Comment by syerokhin** [comment]
Just to make more clear.  Crash here is failed assert.
Please use Debug version to reproduce.

**Comment by Fedr** [comment]
The problem here is that random_point_on_mesh can return last-face-index+1. This happens even in the tutorial example.

The patch as follows fixes the crash:

`--- a/include/igl/random_points_on_mesh.cpp`
`+++ b/include/igl/random_points_on_mesh.cpp`
`@@ -42,6 +42,10 @@ IGL_INLINE void igl::random_points_on_mesh(`
`   assert(R.minCoeff() >= 0);`
`   assert(R.maxCoeff() <= 1);`
`   histc(R,C,FI);`
`+  auto FImax = F.rows() - 1;`
`+  for ( int i = 0; i < FI.rows(); ++i )`
`+      if ( FI(i) > FImax )`
`+        FI(i) = FImax;`
`   const VectorXs S = (VectorXs::Random(n,1).array() + 1.)/2.;`
`   const VectorXs T = (VectorXs::Random(n,1).array() + 1.)/2.;`
 `  B.resize(n,3);`

**Comment by teseoch** [comment]
hmhmh I think this
```
C(C.size()-1) = F.rows() - 1
``` 
should be a better fix but I am just guessing

**Comment by alecjacobson** [comment]
I swear this has been noticed before and fixed... Maybe just deja vu

>

**Comment by jdumas** [comment]
There was this: https://github.com/libigl/libigl/pull/1345

**Comment by teseoch** [comment]
is my suggestion correct?
I don't want to create a PR since the code is not tested and I am afraid of breaking something.
