### ISSUE TITLE
[URGENT] Getting high genus meshes out of boolean operation (intersection)

### ISSUE THREAD

**Issue by randomleyyyyyyya** [libigl/libigl#1543]
Hello,

I am using libigl’s boolean operation to extract the intersection of several meshes, it works very well in general, but there’s one thing — I am occasionally getting high genus meshes as outputs while the genera of the inputs are all very low (and it should not be the case in theory). I am wondering why I am getting this issue and how can I fix it?

Thank you in advance!

**Comment by alecjacobson** [comment]
Could you share your inputs? There are many reasons why you might get this
and it would not be unexpected. There are some other cases I can think of
where it could be correct but unexpected.
-Alec

>

**Comment by randomleyyyyyyya** [comment]
Hello Alec,

Thank you for your reply!

[Here](https://drive.google.com/file/d/1-v6_Ut6nYFN5_MHTEL8xoGMxR0zo4tfo/view?usp=sharing) is a link to a zip file of the input to the boolean operation and the output for the bunny example.

The inputs have genus 0 and genus 2 respectively, and the output has an undefined genus (due to non manifoldness), but if we clean the output it will have a genus of 10.

Sincerely,
Lei

**Comment by alecjacobson** [comment]
Thanks, these two meshes have many parts that are almost the same but not
quite, so I'm not surprised that the result will have lots of small
components or topological handles.

BTW, these meshes look like they're created from a voxel grid or distance
field. You might consider just doing the boolean operation on the voxel
representation rather than as meshes.

**Comment by randomleyyyyyyya** [comment]
Sounds like a good idea. Thank you!
