### ISSUE TITLE
specification of region handles for biharmonic-coordinates deformation

### ISSUE THREAD

**Issue by blamber** [libigl/libigl#1562]
Hello,

Would it be possible to provide some details or a concrete example on how to specify and use region handles with the Biharmonic Components  deformation?

For example, in the 407_BiharmonicCoordinates tutorial, how would I define a region handle for the tip of one of the octopus tentacles?  Once defined, how does one then specify how that handle is to move?  

thanks,
Brian

...

#### Check all that apply (change to `[x]`)
- [ ] Windows
- [ ] macOS
- [ xx] Linux

**Comment by alecjacobson** [comment]
Checkout the example in the documentation:

https://libigl.github.io/dox/namespaceigl.html#aa0ba6f8afae42bb09f687fe9a518ee94

For computing the weights just give dim+1 or more vertex indices in the list (i.e., for 3D you need at least 4 vertices in a region).

Then at deformation time, in the `H` matrix instead of specifying the change in vertex position, specify the affine transformation that moves the whole region. 

Please reopen if this is not enough.
