### ISSUE TITLE
Let's move predicates to the main library

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#1564]
Shewchuck's predicates haven't changed in 25 years. the license is compatible and others have figured out the c/c++ encapsulation namespace issues.

**Comment by jdumas** [comment]
The main file [predicates.c](https://github.com/libigl/libigl-predicates/blob/master/predicates.c) has a lot of #define all over the place. Are you planning to compile this as a .cpp file inside the igl namespace? Otherwise, we have the same issue as the png/stb library, there are some strong compatibility issues with keeping igl::core as a header-only library...

**Comment by alecjacobson** [comment]
I think someone mentioned in an earlier issue / PR that geogram or others
had already namespacified these

**Comment by jdumas** [comment]
Geogram has its own implementation of exact predicates, different from Shewchuck's (in fact it also has a tool to generate custom predicates should you need it). The predicates in geogram come in the form of a pair of .cpp/.h. So while they are in their own namespace `GEO`, you can't just drop it into a header-only library and call it a day. You either need to inline everything that's in the .cpp, or you use the same trick as stb libs with the `#define STB_IMAGE_WRITE_IMPLEMENTATION` trick.

**Comment by alecjacobson** [comment]
We don't need to move it all into libigl's main library at once, and it doesn't (in fact shouldn't) be done as one giant file. Right now there are only four functions in `igl/predicates.cpp`. At least 2 are buggy (`ear_clipping.cpp` and `point_inside_convex_polygon.cpp`), one has had issues in the past (`segment_segment_intersect.cpp`), and the last one is not libigl style but rather some kind of bandaid to deal with the `exactinit` weirdness in the original predicates C code (`predicates.cpp`).

We can leave this `igl/predicates` folder alone for now in case someone is using it (but from these bugs, I would be scared if they are!).

Meanwhile, swallow the predicates one by one into the main libigl library. There are other functions there already (e.g., `delaunay_triangulation`) that would benefit from just a few of them.

**Comment by jdumas** [comment]
The exactinit weirdness is still not solved, for example you cannot compile libigl with both triangle AND predicates enabled for now, since they will have conflicting symbols (they both use the same exactinit code). I remember we had a [contrib](https://github.com/libigl/libigl-predicates/issues/1) that would reproduce the exactinit at compile time, so we could avoid this init weirdness, but afaik this hasn't been tested on `float`.

In any case, my question is more about what/how you are planning to bring the predicates into the main lib. There are strong technical limitations to keeping igl::core a header-only library, which makes this task challenging from an engineering perspective. Even the predicates from Geogram would be difficult to split into smaller files, since they need a whole machinery for stack-allocated arbitrary precision numbers.

**Comment by alecjacobson** [comment]
Wouldn't static variables be enough?

**Comment by jdumas** [comment]
If you include them both in the same compilation unit, their definitions would still conflict (if they are in the same namespace). And that would require extensive modifications to the source code (which may not be an issue since as you said, Shwechuk's predicates haven't changed in 25y). The #define pollution would be more difficult to get rid of though.

**Comment by alecjacobson** [comment]
are you talking about thread safety ? Or duplicate symbols? I was thinking
static local variables in the functions. Does that really have the same
issue?

The define pollution is awful but on a case-by-case basis looks like it
wouldn't be that bad to clean up as we go (perhaps famous last words).

In any case, the goal would be *useable* predicates within libigl, not
necessarily super-stack-memory-allocation-optimized predicates that are
hard to use so only 4 buggy functions use them.

**Comment by jdumas** [comment]
But since predicates are often called in performance critical paths, anything that is not efficient memory-wise will be slow and unusable. I'm not sure how Shewchuk's predicates work, but they don't seem to be doing `alloca` like geogram's.

In any case, I'm just putting on my engineer's hat and pointing out potential pitfalls of trying to integrate ubiquitous .c code into a header-only library:
- Function symbol collision
- #define header pollution
- (no) namespace encapsulation
- Need to inline everything
- (compilation time from having everything inline)
- static global calculation/storage

Thread-safety is probably ok, since we can use Meyer's singleton to safely initialize the global variables. But where to store those global variables is indeed tricky. If you define a static variable into every compilation unit, there's no telling what `exactinit()` will initialize exactly. You cannot have globally static variables a header-only library, so you'd need to define your own `struct` singleton pattern to hold the variables `splitter`, `epsilon`, etc. Not impossible but this will require substantial changes to the `predicates.c` source code (replace every instances of `splitter` with `igl::Predicates::instance().splitter` for example).

So none of this are insurmountable, and we can solve anything with a bit of elbow grease. I just want to make sure that whoever is going to do this knows what they're getting into (and is aware of the different problems to solve).

My personal opinion is that the juice isn't worth the squeeze, and I'd be happy with a new module `igl::extra` that is *not* header-only, but where we could cram and easily encapsulate all the stuff we want without the headache of maintaining a header-only library (hello png reader).

**Comment by alecjacobson** [comment]
your comments make sense if the goal is "move all this c code to c++ header
only" without having to worry about what the code is. Admittedly that's how
my original post suggested it.

I think the goal should be, write orient2D and incircle predicates in the
main library. Then we can happily remove the current predicates/ folder.

>

**Comment by jdumas** [comment]
Ah yes, that would be a good solution indeed. Unfortunately, there are probably only 3 ppl on the planet that really understand Shewchuk's predicates or how to write their own, so even that would be a challenging task! (But a cool project for sure)
