### ISSUE TITLE
How to move one mesh so it doesn't collide with another?

### ISSUE THREAD

**Issue by Rocketmagnet** [libigl/libigl#1574]
#### Describe your question

I have two meshes, which may or may not be colliding. If they are colliding, I would like to slowly move them apart until they are no longer colliding.

One way to do this, would be to use a function which not only detects the collision, but also give a measure of the amount of overlap between the two meshes. Then I can perform a gradient descent.

I suppose that the CSG functions might help here. I could take the intersection of the two meshes, and calculate the volume of the resulting mesh, but I can't see a volume function mentioned in the tutorials.

Is there some way I can achieve what I want using libigl?

Many thanks
Hugo
...

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by jiangzhongshi** [comment]
In order to get the enclosing volume of a mesh, you can follow something like https://github.com/libigl/libigl/issues/694#issuecomment-365485510

**Comment by alecjacobson** [comment]
In generally this is a tough problem and there have been some papers about it:

"Untangling cloth"
"Resolving surface collisions through intersection contour minimization"
"Interference Aware Geometric Modeling" (kind of what I implemented here https://www.alecjacobson.com/weblog/?p=4341)
"Guaranteed Globally Injective 3D Deformation Processing"

We don't have any of these implemented in libigl. If I was going to try to do this myself, I might use TinyAD to do a descent optimization on some measure of penetration (overlap) volume.

I think I even implemented this once differentiating through the Boolean intersection operation. Since the derivative of volume is just normals I think this wasn't sooo bad and did indeed move the meshes.

No guarantee they untangle though. I think finding path to an untangled state is in general hard (in robotics they use search heuristics for the similar problem of finding feasible motion).

Good luck! Feel free to continue this as a [discussion](https://github.com/libigl/libigl/discussions) rather than an issue.
