### ISSUE TITLE
Biharmonic name .

### ISSUE THREAD

**Issue by csverma610** [libigl/libigl#164]
Hello,

There is an argument "k" in the biharmonic coordinates. If k = 2,
biharmonic makes sense, but for K > 2, having the same name
may not be elegant. Perhaps just harmonic will be better. Any 
suggestions ?

**Comment by alecjacobson** [comment]
Unfortunately this function doesn't make sense for k<2 so `harmonic` wouldn't be appropriate. Perhaps `polyharmonic_coordinates` would make sense, but since the relevant paper only describes `k=2` then the `k` is really just an "extra" parameter. If k>2 becomes more useful/common, then I'd consider renaming, but for now it'll stay.
