### ISSUE TITLE
Mean Curvature Flow

### ISSUE THREAD

**Issue by csverma610** [libigl/libigl#168]
In the tutorial example 205, the coordinates are divided by  sqrt(area) ( in the last lines). Is it necessary ?

If it necessary then I think, it should have been at the first iteration also. It seems that the scaling is
done from the second step, if I am not wrong.

Thanks.
csv

**Comment by alecjacobson** [comment]
This is subtle. There's two things happening here:

(1) At every step viewer is zooming in/out so that the model fills the unit region (so it appears not to scale):

```cpp
 viewer.core.align_camera_center(U,F);
```

(2) The flowing mesh (U,F) is recentered around the origin and scaled to have unit surface area at each step:

```cpp
U.rowwise() -= centroid;
// Normalize to unit surface area (important for numerics)
U.array() /= sqrt(area);
```

As written in the comments, this very important for numerics: floating point numbers are more precise near the origin (recenter) and we need a healthy amount of resolution between neighboring vertices to do computation (rescaling). See http://www.alecjacobson.com/weblog/?p=3981
(1) is really only for visualization. (2) is really only for numerics. You could put the recentering and rescaling  before the flow step rather than after it, but you'd only be affecting the numerics of the first step: the important thing is that you actually rescale and recenter U at every iteration and _not just_ the camera (i.e. 1)
