### ISSUE TITLE
Lots of warnings

### ISSUE THREAD

**Issue by brendanlb** [libigl/libigl#1681]
Hi,

When using libigl in my projects as a header-only library, I get a lot of warnings. Is there a way to disable warnings for files from a specified directory ? It's quite difficult and painful to identify warnings coming from my own code because of the amount of warnings coming from the igl included files (-Wunknown-pragmas, -Wunused-result, etc.) and I don't want to modify an external library code.

Other than that, the library is great, thanks for all your work !

- [ ] Windows
- [ ] macOS
- [ x ] Linux (Ubuntu 20.04)

**Comment by jdumas** [comment]
Hi,

I you want to fix some of those warnings, we'd be happy to take new PRs. Otherwise, I can suggest to use #pragma push/pop to [disable](https://github.com/polyfem/polyfem/blob/master/src/utils/DisableWarnings.hpp) and [enable](https://github.com/polyfem/polyfem/blob/master/src/utils/EnableWarnings.hpp) specific warnings when you are including libigl headers. Finally, on Linux you can include libigl headers as system headers (with `-isystem` instead `-I`), which might require a slight modification of our CMake file (Visual studio has a similar system to ignore warnings coming from certain files).

**Comment by brendanlb** [comment]
Hi,

Thank you for your answer @jdumas. Following your advice, I added the libigl directory as `SYSTEM` in my CMakeLists.txt. It disabled all warnings, which was exactly what I was looking for ! For those who might be interested, here are the lines I used in my CMakeLists.txt (using libigl as a header-only library with files located in my project include directory) :

```
# libigl
set(ligigl_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/include/libigl/include)

# Include directories
target_include_directories(project_name
                           SYSTEM PUBLIC
                           ${ligigl_INCLUDE_DIR})   # to avoid warnings from libigl
```
