### ISSUE TITLE
Limit Number of Threads Used

### ISSUE THREAD

**Issue by cheng-chi** [libigl/libigl#1683]
#### Describe your feature request
We are currently using libigl on a shared dual-socket research server. Since other people are using the server at the same time, I'm looking for a way to not use all cores available. However, it seems like many algorithms depend on igl/parallel_for.h, which will automatically use all threads available. Is there an easy way to implement something similar to OpenMP's OMP_NUM_THREADS environment variable? I will be glad to help if needed.

#### Check all that apply (change to `[x]`)
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by jdumas** [comment]
Well you can always define IGL_PARALLEL_FOR_FORCE_SERIAL to turn the parallel for into a serial loop:
https://github.com/libigl/libigl/blob/fbfb2d56ad7bab2844433b27f32025314edc60f8/include/igl/parallel_for.h#L130

We'd be happy to review any PR to customize the number of threads. Ideally we should provide ways to let the client override the parallel for implementation with their own (e.g. use OpenMP or TBB rather than the default implementation).

**Comment by cchi-nuro** [comment]
Thanks @jdumas, unfortunately we are mainly using the python binding of libigl, and IGL_PARALLEL_FOR_FORCE_SERIAL is a compile time option. I will try to implement a simple version with get_env (which does not make system call when being used, and hopefully will not cause performance problems.)

**Comment by jdumas** [comment]
Fixed by #1684
