### ISSUE TITLE
cannot open source file "imgui.h"

### ISSUE THREAD

**Issue by zhiyingf** [libigl/libigl#1713]
#### Describe your question
in ImGuizmo.cpp:
![image](https://user-images.githubusercontent.com/38620101/106475393-da214f00-64e0-11eb-92cf-b9e080834a24.png)
but I add igl::igl::opengl_glfw_imgui to the list.
#### Check all that apply (change to `[x]`)
- [x ] Windows
- [ ] macOS
- [ ] Linux

**Comment by jdumas** [comment]
Same comments as in #1712, but with `igl::opengl_glfw_imgui` ....

**Comment by zhiyingf** [comment]
I did use `igl::opengl_glfw_imgui`... ...

**Comment by jdumas** [comment]
Try to delete the content of your `external/` folder and let CMake re-download the various dependencies. Try to compile libigl on its own with the tutorial containing imgui.

**Comment by zhiyingf** [comment]
Maybe because of the internet, CMake can't download. So I had to modify the file( `libigl/cmake/LibiglDownloadExternal.cmake` ) and download the `external/*` folder manually. Finally ,can't compile libigl duo to above error。

**Comment by jdumas** [comment]
Please don't download stuff manually. If something is not working with LibiglDownloadExternal.cmake please describe the issue so we can try to help.

**Comment by zhiyingf** [comment]
Ok, Thanks.CMake problem:
![image](https://user-images.githubusercontent.com/38620101/106535059-55f6b800-6530-11eb-8329-e2b383892585.png)
and
![image](https://user-images.githubusercontent.com/38620101/106535095-660e9780-6530-11eb-8f78-a0c01c91f5b1.png)
Can't download like this：embree,glfw,imgui,cgal... ...

**Comment by jdumas** [comment]
Does it do that when you start from a _fresh clone_ of libigl and use an _empty directory_ for your CMake build?

**Comment by zhiyingf** [comment]
I not used an empty directory for CMake build because of can't delete the /build folder at that time.

**Comment by jdumas** [comment]
Try using a different folder.

**Comment by Philius** [comment]
I'm getting this error building libigl on Debian 64 bit.
I added VERBOSE=1 to see the include directives - there are none!
```
[ 68%] Building CXX object CMakeFiles/imguizmo.dir/external/imguizmo/ImGuizmo.cpp.o
/usr/bin/c++   -fPIC -O3 -DNDEBUG -o CMakeFiles/imguizmo.dir/external/imguizmo/ImGuizmo.cpp.o -c /v3c/3d/doodles/libigl-upstream/external/imguizmo/ImGuizmo.cpp
/v3c/3d/doodles/libigl-upstream/external/imguizmo/ImGuizmo.cpp:23:10: fatal error: imgui.h: No such file or directory
   23 | #include "imgui.h"
      |          ^~~~~~~~~
```

**Comment by jdumas** [comment]
Whenever you are changing a CMake option, remember to delete your CMakeCache.txt for the option to take effect. Also, we do not support building anything more that the main lib for embree, so I would leave the tutorials disabled (the libigl tutorials using embree should still be built).

**Comment by Philius** [comment]
I just deleted the build and external directories, mkdir build, cd build, cmake-gui, configure, check EMBREE_TUTORIALS, configure, generate, make, same problem.
You have to run configure to see and modify the options in cmake-gui, I'm guessing that's ok.
If an option isn't supported, shouldn't it be hidden? I'm no cmake/git submodule expert, maybe it's not possible.
Anyway, at least for me, cmake seems to be the cause of no include directives leading to the compiler not being able to find imgui.h.
It's too easy to browse the cmake options and forget you checked a check-box (because you figure what's the harm) and wonder what went wrong.

**Comment by jdumas** [comment]
The EMBREE_TUTORIALS option is not supported in libigl, please do not enable it. It shows up in cmake-gui because we are compiling embree from source, and embree's CMake defines it. But, l since embree's cmake is poorly written, changing any of the default options set by libigl can cause trouble, which is exactly what's happening.

I suppose we _could_ hide it, but it's not worth it, as we cannot test all possible combination of options and hide the ones that are not safe to use. As a general rule, any option that doesn't start with `LIBIGL_xxx` is not our responsibility, and comes from third-party dependencies themselves. If it messes up your project, it's probably not libigl's fault.

**Comment by Philius** [comment]
> Whenever you are changing a CMake option, remember to delete your CMakeCache.txt for the option to take effect. Also, we do not support building anything more that the main lib for embree, so I would leave the tutorials disabled (the libigl tutorials using embree should still be built).

Which libigl tutorials use embree? Do you mean [https://github.com/libigl/libigl-examples/tree/master/embree](https://github.com/libigl/libigl-examples/tree/master/embree)?

**Comment by Philius** [comment]
Never mind, I can search for embree in the tutorials.
