### ISSUE TITLE
cmake using -isystem for cgal includes and finding homebrew install instead?

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#2029]
On my local mac, I noticed that the cgal tests were failing. After some long debugging I traced it down to the compilation paramters:

```
-isystem /Users/ajx/Repos/libigl/build-header-only/_deps/cgal-src/include
```

if I replaced this with 

```
-I /Users/ajx/Repos/libigl/build-header-only/_deps/cgal-src/include
```

Everything works. My _guess_ is that [because isystem includes come later](https://stackoverflow.com/a/2579600/148668), the compiler was finding the cgal headers in `/usr/local/include/` where homebrew had put them. This compiled fine, but resulted in memory issues and crashes at runtime. I imagine due to a CGAL mismatch.

The easy fix for me was to uninstall cgal from homebrew. However, I wonder if this is something we could be doing better to prevent via our cmake scripts?

I'm not entirely sure why we use `isystem` for cgal or if that's something we're choosing or cgal is choosing. I believe `isystem` vs `I` also affects whether compilation warnings are displayed, but if that's the only reason then I'd rather see warnings than this hard to debug crash.

**Comment by jdumas** [comment]
The problem is not `isystem` vs `I`. The problem is we have _something_ that is adding `/usr/local/include/` to your include paths. You just got lucky that with `-I` the downloaded CGAL folder comes first, but this is absolutely not a reliable way to handle this type of mismatch. The only real "solutions" are:
- Remove whatever is using a system installed library that caused the addition of `-I /usr/local/include/` (and download it instead).
- Uninstall CGAL from your system to prevent further conflicts (which imho is a good idea). If you want to compile a package that requires a system-wide install of CGAL, I'd suggest using `conda` environment to manage that instead of homebrew.

**Comment by alecjacobson** [comment]
For myself, I'm happy to uninstall cgal, but to resolve this issue we should see what we can do about removing the `/usr/local/include/` to prevent this from happening to others. 

What's the best way to go about finding this pesky `/usr/local/include/`?

**Comment by alecjacobson** [comment]
In my CMakeCache.txt I see two suspicious lines:

```
GMPXX_INCLUDE_DIR:PATH=/usr/local/include
GMPXX_LIBRARIES:FILEPATH=/usr/local/lib/libgmpxx.dylib
```

I believe these should be finding gmpxx in our local build. I'll investigate these.

**Comment by jdumas** [comment]
I'd try a divide-and-conquer approach where I delete the CMakeCache.txt, enable only half of the modules, reconfigure, then find out whether the include flag is still there, etc. the GMPXX_INCLUDE_DIR is suspicious indeed. We might have to hijack CGAL's FindGMPXX the [same way](https://github.com/libigl/libigl/blob/91f6c503f62d16f4d27709ea5be0d9ab43611942/cmake/recipes/external/cgal.cmake#L32) we hijacked the other find modules.

**Comment by alecjacobson** [comment]
I think I've fixed it. I'll submit a PR shortly.
