### ISSUE TITLE
Failed building in VS2019

### ISSUE THREAD

**Issue by Hassan-Bahrami** [libigl/libigl#2037]
#### Describe your issue
After cloning igl repository, I tried to build it by cmake in build direcotry. When I try following commands in Git Bash:
```
mkdir build
cd build
cmake ..
make
```
I receive this error:
```
"make: *** No targets specified and no makefile found.  Stop."
```
When I try to build the "libigl.sln" by Visual Studio 2019 to add libigl dependencies, I get 38 successded, 72 failed and 8 skiped.
The error list of VS2019 is attached (it was too long to put in commands)

#### Checklist

- [X] I have read the [bug report](https://libigl.github.io/bug-report/) page
- [X] CMake issue: I have tried with a fresh clone/empty build directory

#### Platform

- [X] Windows
- [ ] macOS
- [ ] Linux
[VS2019_error_list_of_libigl.txt](https://github.com/libigl/libigl/files/8694699/VS2019_error_list_of_libigl.txt)

**Comment by zener90818** [comment]
I meet the same error, Did you solve it?

**Comment by Hassan-math** [comment]
I used mingw compiler instead of MVS19 and it worked for me. It seems that libigl is not compatible with visual studio compiler.

**Comment by alecjacobson** [comment]
libigl is definitely compatible with visual studio.  Our github actions test each pull request to compile successful on windows with VS.

I don't personally use windows often but I'll occasionally use it to test the build. When I do, I open the cmake project directly in visual studio rather than running any command line commands.
