### ISSUE TITLE
Is it a good way to include CGAL and Embree just for picking?

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#213]
It seems embree depend on CGAL and CGAL depend on Boost. These dependency make the CMake build on VS201x hard to do . I like to generate MTd based VC Porjects and failed after a week struggle.
I hope Libigl does not depend on CGAL and embree.

**Comment by alecjacobson** [comment]
CGAL does depend on embree, but embree does **_not_** depend on CGAL.  The main libigl functions do **_not_** depend on cgal or embree. Only the functions in `igl/embree` or `igl/copyleft/cgal`/`igl/copyleft/boolean`

Meanwhile, for picking you can just use (the new) `igl/unproject_onto_mesh`. In most cases the embree version is super-overkill just for picking on a mesh.

Since you seem to be having a lot of trouble, I would recommend thoroughly reading the [README.md](https://github.com/libigl/libigl/#readme) and trying all of the examples in the [tutorial](libigl.github.io/libigl/tutorial/tutorial.html).

**Comment by wguo68** [comment]
Thanks
