### ISSUE TITLE
Problem with key_down callbacks in plugins

### ISSUE THREAD

**Issue by olkido** [libigl/libigl#24]
Whenever a key is pressed in Anttweakbar it also triggers the key_down in the plugin. This seems to be a bug in Anttweakbar.

**Comment by alecjacobson** [comment]
Note: This problem was _not_ solved during the major update to libigl version1.2.

**Comment by alecjacobson** [comment]
Looks like this very same issue is showing up in nanogui, too...

**Comment by alecjacobson** [comment]
This issue has been resolved, see tutorial entry for [biharmonic coordinates](https://github.com/libigl/libigl/blob/master/tutorial/407_BiharmonicCoordinates/main.cpp) for proper use of `key_pressed` (rather than probably-soon-to-be-deprecated `key_down`). It remains an issue to update all other tutorial entries and to forward this issue to nanogui
