### ISSUE TITLE
fatal error C1017: invalid integer constant expression

### ISSUE THREAD

**Issue by wguo68** [libigl/libigl#308]
When I download to build tutorials ,there are many errors such as "fatal error C1017: invalid integer constant expression". I am using VS2013. The first error in lines of cat.cpp:
"
# if false

  // This **must** be DynamicSparseMatrix, otherwise this implementation is
  // insanely slow
"

**Comment by danielepanozzo** [comment]
We only support VS2015. Could you check if the same error happens with VS2015?

**Comment by wguo68** [comment]
It works for VS2015.
I want to use CUDA,but vs2015 is not supported by CUDA.    So I have to use VS2013. I am not familiar with programming on Linux because there is no IDE development tool as VS.

**Comment by danielepanozzo** [comment]
Unfortunately we do not support VS2013. Its support for C++11 it is not great, and we do not have the resources to get everything to run on VS 2013.

If you manage to get it to work on VS2013, please send a pull request so that others can benefit from it.

Regarding the other errors with VS2015: do they happen when you compile the tutorials with no changes?
