### ISSUE TITLE
Parameterization issue follow up

### ISSUE THREAD

**Issue by RogersDoug** [libigl/libigl#37]
I subdivided the cow model and increased the gradient size to 500.  However, the right horn of the model produces slivers in texture space.  You can see this in the viewer, there is no checkerboard pattern as there is on the rest of the model. 

Subdivided model:
https://dl.dropboxusercontent.com/u/85781814/cow_dense.obj

Image of horns
https://dl.dropboxusercontent.com/u/85781814/cow_dense.jpg

I don't see anything obviously wrong with the generated constraints.

**Comment by danielepanozzo** [comment]
Is the screenshot taken after pressing 7 or 8 in the viewer? If you do not need to do quadrangulation there is no reason to do the integer rounding to hide the seams. I think that 8 will probably give you a better result. The MIQ parametrization method relies on the fact that the cross-field is smooth: curvature directions are undefined on flat or spherical parts and they are thus extremely noisy in these regions introducing unbounded distortion in the Poisson parametrization. The right thing to do is compute the curvature directions, and constraint them only in a  few face (~1% of the model) where the anisotropy of the curvature is high. The nrosy method then smooth this over the rest of the surface. I do not have code in libigl for this because it requires too many parameters to tweak and I do not want to make the example too complicated. It is also problem specific: for example for cad models you definitely do not want to use curvature, but simply find the sharp edges and force the alignment to the features only there.

**Comment by RogersDoug** [comment]
That was 7.  Here is 8, which show seams separation.  
https://dl.dropboxusercontent.com/u/85781814/cow_dense8.jpg

I want to hide the seams to make the texture mapping seamless, aka invisible seams.  These are for normal maps, which really highlight seam discontinuities.

>The right thing to do is compute the curvature directions, and constraint them only in a few face (~1% of the model) where the anisotropy of the curvature is high. 

I will work on this today.  Thanks.

**Comment by RogersDoug** [comment]
That did the trick.  Here is the updated image with constraints on regions of high curvature.

https://dl.dropboxusercontent.com/u/85781814/cow_curvature_constraint.jpg

This can be closed.

Thanks.

**Comment by danielepanozzo** [comment]
Great, glad that it worked! Just a comment: with 8 you see the seams because the grid does not close up to integer values, but the gradient of the parametrization is still identical over the seams. I don't know for which application you want to use it, but if you only care about having consistent gradients you can get a much lower distortion using 8 instead of 7.

**Comment by RogersDoug** [comment]
I am trying to get invisible seams for normal maps. So I need to have the texels align across chart boundaries.  Like this:

https://dl.dropboxusercontent.com/u/85781814/seams.jpg 

So T0 and T1 are adjacent on the mesh, but not in texture space.  The orange texel overlaps T0, so I need the value from T1.  I create the normals for T0, then rotate T1 to align with T0 to get T1'.  The normals for T1' are then rendered to get complete coverage for T0.  The sampling orientation for the shared edge needs to be able to achieve square, aligned texels to avoid lighting artifacts. 

Thanks for you help.  I really appreciate your support.

**Comment by RogersDoug** [comment]
I need the triangles to align, so the output from '8' does not work.  It was worth a try.

Thanks again.
