### ISSUE TITLE
Multiple viewers? Each on their own thread?

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl#409]
Has anyone experimented with launching multiple `igl::viewer::Viewer`s ? It seems like there are some global variables insides `igl/viewer/Viewer.cpp` that would need to be cleaned up and perhaps sprinkle in a few `glfwMakeContextCurrent` calls, but I'm having trouble getting glfw to play nicely when there are multiple windows.

Perhaps a preliminary question is: how easy it is to launch multiple glfw windows?

Eventually I'd like to have 3 viewers running, each on their own thread (doing some computation and displaying results in an animation). It's not enough to have three meshes in one view because the animations will have significantly different frame rates, and I don't want to wait for the slowest one.

**Comment by alecjacobson** [comment]
_I leave this thread open for now because I'm still interested in this problem in general. For my specific problem at hand I developed a [workaround](http://www.alecjacobson.com/weblog/?p=4679 ) using a single viewer._

**Comment by jhwang7628** [comment]
Has there been any development on this? I am interested in having a separate rendering viewer window + gui for extra control, ideally running on different threads. I'm currently using multiple cores and split the viewports but its not very ideal.

**Comment by jdumas** [comment]
I have a working PR in #1038 that implement support for multiple windows, without using different threads. The branch is not up to date with the latest `dev` yet, but should be usable. There are a couple of issues on macOS that I haven't solved yet, because I don't have access to a machine on macOS. I was hoping one of our mac user would take the time to fix the problematic issues so we can merge it, but so far it hasn't happened yet :D
