### ISSUE TITLE
Compiling eig.cpp error

### ISSUE THREAD

**Issue by csv610** [libigl/libigl#416]
Hello,
What could be solution to this compilation error ?
csv

eigs.cpp:146:6: error: 'operator=' is a protected member of 'Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >'
  sU = igl::slice(U,I,2);

**Comment by alecjacobson** [comment]
What version of Eigen are you using? This may be due to the new updates in
3.3.

**Comment by csv610** [comment]
Hello Alec,
I was using Eigen3.3.1 as there were bugs in earlier versions. But since LibIGL isfar more important to me, i downgraded the Eigen to 3.2.8 and it seems the softwareis compiling.
Second, do you know which module in libgil can generate quadmesh over 2D ( with holes)using Frame fields ?
Thanks.csv

**Comment by rui-cai** [comment]
The problem is, for the line "sU = igl::slice(U,I,2);", the assign operator will call the "move-assignment" of the  Eigen::PlainObjectBase class, which has been declared as "protected" function in Eigen 3.3. In Eigen 3.3, only  "copy assignment" of Eigen::PlainObjectBase object is allowed as public.

A hot fix is split the line into two parts, as
Eigen::Matrix<double, -1, -1, 0, -1, -1> tmp = igl::slice(U,I,2);
sU = tmp;

In this way, the assign operator goes to the "copy" one.

**Comment by alecjacobson** [comment]
Thanks. I imagine there are going to be quite a few of these across all the
other functions. We'll have to be careful when updating Eigen.

**Comment by csv610** [comment]
Hello,
Thanks for this valuable fix.
csv
