### ISSUE TITLE
some questions on the boolean function

### ISSUE THREAD

**Issue by luogyong** [libigl/libigl#418]
1) for the function igl::copyleft::cgal::mesh_boolean(VA,FA,VB,FB,boolean_type,VC,FC,**J**),  what is the  J meaning?
if J(i)<=FA.rows(),  means the FC(i) belongs to FA?

2) Can I union two coplanar overlapped facet into one through union operation?

3)  Is there a method to obtain all the intersection lines when two surfaces/volumes are resolved?

4) I there a method to get all sub-blocks/sub-surface when two surfaces/volumes are resolved?

Thank you!

**Comment by alecjacobson** [comment]
1. if `J(i) < FA.rows()` then face i of the output mesh is a sub-triangle of the `J(i)`th face of A. If `J(i)>FA.rows()` then face i of the output mesh is a sub-triangle of the `J(i)-FA.rows()`th face of B.

2. Not sure exactly what you mean. If you just want to merge 2 triangles, then `igl::copyleft::cgal::mesh_boolean` is not appropriate since it operates on "solid geometry" (or more precisely [piecewise-constant winding number mesh](http://www.cs.columbia.edu/cg/mesh-arrangements/#definitions). If you meant, "is it OK if some facet of a solid mesh A is coplanar with some facet of solid mesh B?" Then the answer is yes.

3. For this I would use `igl::copyleft::cgal::intersect_other`. This will split all triangles of each mesh at its intersections with the other mesh. The new edges shared by both meshes will represent the "intersection curve". You'll have to decide whether you want to include/discard "intersection areas" where the meshes overlap at co-planar faces.

4. Not sure what "sub-blocks/sub-surfaces" means. Perhaps the components cut apart by the "intersection curve"? For this, I would use `igl::copyleft::cgal::intersect_other` and then find connected components considering two faces to be neighbors if they share a non-"intersection-curve"-edge.

**Comment by luogyong** [comment]
Thank you for your reply. 
for the second one, from your answer and my own testing, can I say that the libigl cannot make a boolean operation on the meshes when both of them are surfaces(open, not close), even the operation is **resolve**? 
Is there a function to do the job?
for 3) and 4), for the function **igl::copyleft::cgal::mesh_boolean**, when I had made a resolve operation, I hope it can also return all the intersection curves and all sub-blocks/sub-surfaces. here, sub-blocks mean every closed surface and sub-furfaces mean every open surface after resolved.  
Any suggestion to accomplish the function? My work is on finite element modeling. This function is very important and vital for finite element modellings.

Maybe I asked too much. Anyway, I appreciate your job deeply.

**Comment by alecjacobson** [comment]
The short answer is that gl::mesh_boolean your mesh should have no open
boundaries. Technically, boundaries are OK so long as they meet up
perfectly along "seams". Imagine if you have a point "inside" your solid,
then there should be no path that moves the point outside your shape
without passing through the mesh.

"resolve" is really just calling `igl::remesh_intersections` so I would
just call that directly, if that's your goal.

Perhaps posting some inputs and desired outputs would help.

**Comment by luogyong** [comment]
Thank you for your reply.
I know the resolve operation can do something like that;
![image](https://cloud.githubusercontent.com/assets/10364677/21185880/63f3919c-c24d-11e6-8c40-7e5c271db6b4.png)
I hope it can also return all sub-blocks/sub-surfaces like that:
![image](https://cloud.githubusercontent.com/assets/10364677/21186202/b27209ec-c24e-11e6-81f1-183e9d67485c.png)
and that:
![image](https://cloud.githubusercontent.com/assets/10364677/21186478/c3aaeaca-c24f-11e6-8230-d8536abd6820.png)

Thank you.

**Comment by alecjacobson** [comment]
Thanks for the images, this makes it clearer.

I think you'll want to look at `igl::copyleft::cgal::remesh_intersections`, `igl::facet_components`, and `igl::trim_with_solid`.

There are two potential issues you should keep in mind:

1) what do you want to happen if part of the green mesh overlaps with the orange surface  along a co-planar sheet? Which output should this belong to? Or are you going to ensure that this kind of input never happens?

2) For you second image, the first input looks like a "surface with boundary" and the second looks like the well-defined boundary surface of solid volume. In this case, `igl::copyleft::cgal::trim_with_solid` will help you get the **_green_** outputs.

However, it's difficult to "cut" a volume with surface without making some decisions or knowing more about the surface. For example, could the boundary of the green surface ever happen _inside_ of the orange volume? What should the orange output be in that case?

What if the green mesh has self-intersections?

One way I could imagine handling this would be to resolve all of the intersections using `igl::copyleft::cgal::remesh_intersection` then remove any components of the green mesh that contain part of its original boundary. This leaves you with the resolved orange mesh and parts of the green mesh that are bounded by intersections with the orange mesh. Now, you can identify regions of the orange mesh that are bounded by the intersections with the remaining orange mesh. For each _now open_ component of the orange mesh you'll want to _close_ it using the corresponding component from the green mesh.  I imagine that there are some details missing here.

**Comment by luogyong** [comment]
Any example or tutorial on how to use these functions: igl::copyleft::cgal::remesh_intersections, igl::facet_components, and igl::trim_with_solid?

**AND**

Is it possible to implement the following rule to return the resolve operation result:
after a resolve operation is applied on A and B, if any volume(closed surface)  was generated then output it. the left components(if any)  are output as surfaces.

**Comment by alecjacobson** [comment]
No there aren't currently any examples of those.

and

The output of resolve/remesh_intersections is a non-manifold mesh joining
the two input meshes. You should be able to find within that volumetric
components by the process I described above, but being careful about the
ambiguous cases.

**Comment by luogyong** [comment]
OK. I will try your suggestion.
 Here is another question:
when two objects were resolve, why were the  overlapping parts ignored? A test result was shown below.
![image](https://cloud.githubusercontent.com/assets/10364677/21265545/f0f4c8fa-c3dc-11e6-8855-b656692dddbb.png)

Why not output something like that:
![image](https://cloud.githubusercontent.com/assets/10364677/21265633/5e519d88-c3dd-11e6-851a-2fda576b11d9.png)

A similar result  was found when two co-planar surfaces with an overlapping part were resolved.

**Comment by alecjacobson** [comment]
This seems like a bug in "resolve". Could you send the inputs? 
@qnzhou

**Comment by luogyong** [comment]
Attached below is the input files.
[cube_resolve_cube2_off.zip](https://github.com/libigl/libigl/files/657416/cube_resolve_cube2_off.zip)

**Comment by alecjacobson** [comment]
Thanks. I see what has happened. For real boolean operations (union, intersect, minus, xor) duplicate faces resulting from co-planar intersections are pruned away. For resolve, we'd expect all faces to show up in the output, but currently `mesh_boolean` is returning the result _after_ pruning. Probably it should return it before pruning.

But actually, I would rather remove this `"resolve"` option from mesh_boolean since it really isn't a boolean operation and it's just adding to confusion. It only exists to match the cork interface.

Instead users should all `remesh_intersections` directly. 

@qnzhou , what do you think about that?

**Comment by luogyong** [comment]
Oh, NO, I like the **_resolve_** function.

**Comment by qnzhou** [comment]
Good catch @luogyong !

To provide some background, after regular boolean operation (union, intersection, difference, and symmetric difference) we have a solid mesh that induces 0/1 winding number field (assuming the input meshes are PWN).  However, it may contain pairs of identical triangles with opposite orientations.  That is why we run ``igl::resolve_duplicated_faces(...)`` to remove these duplicated triangle pairs so the output mesh is self-intersection free.

However, ``igl::resolve_duplicated_faces(...)`` is not appropriate for ``resolve`` operations.  In fact, if you compile ``mesh_boolean`` in debug mode, the inputs actually trigger an assertion failed error.

@alecjacobson I think separating ``igl::resolve_duplicated_faces(...)`` from ``igl::copyleft::cgal::mesh_boolean(...)`` make sense.  In particular, when the users provide the ``keep`` function, it is unclear if duplicated but opposite oriented triangles should be removed.  However, for regular boolean operation, we have to resolve duplicated faces at some point, otherwise users may complain about finding duplicated faces in boolean outputs.

**Comment by luogyong** [comment]
Yes. outputting duplicated faces is usually not acceptable. To solve the problem, is it possible to output the overlapping faces that only belong to one of objects being resolved? 
Thank you all. Waiting your next commit...

**Comment by alecjacobson** [comment]
The solution for your problem will be to use
igl::copyleft::cgal::remesh_intersections, you can already use this in the
current version.

**Comment by ataber** [comment]
To clarify: as of right now, `igl::copyleft::cgal::mesh_boolean` does trim coplanar and overlapping faces, correct?

**Comment by alecjacobson** [comment]
yes.
