### ISSUE TITLE
igl::hausdorff does not work with MatrixX3d

### ISSUE THREAD

**Issue by evouga** [libigl/libigl#436]
You have to copy the vertices into a MatrixXd, otherwise Eigen spews YOU_MIXED_MATRICES_OF_DIFFERENT_SIZES errors.

**Comment by alecjacobson** [comment]
What're you trying to pass to it?

BTW, please see the warning that igl::hausdorff is computing a lower bound
on hausdorff distance. This is a known issue that probably won't be
resolved soon.

**Comment by evouga** [comment]
Here is a minimal example:

````
#include "igl/readPLY.h"
#include "igl/hausdorff.h"

int main(int argc, char *argv[])
{
	Eigen::MatrixX3d groundV;
	Eigen::MatrixX3i groundF;
	igl::readPLY(argv[1], groundV, groundF);

	Eigen::MatrixX3d testV;
	Eigen::MatrixX3i testF;
	igl::readPLY(argv[2], groundV, groundF);
	double dist;
	igl::hausdorff(groundV, groundF, testV, testF, dist);
}
````

**Comment by alecjacobson** [comment]
Thanks, that helps a lot.

This is a symptom of the way that point_mesh_squared_distance and hausdorff
(and also point_simplex_squared_distance) are attempting to be dimension
agnostic. They're checking the #columns of V at runtime rather than compile
time, so at compile time a 2d and 3d version are compiled. Finally because
your V has fixed 3 columns at compile time the 2D version is failing to
compile.

Originally my idea was to avoid making the caller specify the dimension
(e.g., avoid forcing them to write hausdorff<3> instead of just hausdorff).
But perhaps this was too ambitious.

I hope to get around to this, but might not be until after Jan 17.

**Comment by Poutsh** [comment]
Hi,

I up this issue because I'm facing the same error, when I use Eigen::MatrixX3d i get the YOU_MIXED_MATRICES_OF_DIFFERENT_SIZES error and when I use Eigen::MatrixXd I get an error at runtime.

Is there a way to fix this?

Thank you in advance.

**Comment by alecjacobson** [comment]
It sounds like you might be hitting a different problem when you using `Eigen::MatrixXd`. Could you post a minimal example?

**Comment by Poutsh** [comment]
I used the example posted by @evouga and I get the error as it is. When I'm changing the type of the 4 matrices by Eigen::MatrixXd and Eigen::MatrixXi I'm getting an assert telling me that VA should contain 3d points.

What type of matrices should I use if I want to compare two meshes using hausdorff, or is there a different way to do it?

Thank you for the quick answer

**Comment by Poutsh** [comment]
I managed to fix the error.

For some reason, it was refusing to compile because of the case where dim=2 in the switch of igl::point_mesh_squared_distance. The compiler was testing this case eventhough my matrix had 3 colons, so I commented the case where dim=2. I don't think this is a viable solution but in my case it's sufficient.
