### ISSUE TITLE
Question on minkowski sum

### ISSUE THREAD

**Issue by sh-1** [libigl/libigl#458]
I tried to do something like this.
[https://www.youtube.com/watch?v=lPgLZgnbREk&t=400s](url)

and my code is 

	Eigen::MatrixXd VModel, VPart;
	Eigen::MatrixXi FModel, FPart;

	igl::readOFF("./models/cuboid.off", VModel, FModel);
	igl::readOFF("./models/sphere.off", VPart, FPart);

	Eigen::MatrixXd resultV;
	Eigen::MatrixXi resultF;
	Eigen::VectorXi resultJ;

	igl::copyleft::cgal::minkowski_sum(VModel, FModel, VPart, FPart, true, resultV, resultF, resultJ);

	igl::writeOFF("./result/out.off", resultV, resultF);

    return 0;

but when I try to compile this, it causes error C2248 at minkowski_sum.cpp line142.
Then I changed the code 
J = slice(DerivedJ(J),SJ,1);
to
slice(DerivedJ(J), SJ, 1, J);

and succeeded in compiling it (but I don't know its correct or not).
But it stops running with Assertion failed message
"Assertion failed: A.nonZeros()%2 == 0, files c:mydirectory\libigl\include\igl\edges.cpp, line 21"

I am using VS2015 on windows 8.1 64bit.

Is my usage incorrect? Do you know what the problem is?

Thanks in advance,

**Comment by alecjacobson** [comment]
could you upload your models so we can debug?

**Comment by sh-1** [comment]
Thanks for your reply!

These are the models,
[https://www.dropbox.com/sh/qp9mi0zb3ilf8x0/AACQubDo-gzplcV_hH_qu6BPa?dl=0](https://www.dropbox.com/sh/qp9mi0zb3ilf8x0/AACQubDo-gzplcV_hH_qu6BPa?dl=0)

These are just a simple cuboid and a coarse sphere.

**Comment by alecjacobson** [comment]
@qnzhou Do you have any ideas about this issue?

**Comment by fusentasticus** [comment]
This problem could simply be due to a degenerate triangle in your input. If you have a triangle with two identical vertices, then (after duplicate vertex removal) one edge of the triangle in F becomes a loop and the entry for that edge will appear only once in the adjacency matrix (in the diagonal). Now, if you have an odd number of such pathologies, then you'll be in luck and your problem will be caught by the invariant check in edges.cpp!   The obj code below reproduces the problem if  `igl::remove_duplicate_vertices` is used to scrub the input.  Meshmixer does not flag such triangles. Perhaps `igl:adjacency_matrix` should report this?

v -27.7917347 -5.23339653 0.7492955923
vn -0.05033982918 0.6383653879 -0.7680856586
v -27.7917347 -5.23339653 0.7492955923
vn -0.04969974235 0.6434671283 -0.7638586164
v -27.73283195 -5.342694283 0.6319471598
vn -0.05422706902 0.6783614159 -0.7327244878

# mm_gid 3
g mmGroup3
f 2//2 1//1 3//3
```

**Comment by qnzhou** [comment]
@alecjacobson Can you check the PR above?

@sh-1 I have updated your main file (in particular, `resultJ` should be a matrix instead of a vector):

```C++
#include <Eigen/Core>
#include <igl/readOFF.h>
#include <igl/writeOFF.h>
#include <igl/copyleft/cgal/minkowski_sum.h>

int main(int argc, char** argv) {
    Eigen::MatrixXd VModel, VPart;
    Eigen::MatrixXi FModel, FPart;

    igl::readOFF("./cuboid.off", VModel, FModel);
    igl::readOFF("./sphere.off", VPart, FPart);

    Eigen::MatrixXd resultV;
    Eigen::MatrixXi resultF;
    Eigen::MatrixXi resultJ;

    igl::copyleft::cgal::minkowski_sum(VModel, FModel, VPart, FPart, true, resultV, resultF, resultJ);

    igl::writeOFF("./out.off", resultV, resultF);

    return 0;
}
```

**Comment by fusentasticus** [comment]
So my comment was off the mark, mostly! Still for fool-proof fail-early asserts, you might want to change  line 33 `if(it.row()<it.col())` in

**Comment by fusentasticus** [comment]
So my comment was off the mark, mostly! Thanks for looking at it anyways. If you want people to fail early for all cases (since bad stuff may pass through other tools to libigl as I found out the hard way!) may I suggest it might be worth complementing the assert for evenness (which was triggered in original post)? Specifically, augment the comparison in https://github.com/libigl/libigl/blob/master/include/igl/edges.cpp#L33 for equality, and add an assert if true? Or perhaps do it in `igl:adjacency_matrix`?
