### ISSUE TITLE
Using pyigl with other pybind11 exports

### ISSUE THREAD

**Issue by MichaelRabinovich** [libigl/libigl#467]
Hey all,

I might be doing something wrong, but I'm having problem importing modules that I've built with pybind11 and pyigl together. After importing pyigl, calling otherwise functioning methods through another pybind11 makes my python program crush with a segmentation fault or a bus error. 

The problem seems to come from compiling my other pybind11 module with another version of pybind11.h than the one you use for libigl. If I built it with your header files some routines seems to work. However I can't use your version since it doesn't seem to include the file Eigen.h necessary for me to seamlessly call my c++ Eigen functions with a numpy array.

Any ideas what can I do?

Thanks,
Michael

**Comment by danielepanozzo** [comment]
Do you use a special version of pybind11 or is it simply a newer version of the one with use in libigl? 

If it is just newer, I would suggest to send a PR to libigl updating the bundled pybind11 to the latest version (and fixing whatever problems this might introduce). You would then be able to use the same version for both libigl and your code. I am adding @s-koch  to this discussion since he is using daily the python bindings and he might want to comment on this before you go ahead and prepare the PR.

**Comment by s-koch** [comment]
Hi, 
I just recently updated the version of pybind11 which is used by libigl to release v2.0 (from January 2017). However, the python bindings of libigl can also be compiled with the latest version in their repository. You can just replace it with the ext/nanogui folder.
Given your question, I am not so sure if this is really just a version problem or if it's related to libigl having its own binding of Eigen types. Can you maybe elaborate on your build process and what calls you want to make?

**Comment by MichaelRabinovich** [comment]
Oh I'm sorry, for some reason I was convinced you added stuff and changed pybind11 in libigl. Updating pybind11 for libigl like you said fixed it.
Thanks!

**Comment by s-koch** [comment]
Ok great! Out of curiosity, are you using the iglhelpers functions to convert between the pybind11 eigen/numpy types and libigl's eigen types?
