### ISSUE TITLE
Access violation error in Triangle.c

### ISSUE THREAD

**Issue by danhambleton** [libigl/libigl#487]
I'm trying to use the Triangle lib (external/triangle) and the provided wrapper (libigl/include/triangle). Everything is compiling fine, however when I run a basic test, I get an access violation error [here](https://github.com/libigl/triangle/blob/428a74fd93766f70ab7f718dec22026707283db6/triangle.c#L14127).

Here is my code (should be exactly the same as the tutorial):

```
	using namespace Eigen;
	using namespace std;

	// Input polygon
	Eigen::MatrixXd V;
	Eigen::MatrixXi E;
	Eigen::MatrixXd H;

	// Triangulated interior
	Eigen::MatrixXd V2;
	Eigen::MatrixXi F2;


	// Create the boundary of a square
	V.resize(8, 2);
	E.resize(8, 2);
	H.resize(1, 2);

	V << -1, -1, 1, -1, 1, 1, -1, 1,
		-2, -2, 2, -2, 2, 2, -2, 2;

	E << 0, 1, 1, 2, 2, 3, 3, 0,
		4, 5, 5, 6, 6, 7, 7, 4;

	H << 0, 0;

	// Triangulate the interior
	igl::triangle::triangulate(V, E, H, "a0.005q", V2, F2);
```
I am compiling on Windows, targeting x64. I'm using libigl as header only, and building triangle as a static lib (using the libigl provided cmake).

Has anyone else had any issues with this?

**Comment by alecjacobson** [comment]
Eww. I'm not sure the best way to go about debugging this.

On my mac, I'm not getting any problems.

Does debug mode reveal anything?

Is there a chance that somehow triangle is being compiled with different flags from the main program?

If I or someone can test on a windows machine, we might learn more...

**Comment by danhambleton** [comment]
Hrmm, strange. I double checked the compiler flags and they are indeed the same. The relevant ones for triangle seem to be: 
```
TRILIBRARY
ANSI_DECLARATORS
NO_TIMER
```

**Comment by danhambleton** [comment]
I am happy to test whatever changes on my windows set up, btw.

**Comment by alecjacobson** [comment]
I'm just not sure what to change...

Does it work for 64bit?

**Comment by anklinv** [comment]
I had exactly the same problem. The issue was that in the triangle library it is assumed that `long` is 8 bytes long, but when compiling on Windows 64bit it is actually only 4 bytes. As the triangles library uses  `long` as pointers it results in an access violation. The temporary fix is to replace every instance of `long` with `__int64` in the triangle.c file.

**Comment by anklinv** [comment]
I had exactly the same problem. The issue was that in the triangle library it is assumed that `long` is 8 bytes long, but when compiling on Windows 64bit it is actually only 4 bytes. As the triangles library uses  `long` as pointers it results in an access violation. The temporary fix is to replace every instance of `long` with `__int64` in the triangle.c file.

**Comment by danhambleton** [comment]
Ah, that makes sense. Good catch! I will test it out.

**Comment by Nes-tle** [comment]
@anklinv Much thanks to your insight!
