### ISSUE TITLE
Does libigl have any remeshing modules?

### ISSUE THREAD

**Issue by Ahbee** [libigl/libigl#49]
Hello, I see that it can generate N-rosy fields, but is it possible to remesh based on the rosy field?
If not can anyone point me to another library or source code that can. Thanks.

**Comment by danielepanozzo** [comment]
Hi,
we have here an example that uses libigl to produce a seamless parametrization:
http://libigl.github.io/libigl/tutorial/tutorial.html#505

If you want a mesh, you can pass this parametrization to libQEX (https://github.com/hcebke/libQEx) to extract it. We do not have it built in in the tutorial due to a more restrictive licence used by libQEX.

**Comment by chrisidefix** [comment]
Hi Daniele, maybe questions like this one could go into a FAQ, since you already took the time to respond, maybe copy paste this into a github wiki page or somewhere in your documentation, since it's otherwise hard for anyone else to find. Cheers!

**Comment by alecjacobson** [comment]
Good idea. But for now the "issues" page _is_ the FAQ. Adding a proper FAQ
is a perennial todo item, we probably won't get to anytime soon.

**Comment by chrisidefix** [comment]
Yeah - I started copy-pasting stuff myself, but I guess it's pointless, since it will just make things redundant. I guess the Issues page works until you can hire a technical writer ;).
