### ISSUE TITLE
tutorials does not compile as described in page!

### ISSUE THREAD

**Issue by rodolfolotte** [libigl/libigl#502]
Hey, I've getting a lot of erros in the configuration of libigl. Maybe it's a simple question, but ask this here could also help many others. So, I'm sorry for that. 

1. First, before to clone the project, I took care to install all dependencies (mentioned in tutorial page):

`sudo apt-get install git`
`sudo apt-get install build-essential`
`sudo apt-get install cmake`
`sudo apt-get install libx11-dev`
`sudo apt-get install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev`
`sudo apt-get install libxrandr-dev`
`sudo apt-get install libxi-dev`
`sudo apt-get install libxmu-dev`
`sudo apt-get install libblas-dev`

After that, I've cloned libigl recursively (--recursive) and placed it in **/home/myfolder/Documents/**. Ok, next to this folder (**in /home/myfolder/Documents/**), I also cloned libigl-example-project (recursively).

Inside /libigl-example/build/ , I did:

`cmake ..`
`make`

which worked perfectly! 

But when I try to go in **/home/myfolder/Documents/libigl/tutorial/102_DrawMesh/**, for instance, and try to do the same thing, I get something like:

`fatal error: igl/readOFF.h: File not found
 #include <igl/readOFF.h>
                         ^
compilation terminated.
CMakeFiles/102_DrawMesh_bin.dir/build.make:62: recipe for target 'CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/102_DrawMesh_bin.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/102_DrawMesh_bin.dir/all' failed
make[1]: *** [CMakeFiles/102_DrawMesh_bin.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

I mean, in tutorial page says: **"The examples can also be built independently using the CMakeLists.txt inside each example folder."**, what I did was to create a build folder inside ../102_DrawMesh/, and try to configure and make as I did in libigl-example-project, but I did not work as described! Also if I try to configure an alternative example, lets say, in **/home/XYZ/tests/** :

`#include <igl/readOFF.h>`
`#include <igl/viewer/Viewer.h>`

`Eigen::MatrixXd V;`
`Eigen::MatrixXi F;`

`int main(int argc, char *argv[]) {`
 ` // Load a mesh in OFF format`
  `igl::readOFF(TUTORIAL_SHARED_PATH "/bunny.off", V, F);`

 ` // Plot the mesh`
  `igl::viewer::Viewer viewer;`
  `viewer.data.set_mesh(V, F);`
  `viewer.launch();`
`}`
also got: _**libigl not found --- You can download it using...**_

I did not build ANYTHING, only cloned the libigl and try to compile the example, but it was not possible.

Could someone clarify or even give me some tips about that?

Thank you, Rodolfo.

**Comment by jiangzhongshi** [comment]
Hi,

To compile the tutorials, all you need to do is the first step, which you succeeded. And inside the build folder, there'll be binaries that run each tutorial.

And about your question, I would suggest you read more about the CMake workflow. 
I may explain it as follows:
the whole tutorial is configured as a whole, from the `CMakeLists.txt` in `tutorial`. It contains the general settings and calls each `CMakeLists.txt` in the subdirectory, such as `102_DrawMesh/CMakeLists.txt` to configure additional settings for each independent projects (each tutorial).
So when you call `cmake` on the subdirectory's `CMakeLists.txt`, it's valid, but you get only the customized settings information for each project, instead of the more important general settings, such as where to find `libigl`.

Also, if you want to build you own project, it's very helpful to refer to the template CMake files in [libigl-example-project](https://github.com/libigl/libigl-example-project).

Best,
Zhongshi
