### ISSUE TITLE
missing explicit template instantiation in "extract_manifold_patches.cpp"

### ISSUE THREAD

**Issue by Luk0r** [libigl/libigl#512]
only the long version has its instantiation for the static build, the short version is missing.
```C++
size_t n = igl::extract_manifold_patches(F, P); // linker error
```

**Comment by jiangzhongshi** [comment]
Since `libigl` is a templated class, most of the functions are not already explicitly instantiated (because of numerous possibilities!).

So when using it as  the static library, we always need to explicitly instantiate ourself. 

You can follow the way of existing instantiations to declare the ones that you need. Or refer to the [script](https://github.com/libigl/libigl/blob/master/scripts/autoexplicit.sh)
