### ISSUE TITLE
Can't build pyigl with nanogui #mac

### ISSUE THREAD

**Issue by YupanWang** [libigl/libigl#536]
I tried to build igl with nanogui  in python version, I modified the code in cmakelists:
option(LIBIGL_WITH_NANOGUI          "Use Nanogui menu"   OFF).   to
option(LIBIGL_WITH_NANOGUI          "Use Nanogui menu"   ON).

 but in the cmake phase, there is the warning:

"CMake Warning (dev) at CMakeLists.txt:208 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "nanogui-python".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate."

and in the make phase, there is an error:
Scanning dependencies of target copy
Error copying file "/Users/wangyupan/libigl/python/build/libigl/nanogui/python/nanogui" to "/Users/wangyupan/libigl/python/build/../".
make[2]: *** [copy] Error 1
make[1]: *** [CMakeFiles/copy.dir/all] Error 2
make: *** [all] Error 2

What can I do ?

**Comment by MichaelRabinovich** [comment]
Guys I'm having the same problem. I'll detail here all the (boring) details of what I've done, so you could maybe see if I made some mistake at any point:

It also seems that it doesn't build "libigl/python/build/libigl/nanogui/python/nanogui" so I went and manually build it (by going to libigl/python/build/libigl/nanogui and running make), and then ran make again which made the copy operation work, and then renamed the copied file from nanogui to nanogui.so (otherwise import nanogui doesn't work).
When I import nanogui after pyigl I get warnings that look like this:

objc[26466]: Class GLFWLayoutListener is implemented in both /Users/michaelrabinovich/libigl/python/pyigl.so (0x10fd1b918) and /Users/michaelrabinovich/libigl/python/nanogui.so (0x1102ec180). One of the two will be used. Which one is undefined.

But I was still optimistic so I've tried running example 106 and got the python error:
 File "./106_ViewerMenu.py", line 61, in viewer_init
    viewer.screen.performLayout()
TypeError: Unable to convert function return value to a Python type! The signature was
	(self: pyigl.viewer.Viewer) -> nanogui::Screen

I would appreciate any help. Any idea what I did wrong?

Best,
Michael
