### ISSUE TITLE
Could "Biharmonic Coordinates" be used for "Deformation Transfer" ?

### ISSUE THREAD

**Issue by sjoerd-dijkstra** [libigl/libigl#556]
Hi!

In tutorial 407 the high resolution mesh is controlled by the low resolution mesh through the pointhandles/weights computed by `igl::biharmonic_coordinates()`.

I was wondering of this approach could be used to achieve similar results as "Deformation Transfer" as described by Sumner et al. (http://people.csail.mit.edu/sumner/research/deftransfer/Sumner2004DTF.pdf).

What i have is two meshes (A & B) of the same shape (registered surfaces with a non-rigid icp), but with a different vertex topology. For the one mesh A, i have a blendshape that i would like to transfer to the mesh B. So far the approach:

```cpp
// mesh classes with vertices (V) and faces (F)
A, A_deformed, B; // known
B_deformed;     // unknow

// point handles
Eigen::VectorXi b;

//weights
Eigen::MatrixXd W;

// find closest points as point handles A->B
Eigen::VectorXi J = Eigen::VectorXi::LinSpaced(B.V.rows(),0,B.V.rows()-1);
igl::point_mesh_squared_distance(A.V, B.V, J, _, b, _);

// calculate biharmonic coordinates
igl::slice(B.V, b, 1, A.V);
std::vector<std::vector<int> > S;
igl::matrix_to_list(b, S);
igl::biharmonic_coordinates(B.V, B.F, S, 3, W);   // here it breaks

// transfer deformation
B_deformed.V = W * (A_deformed.V.rowwise() + RowVector3d(1,0,0)));
B_deformed.F = B.F;
```

If possible, it seems the meshes in the tutorial use tetrahedra  rather than triangles, is this necessary? My meshes both have vertices with dim=3 and faces also with dim=3 (triangles).

Thanks!
Sjoerd

**Comment by alecjacobson** [comment]
You could probably do something of this sort.

What we call "Biharmonic coordinates" are defined over subregions of space (volumes in 3D) rather than surfaces.

There are other ways to use the biharmonic equation / related energy to define smooth interpolation (e.g., bounded biharmonic weights) that can work on surfaces.

If your shapes are closed or at least represent closed objects then you might also try using Nested Cages + biharmonic coordinates. Just a thought anyway.

One issue that might come up is that the original deformation transfer (if I remember right) uses compactly supported basis functions. So other non-local functions might affect performance.

**Comment by Sjoerdie** [comment]
Thanks so much! I see now. My shapes were, unfortunatly, not closed and too big for calculating bounded biharmonic weights for so many points. In the end, a sparse LU solver for all local triangle transformation functions did the trick :)

A follow up question: Is there a way for retrieving the second (and third, etc.) closest point with `igl::point_mesh_squared_distance()`?

 I'm trying to calculate a correspondence map for the triangles of the two meshes. Two triangles correspond if their centroids are within a certain threshold (i'm using the squared distance) of each other and the angle between their normals is less than 90 degrees.

So far i have the centroids calculated and `igl::point_mesh_squared_distance()` tells me which centroids are closest to each other. Thereafter `igl::per_face_normals()` helps me find out whether the normals of the triangles are compatible (angle < 90 degrees).

Is there a way of getting an ordered list of closest points?

**Comment by hicup82017** [comment]
Hi Alex,
I like the way your library is built towards geometry :).
My query is related to **bi-harmonic co-ordinates**. 
I am interested to use bi-harmonic co-ordinates to my mesh deformation. I observed it to have a lot of nice properties. 
I am able to get the weights into my project and deform very well. But here comes the problem, when I try to use it in my application.
**Problem 1:** Some of the weights are negative. I have read your paper, which tells how negative weights are useful.
 Is it possible to restrict the weights to be only positive weights?
**Problem 2:** For real time deformation, we tend to minimize the control points to only 4. Most game engines follow the same policy. 
 Can you suggest an easy way to find the best positive and negative weights (together shall be 4) that I can take and normalize?

**Comment by jmespadero** [comment]
Hi @hicup82017 
If you have problem with negative weights you can give a try to _mean-value laplacian_ 
![cotangent](https://user-images.githubusercontent.com/6451497/31452672-e3f0836a-aeaf-11e7-8920-7a98da7f2580.png)

Instead of using weights `w_ij = cot(α) + cot(β)`

try weights `w_ij = (tg(θ1 / 2) + tg(θ2 / 2)) / |Vi-Vj|`, which are always positive.

You can read more at
http://www.cs.princeton.edu/courses/archive/fall10/cos526/papers/sorkine05.pdf

If you are interested in the c++code, I have it coded with IGL.

**Comment by alecjacobson** [comment]
@jmespadero I think @hicup82017 is referring to the skinning weights rather than the cotangent coefficients in the system matrix.

"biharmonic coordinates" [Wang et al. 2015] can be _negative_. This is a consequence of improving fairness/smoothness. It's a "no free lunch" situation. In contrast, "bounded biharmonic weights" (`igl::bbw`) will guarantee positivity but at the cost of flattening out near each handle (this can look bad if you have a lot of handles; for a few handles this is actually usually what you want).

Sparsity (no more than 4 weights per point) is harder to accomplish. There's no perfect solution that I know of (the so-called "local barycentric coordinates " trade smoothness for sparsity and don't guarantee an limit on the number of non-zero weights. 

There's a paper "Poisson-Based Weight Reduction of Animated Meshes" [Landreneau & Schaefer 2010] that describes a procedure to _sparsify_ weights. This works quite well. In my experience, the "example-based" part of this paper (section 4) is not necessary. I found that with a good QP solver (like mosek or maybe libigl's active set solver) the section 3.3 was already good. 

In the end, given some initial weights (say in a #vertices by #bones matrix X) you could optimize for sparse weights via 

min_W  (L*X - L*W)' * M^-1 * (L*X - L*W)
subject to W(i,j) = 0 if X(i,j) is not one of the 4th largest values in ith row of X
and W > 0

(technically you should also constrain that sum_j W(i,j) = 1 , but this will require optimizing all weights simultaneously, not strictly necessary as you can usually normalize _post facto_).
