### ISSUE TITLE
Mesh that looks PWN failing piecewise_constant_winding_number

### ISSUE THREAD

**Issue by ataber** [libigl/libigl#599]
When I attempt to do a boolean operation on [this mesh](https://github.com/libigl/libigl/files/1289431/wing.ply.gz), I see the ["Input mesh is not orientable" error](https://github.com/libigl/libigl/blob/e2aa034ab822d492ba74d736a8d823a317e8520e/include/igl/copyleft/cgal/propagate_winding_numbers.cpp#L123). It is true that my mesh isn't manifold, but it appears as if it should have a piecewise constant winding number. I'm especially confused because [here](https://github.com/libigl/libigl/issues/418#issuecomment-266779793) it sounds like it's path-wise solid at every point (although perhaps I'm not understanding that comment).

Is there something I'm missing with this mesh? In Meshlab I can't see any Z-fighting so I don't think there's any overlapping oppositely-oriented tris.

**Comment by alecjacobson** [comment]
@qnzhou might be able to provide a better diagnosis, but from a quick look this mesh is probably not PWN. 

The mesh has an open boundary. This does not strictly invalidate PWN, but the boundary is still there after resolving self-intersections. This is probably a bad sign. 

If the boundaries are just little flaps, you could try removing those "manifold components" after resolving self-intersections. Otherwise, unfortunately, you might have to clean this up before using booleans/CSG.

**Comment by alecjacobson** [comment]
This mesh has a bunch of non-manifold elements (which are OK) and two geometrically open boundary loops (not OK). If you close those boundaries (i.e., with a simple fan of triangles) then the mesh becomes PWN and can be used for booleans. 

I did this in matlab but it's the same function in C++:

```matlab
[V,F] = load_mesh('/Users/alecjacobson/Downloads/wing.ply');
G = [F;fill_holes(V,F)];
[VV,FF] = mesh_boolean(V,F,[],[],'union');
```
