### ISSUE TITLE
Parametrization 

### ISSUE THREAD

**Issue by lmert** [libigl/libigl#608]
I can do the harmonic, least squares conformal maps and as-rigid-as-possible parametrizations with tutorial's example input mesh(camelhead) as described in the tutorial. It is so cool.

However, when I change the input mesh(hand) I could not get any result for harmonic parametrization. Code ran but while it was running it printed errors "numerical issue" and "invalid solver type" in the console. Therefore I could not get the result. It calculated boundries and corresponding u,v coordinates of them but at the end of the harmonic function; all u,v coordinates corresponding to vertices were same and all u and v values were same each other and all the values were very very small(6.27743856220410e+67). Boundry u,v coordinates were normal, I think. 

Then I tried the other methods but they also did not work for my input mesh.
For least squares conformal maps: code ran but while it was running it printed errors "numerical issue" in the console.    
For as-rigid-as-possible: code ran but while it was running it printed errors "numerical issue" and "invalid solver type" in the console.

What is the problem of my input mesh? Or what are the input restrictions for parametrization methods? Can anyone help me?

My input mesh: [hand.obj.txt](https://github.com/libigl/libigl/files/1309094/hand.obj.txt)

**Comment by jmespadero** [comment]
Always check the sanity of your data before of process it. You have 645 unreferenced vertex

```txt
Loading file hand.obj
Num vertex: 2146 Num triangles: 2960 Unreferenced vertex: 645
minArea: 3.42601 maxArea: 74.9705 averageArea: 22.0296 totalArea: 65207.7
minAngle: 0.109459 maxAngle: 2.67043
List of triangles with ShapeFactor > 4
Sum of VertexAreas = 65207.7
Triangle 2933 has ShapeFactor 4.57706
```

You can use meshlab  `filter->Remove unreferenced vertex` and try again...
![screenshot at 2017-10-11 17 13 30](https://user-images.githubusercontent.com/6451497/31449708-eda768cc-aea7-11e7-949a-060d6dfea989.png)

**Comment by lmert** [comment]
Thanks for your answer. You are right. After removing unreferenced vertices, I managed to apply parametrization.

**Comment by LvYangming** [comment]
I also meet this problem，and my mesh is sanity but messy,Can anyone help me?
My input mesh:
[hair.OBJ.txt](https://github.com/libigl/libigl/files/1792386/hair.OBJ.txt)

**Comment by jmespadero** [comment]
You can't apply this method because that mesh is **non-manifold** and has a **non-unique boundary**... 
![hair](https://user-images.githubusercontent.com/6451497/37143104-6b4796a4-22ba-11e8-86cd-88e5549c922d.jpg)

**Comment by LvYangming** [comment]
Thanks for the reply. For some reason I can not do mesh seperate and combine in  my project. Is there any other deformation algorithm which fit this issue? 
Currently I am using MLS to do the deformation, but the result is unsatisfactorily.

**Comment by jmespadero** [comment]
This thread is about parameterization, not about deformation. It is true that you can use a parameterization as a tool to model your deformation, but keep in mind that are different things.

It is quite easy to create a parameterization for each patch of your mesh using blender -> Edit mode -> Unwrap. 
![hairunwrap](https://user-images.githubusercontent.com/6451497/37272897-63efdaee-25d8-11e8-8faa-891cc43818c6.png)

From this parameterization it is easier to craft a method to translate a single deformation in 1D to your 3D mesh. 

If you need to craft a even more tailored parameterization, you can read this...
https://blender.stackexchange.com/questions/66710/is-this-workflow-for-texture-atlas-ok

**Comment by MunichMogician** [comment]
I also met this problem, could you please tell me how to use the igl::remove_unreferenced in the code specifically, like which parameter means what, or kindly show any code written when solve it? great thanks @lmert @jmespadero

**Comment by jmespadero** [comment]
In this case, the problem is not about unreferenced vertex, but about **duplicated vertex**. This means that there are multiple vertex with same coordinates but different index. Your mesh is not a "shared-coordinates triangle mesh" with " but a "[triangle soup](https://stackoverflow.com/questions/24792749/what-soup-definition-means-in-triangle-soup-or-polygon-soup)".

You can easily solve that problem using IGL calling the [remove_duplicate_vertices(V, 0.001)](https://github.com/libigl/libigl/blob/master/include/igl/remove_duplicate_vertices.h) method, or also using [meshlabjs](http://www.meshlabjs.net/) and apply the "Remove duplicate vertex" filter.

But after that, you will find another problem... your mesh has a hole (in the right eye) due to noise in the geometry capture. So, even after removing duplicated vertex, you won't meet the **have one unique boundary** condition and won't be able to create a parameterization with IGL. The solution is manually edit the mesh (with meshlab or with blender3D) and close that hole in the right eye, so you don't get those red vertex in the interior of your mesh when applying "colorize by border distance"

![screenshot at 2018-05-04 10-33-57](https://user-images.githubusercontent.com/6451497/39620391-4bd64060-4f8b-11e8-9958-d43903dd689c.jpg)

**Comment by MunichMogician** [comment]
So kind and perfect answer! Sincere thanks!
