### ISSUE TITLE
determining the set of all mesh faces within view of a point

### ISSUE THREAD

**Issue by sadams69** [libigl/libigl#614]
I am interested in texturing a mesh using cameras from multiple vantage points. To do so, I would like to determine the set of all mesh faces visible to each camera. Are there features within libigl to facilitate or carry out this process? 

Even just a few hints would be appreciated to get me started.

**Comment by alecjacobson** [comment]
You'll probably need to define "visible" since in general _part_ of the triangle might be visible and part might be occluded.

Certainly, you can start by checking that the face normals don't point away from the camera (use `igl::per_face_normals` and then take the dot product with a vector from the triangle (one of the corners or the `igl::barycenter`) and the camera position. 

If you defined visibility to be such that the _entire_ triangle must be visible. Then you could solve this by creating a tetrahedron for each triangle and checking whether it intersects any of the original faces using `igl::copyleft::cgal::intersect_other`.
