### ISSUE TITLE
pyigl.eigen.MatrixXi.__init__() can't take list of list of integers as input

### ISSUE THREAD

**Issue by qianyizh** [libigl/libigl#714]
This error started after PR #696 

The following code used to work well pre-patch:
```
>>> import pyigl as igl
>>> x = igl.eigen.MatrixXi([[1,2,3], [2,3,4]])
```

After the PR, it causes an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pyigl.eigen.MatrixXi()
    2. pyigl.eigen.MatrixXi(arg0: int, arg1: int)
    3. pyigl.eigen.MatrixXi(arg0: int)
    4. pyigl.eigen.MatrixXi(arg0: buffer)
    5. pyigl.eigen.MatrixXi(arg0: std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >)
    6. pyigl.eigen.MatrixXi(arg0: std::vector<int, std::allocator<int> >)

Invoked with: [[1, 2, 3], [2, 3, 4]]

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.
```

The error seems to be caused by an incorrect binding of ``std::vector<std::vector<int>>``. In particular, if the following lines are commented the issue can be fixed.

https://github.com/libigl/libigl/blob/f50084cacb0f3ec76ef270d0a1bc3e9931ac2719/python/modules/py_typedefs.h#L21-L22

What's the purpose of these two lines? They seem to be redundant to me, since the bindings are now automatically included via ``<pybind11/std_bind.h>``. Can these lines be safely removed?

**Comment by fwilliams** [comment]
I might be the cause of this bug. I wrote this a while back because `igl::adjacency_list` took a `vector<vector<int>>` as a parameter and there was no clear way to pass such a type from python. AFAICT there are other functions in libIGL which take a `vector<vector<int>>` (just `git grep "vector<vector<"` to see which). If you can make `adjacency_list` work from python and test some of these other functions withouth the 2 lines in `py_typedefs.h`, then it should be safe to remove those lines.

Pybind incorrectly binding `vector<vector<int>>` to `Eigen::MatrixXi` seems like a bug in pybind at first glance. Maybe report it there.

**Comment by fwilliams** [comment]
I might be the cause of this bug. I wrote this a while back because `igl::adjacency_list` took a `vector<vector<int>>` as a parameter and there was no clear way to pass such a type from python. AFAICT there are other functions in libIGL which take a `vector<vector<int>>` (just `git grep "vector<vector<"` to see which). If you can make `adjacency_list` work from python and test some of these other functions withouth the 2 lines in `py_typedefs.h`, then it should be safe to remove those lines.

Pybind incorrectly binding `vector<vector<int>>` to `Eigen::MatrixXi` seems like a bug in pybind at first glance. Maybe report it there.

**Comment by jiangzhongshi** [comment]
@fwilliams I don't quite understand. From what I know, pybind is supposed to bind `vector<vector<int>>` to `list(list())`.

**Comment by teseoch** [comment]
Obsolete, we now use numpy
