### ISSUE TITLE
Plotting a spline onto a mesh respecting its surface (convex hull)

### ISSUE THREAD

**Issue by aseverino** [libigl/libigl#744]
First of all, I'd like to congratulate you guys for the really solid work with this library. I'm truly impressed.

Second, the reason I'm here writing to you, and the title says pretty much everything I want to ask. Easy to ask, but I'm pretty sure its no easy job to answer (let go implement):

How can I plot a cubic bezier curved spline in a given mesh respecting its convex hull?

I have seen some hints on splines in the "shady" unsupported directory of the Eigen library. From what I found so far, there is no documentation or examples on how to use them. I also already have everything working in terms of drawing points on the mesh (`igl::unproject_in_mesh`). My knowledge doesn't go any farther than that.

How would you implement that? Any hints?

**Comment by joshua0702k** [comment]
Any update on the above question? I am looking to implement something very similar - constructing a spline with control points that lies on the surface of a mesh (instead of the convex hull).  Would love too hear any ideas!  

I believe there is a paper  published by IGL that addressed this, but cannot seem to find any implementation. - http://igl.ethz.ch/projects/wa/weighted-averages-siggraph-2013-panozzo-et-al.pdf. 

Thank you for the help!

**Comment by alecjacobson** [comment]
I'm not sure what it means "respecting its convex hull".

Projecting curves onto triangulated surfaces can be a bit tricky. Doing it pointwise (ie sampling the curve densely and projecting each sample) can lead to discontinuities in hard cases.

defining splines directly on surfaces might work better. You could try Nick Sharp's "Flip Out" method.
