### ISSUE TITLE
Question about collapse_edge

### ISSUE THREAD

**Issue by cap257zero** [libigl/libigl#75]
This is a question about how collapse_edge works (was not sure how to label the issue as a question). I mostly want to make sure I understand it correctly. Suppose I do a single edge collapse

igl::collapse_edge(e, ...)

where e joins vertices i and j (vertices with indices i < j in V) and the edge collapse is valid. Then

-- F will have two blank rows with IGL_COLLAPSE_EDGE_NULL as the entries,
corresponding to the two faces previously recorded in F which now got collapsed

-- V will have row i changed to the coordinates of the new vertex to which the endpoints
of the edge e got collapsed (e.g., the midpoint)

-- V will still have row j unchanged, and this is now a vertex that does not appear in any faces or edges (because collapse_edge has updated F, E, etc)

At this point, I don't have to worry about the dangling vertex in V, and I can collapse another edge.
So for example if I wanted to collapse only edges shorter than some threshold L I could loop through the edges like this:

for (int e = 0; e < E.rows(); ++e) {
	len = (V.row(E(e,0)) - V.row(E(e,1))).norm();
	if (len < L) {
		mid = 0.5 * (V.row(E(e,0)) + V.row(E(e,1)));
		igl::collapse_edge(e, mid, V, F, E, EMAP, EF, EI);
	}
}

At the end of all this, I'd have V and F and I can remove the NULL faces from F without invalidating anything.

However with V, I'll have to find the vertices that are not in any face and remove them from V, and if I do this for example by deleting a row of V, I'd change the indices of any subsequent vertices and therefore have to adjust F accordingly.

Thank you very much for any help.

**Comment by cap257zero** [comment]
Ah and just to add to this, I notice you have kindly provided remove_unreferenced for just this purpose of updating V and F.

**Comment by alecjacobson** [comment]
You're understanding is correct. However, your for loop might be a bit dangerous/misleading. Since `igl::collapse_edge` updates `E`, you might try to get the length of a _removed edge_ whose indices have been also set to `IGL_COLLAPSE_EDGE_NULL`. I think I'm doing enough checks inside of `igl::collapse_edge` to prevent this from throwing exceptions (just returns false), but you might consider checking explicitly during your loop over your edges if the edge `E.row(e)` still exists. 

Also, a single pass via your for loop may still leave edges with lengths less than `L`. You might consider doing multiple passes until no edge is collapsed. Or better yet, use a priority queue based on the edge-length and collapse until empty.

**Comment by cap257zero** [comment]
Thanks a bunch! I will take the suggested precautions.
