### ISSUE TITLE
ImGuiMenu's keypress event processing order

### ISSUE THREAD

**Issue by TerranRush** [libigl/libigl#764]
If I bind a callback_key_pressed() to Viewer, then it will be processed before ImGuiMenu's key_pressed(). So if I catch a number stroke, like `if (key == '3')` in callback_key_pressed() of Viewer, then widgets in ImGuiMenu for numbers cannot get the user input. 

The behavior is different when NanoGui is used.

**Comment by jdumas** [comment]
Yes that's because ImGui is now implemented as a `ViewerPlugin` instead of being hardcoded into the `Viewer.cpp` file. This means that the `key_pressed()` callback for NanoGui, which was called before the custom, user-defined, `callback_key_pressed()`, is now called *after* (in [this line](https://github.com/libigl/libigl/blob/a16f338ca2b0781a34bdd5dcc8ef7447ffa093b6/include/igl/opengl/glfw/Viewer.cpp#L486)).

We can probably change the priority between the user-defined callbacks and the plugins' callbacks, but then you could have the opposite problem. In the case of ImGui, you could check if `ImGui::GetIO().WantCaptureMouse` is true, and `return false;` early in your custom callback.

**Comment by jdumas** [comment]
Yes I agree it is more natural. There may also be a bug in the way events are dispatched in the current plugin implementation of the ImGui menu. It's a bit hard to catch because it appears only when you combine several callbacks like this. I'll see what can be done.
