### ISSUE TITLE
Check mesh watertightness

### ISSUE THREAD

**Issue by irenji** [libigl/libigl#779]
Hi.

Are there any tools to check mesh water-tightness?

**Comment by h00shi** [comment]
Now this might not be what you want exactly, but if you already have oriented normals, summing up (area*n_x), (area*n_y), and (area*n_z) for all the triangles would give you zero for a watertight mesh.

**Comment by evouga** [comment]
I think it's enough to check is_edge_manifold(), is_vertex_manifold(), and that boundary_loop() is empty?

**Comment by jdumas** [comment]
Depends if you consider a Klein bottle to be watertight or not :p (it is watertight but doesn't enclose any solid region).

**Comment by irenji** [comment]
I want to check can print the mesh with 3d printer

**Comment by jdumas** [comment]
Well you can definitely print a Klein bottle. It just won't have any interior infill (although that depends on the slicer). I don't think there's a way to implement a `is_printable()` function that will work in all cases, as it really depends on the how the slicing software interprets your input model. You might want to check out [this paper](http://www.dgp.toronto.edu/projects/fast-winding-numbers/) that will soon make it into libigl (see PR #810), as well as [MeshFix](https://github.com/MarcoAttene/MeshFix-V2.1) that is pretty good at fixing your model geometry if it is supposed to enclose a solid region.

I'd say a good way to check if your model will print correctly, is to slice it with your favorite slicer, visualize the Gcode (e.g. with Repetier-Host), and fix the model if you find out the slices are garbage.

**Comment by evouga** [comment]
That said, it would be useful (and easy) to add an is_watertight() and is_orientable() to libigl (I'm just too lazy to send in a pull request myself ;) ).

**Comment by alecjacobson** [comment]
is_orientable would make sense and would be easy to add.

is_watertight is less meaningful because people define it differently. I
prefer the definitions in our mesh arrangements paper.

**Comment by jdumas** [comment]
Btw there is already a function `bfs_orient()`. So to verify if `is_orientable()` couldn't you just check that the `ids.maxCoeff()` you get is `== 1` ?

**Comment by alecjacobson** [comment]
I believe `bfs_orient` uses a definition of "orientable patches" that includes some non-manifoldness. I.e., an "orientable patch" is a connected component of triangles where connectivity is defined via shared _manifold edges_ (degree two). In some cases, this is very reasonable.

![nonmanifold-yet-consistently-orientable-patch](https://user-images.githubusercontent.com/2241689/42136685-3f022ea0-7d2e-11e8-9c1f-cea318aa197e.png)

This model is non-manifold, but has a unambiguously consistent orientation. 

On the other hand, this definition says that Möbius strip is one "orientable patch", with a (random) boundary running across it.

All this to say, `is_orientable()` needs to have a clear definition. Since the exact requirements tend to be application specific, I'd recommend implementing something like `is_consistently_oriented` that returns whether all faces agree on incident edge orientations. Then it's easy to construct an _ad hoc_ 
"is watertight" test out of `is_vertex_manifold`, `is_edge_manifold`, `is_consistently_oriented`, and `self_intersect`.

**Comment by alecjacobson** [comment]
See https://github.com/alecjacobson/gp-cli/blob/28f042d8f8e1df42881ce338b4bd28af051b0457/meshstatistics.cpp#L188C13-L188C45
