### ISSUE TITLE
mesh_boolean Creates Non-Manifold Mesh

### ISSUE THREAD

**Issue by bryantcurto** [libigl/libigl#815]
While using igl::copyleft::cgal::mesh_boolean, I encountered instances where two manifold meshes that, when unioned, produced a mesh that was non-manifold with respect to edges, or with respect to vertices.

Linked are examples (ie. vertices and faces for the input meshes, as well as the resulting union). Further, I've attached DAE files to visualize these meshes.

Thank you for your help!

Edge Manifold Example:
[EdgeManifold.txt](https://github.com/libigl/libigl/files/2118189/EdgeManifold.txt)
[input_edge_manifold.dae.txt](https://github.com/libigl/libigl/files/2118190/input_edge_manifold.dae.txt)
[output_edge_manifold.dae.txt](https://github.com/libigl/libigl/files/2118191/output_edge_manifold.dae.txt)

Vertex Manifold Example:
[VertexManifold.txt](https://github.com/libigl/libigl/files/2118193/VertexManifold.txt)
[input_vertex_manifold.dae.txt](https://github.com/libigl/libigl/files/2118196/input_vertex_manifold.dae.txt)
[output_vertex_manifold.dae.txt](https://github.com/libigl/libigl/files/2118197/output_vertex_manifold.dae.txt)

**Comment by alecjacobson** [comment]
igl::copyleft::cgal::mesh_boolean computes the _exact_ results which may be non-manifold even if the inputs are manifold. Here are two simple cases to help explain:

Two cubes "kissing" along an edge will union together to create a non-manifold mesh:

![edge-cube](https://user-images.githubusercontent.com/2241689/41662274-bee649e4-746e-11e8-972d-12ed1fc58018.png)

Two cubes "kissing" at a vertices will be non-vertex-manifold:
![vertex-cube](https://user-images.githubusercontent.com/2241689/41662438-2755fd4e-746f-11e8-9462-35b190d3d547.png)

So, the answer is "Yes, and it should because that's the exact result."

igl::copyleft::cgal::mesh_boolean _will_ guarantee that the output is [solid](http://www.cs.columbia.edu/cg/mesh-arrangements/).

**Comment by bryantcurto** [comment]
Thank you for your response!

As a follow up:

I am attempting to union several solids, and then decimate the result to eliminate small edges (see Issue #816).

However, igl::decimate is giving me the failed assertion message _(EF(e,1) == ff || EF(e,0) == ff) && "e should touch ff"_ (which can be found in circulation.cpp, which initially brought me to the conclusion that the union was not manifold.

Do you have any suggestions on a method for eliminating small edges within a mesh that may not be vertex/edge manifold, or a way to allow igl::decimate to operate on non-manifold solids?

**Comment by alecjacobson** [comment]
Ah, got it.

Yes, unfortunately our implementation of decimate is only working on manifold meshes.

I _believe_ that this implementation (forked off of libigl's) handles non-manifold edges:

https://github.com/songrun/SeamAwareDecimater

(It is mostly built to handle UVs but I think you can safely ignore that part)

Otherwise, another reasonably thing to do would be to either thicken or disconnect along the non-manifold edges/vertices. In the cube cases above this is very well posed and you wouldn't get into much trouble: e.g., thickening an edge into a thin connection or cutting along the edge.

Implementing this robust would almost certainly rely on being able to sort incident faces around a vertex/edge correctly (one of the core subroutines that makes our booleans robust). So you could reuse that code if you were to dive into coding this yourself.

This is a cool feature to have, unfortunately, we don't have it yet and I don't have an immediate need for it, so might not happen from me in the foreseeable future.
