### ISSUE TITLE
igl::decimate Starts Decimating Before Checking Stopping Condition

### ISSUE THREAD

**Issue by bryantcurto** [libigl/libigl#816]
While using igl::decimate, I discovered that, unless the cost of collapsing the first edge in the priority queue is infinite, the edge is collapsed before checking the stopping condition. As a result, the first edge is collapsed, even when it should not be.

Below is an example (ie. cost and placement function, stopping condition function, vertices and faces for the input mesh, and the resulting decimated mesh). For this example, no decimation should have occurred.

### cost_and_placement function
```
 igl::shortest_edge_and_midpoint
```

### stopping_condition function
```
bool
stoppingConditionCallbackShortEdges(const Eigen::MatrixXd& V, const Eigen::MatrixXi& F,
                                     const Eigen::MatrixXi& E, const Eigen::VectorXi& EMAP,
                                     const Eigen::MatrixXi& EF, const Eigen::MatrixXi& EI,
                                     const std::set<std::pair<double,int> >& Q,
                                     const std::vector<std::set<std::pair<double,int> >::iterator >& Qit,
                                     const Eigen::MatrixXd& C, const int e,
                                     const int e1, const int e2, const int f1, const int f2)
{
	return Q.begin()->first >= 1e-4;
}
```

#### Vertices: (10);
0.0, 0.0, 0.0,
0.0, 6.0, 0.0,
6.0, 6.0, 0.0,
3.0, 3.0, 0.0,
6.0, 0.0, 0.0,
0.0, 0.0, 6.0,
0.0, 6.0, 6.0,
6.0, 6.0, 6.0,
3.0, 3.0, 6.0,
6.0, 0.0, 6.0,

#### Faces: (16)
0, 1, 3,
3, 1, 2,
3, 4, 0,
8, 6, 5,
7, 6, 8,
5, 9, 8,
0, 5, 1,
1, 5, 6,
4, 9, 0,
0, 9, 5,
1, 6, 2,
2, 6, 7,
3, 8, 4,
4, 8, 9,
2, 7, 3,
3, 7, 8,

#### Vertices: (9)
1.5, 1.5, 0.0,
0.0, 6.0, 0.0,
6.0, 6.0, 0.0,
6.0, 0.0, 0.0,
0.0, 0.0, 6.0,
0.0, 6.0, 6.0,
6.0, 6.0, 6.0,
3.0, 3.0, 6.0,
6.0, 0.0, 6.0,

#### Faces: (14)
0, 1, 2,
7, 5, 4,
6, 5, 7,
4, 8, 7,
0, 4, 1,
1, 4, 5,
3, 8, 0,
0, 8, 4,
1, 5, 2,
2, 5, 6,
0, 7, 3,
3, 7, 8,
2, 6, 0,
0, 6, 7,

_Edit: Put example inline, removed unnecessary files of example, and added cost function and stopping condition_

**Comment by alecjacobson** [comment]
This is a bug and should be fixed.

**Comment by alecjacobson** [comment]
This is no longer considered a bug.

See the [detailed documentation](https://libigl.github.io/dox/decimate_8h.html). Basically, `stopping_condition` shouldn't be thought of as a `while(!stopping_condition){ do another collapse } ` but rather `do{ another collapse}while(!stopping_condition)`

Since `stopping_condition` takes the last successfully collapsed edge as input, it can't be called before the decimation starts.

That means, in your case, you should check your own stopping criteria before calling decimate _or_ catch your condition in the `pre_collapse` callback (by returning false) or in your `cost_and_placement` (by returning ∞ cost).

This seems to imply `infinite_cost_stopping_condition` is redundant and could be replaced with a no-op (since inf costs are checked outside the callback).
