### ISSUE TITLE
About the Texture

### ISSUE THREAD

**Issue by chenhonghua** [libigl/libigl#86]
Hi,
In libigl exists a function(igl::texture_from_tga). We can get the opengl texture id via the function.
Is there a function in libigl that we can set  the texture directly?

**Comment by chenhonghua** [comment]
The function of set_uv work for that?

**Comment by chenhonghua** [comment]
I have a texture get from the function of igl::texture_from_tga.
I also have the texture coordinates.
But how can I establish a relationship between the texture and the texture coordinats?

**Comment by alecjacobson** [comment]
Are you asking how do you use texture coordinates with the libigl viewer?
Or how does texture mapping work in general?

**Comment by chenhonghua** [comment]
Hi, alecjacobson,
I am curious about how to use texture coordinates with the libigl viewer.

**Comment by alecjacobson** [comment]
Have a look at the parameterization tutorials (e.g.
`501_HarmonicParam/main.cpp`). Unfortunately the viewer is expecting the
pixel color data in a different format from igl:texture_from_tga, but it
shouldn't be too hard to convert it. You'll need to do something like:

    viewer.core.show_texture = true;
    viewer.data.set_uv(V_uv);
    viewer.data.set_texture(R,G,B)

where R,G,B are the separated red green and blue channels of your texture.
Now that I have a look at this I see that it's a little silly since we
later convert it back to the format that igl::texture_from_tga returns and
what openGL expects. So perhaps this is _subject to change_.

**Comment by clcaalu** [comment]
Hi,
I am also interested into get to know how to use the texture Coordinates.
As far as I know, the coordinates are read on the order that they are on the .obj file.

However, I need to know which **vt** corresponds to which **v** because I am storing each Vertex information into a Vertex structure.

I have tried reading my obj files with Assimp and I get the vertices information in order. I mean, for the vertex Mesh->mVertices[i] I can get it's texture coordinate on Mesh->mTextureCoords[0][i]

When I try to load the Obj file using libigl, the texture looks totally out of place.
What am I doing wrong?

Thanks in advance!

**Comment by alecjacobson** [comment]
It really depends on the mesh in the particular .obj. The .obj format allows the number of vertex positions and the number of texture coordinates to be different.
