### ISSUE TITLE
draw text on screen

### ISSUE THREAD

**Issue by Lagrant** [libigl/libigl#876]
Dear all,
does libigl provide any function or method to draw text on screen? If not, is there any way to use OpenGL functions by libigl to draw text?

**Comment by jdumas** [comment]
Hi. You can use the ImGui library for that. If you attach a `ImGuiMenu` plugin to the viewer (see tutorial 106), then you can set your text using `viewer.data().add_label()` to set labels in 3D. If you only want the text but not the ImGui menu, you should be able to overwrite the callbacks to define an empty menu.

**Comment by Lagrant** [comment]
Thank you for your reply. It works well!

**Comment by Lagrant** [comment]
Dear Dumas,
I have another question now.  How can I set the size and color of the text by libigl?

**Comment by jdumas** [comment]
Right now you can't do that directly. However, you can override the virtual method [`draw_menu()`](https://github.com/libigl/libigl/blob/23fa1d6b560afa8a0439fca5f4103678ce806b00/include/igl/opengl/glfw/imgui/ImGuiMenu.cpp#L140), and replace its content with your own own code, e.g. surrounding the call to `draw_label_window` with your own sizing/color functions (you'd have to look into how to do that with ImGui directly). Note that using a font size different from the default will pose some blurry fonts to be rendering (because fonts are rasterized at the target size at the beginning of the program). The labels are more intended as a debugging tool than anything else right now. If you want to make a PR to add the ability to change the size and color feel free to do so.

**Comment by Lagrant** [comment]
Thank you very much! I will have a try.
