### ISSUE TITLE
Multiple viewer plugins

### ISSUE THREAD

**Issue by Hugo-Pereira** [libigl/libigl#881]
Hi guys,

When add more than 1 plugin to viewer.plugins I get the following message:

```
libigl/external/imgui/imgui/imgui.cpp:3235: void ImGui::NewFrame(): Assertion `(g.FrameCount == 0 || g.FrameCountEnded == g.FrameCount) && "Forgot to call Render() or EndFrame() at the end of the previous frame?"' failed.
Aborted (core dumped)
```

The code I have is this:

```    
    igl::opengl::glfw::Viewer viewer;
    igl::opengl::glfw::imgui::ImGuiMenu mainMenu;
    igl::opengl::glfw::imgui::ImGuiMenu mainMenu2;
    viewer.plugins.push_back(&mainMenu);
    viewer.plugins.push_back(&mainMenu2);
    viewer.launch();
```

Also, is it possible to add and remove plugins when pressing a button?

Thanks

**Comment by jdumas** [comment]
You can do whatever you want with `viewer.plugins`, so you can add/remove them as you see fit. However, it may be simpler to "hide" the ImGui menu if you don't want to show it.

Regarding your bug, there are some problems currently with nested viewers, as well as with nested ImGui instances. See my PR #861 that fixes the first issue. To get nested ImGui instances is a bit more complicated and I already have a fix in my branch [nested-imgui](https://github.com/jdumas/libigl/tree/nested-imgui), but it will take some time before we can merge it to the master branch.

**Comment by Hugo-Pereira** [comment]
Wow that was fast :)

I don't get the nested viewer part though. Where am I nesting things? I have a single viewer and two ImGuiMenus that I add to the viewer as plugins. This causes viewers to be nested?

**Comment by Hugo-Pereira** [comment]
I want to create a tool, which will have 3 steps. Each step will have its own menu, along with a "main" menu (where I can select which step to "show").

Since there is a list of plugins in the viewer, I hoped I could just add and remove them as needed :\

**Comment by jdumas** [comment]
You can already create multiple menu with a single `ImGuiMenu` plugin. Take a look at tutorial 106 to see how to add/remove windows. Take a look at `imgui_demo.cpp` and maybe compile one of the example to see a demo of what is possible to do with ImGui, then copy/paste the code that you need to write your own menu.

**Comment by JianqiangDing** [comment]
Hi, Dr jdumas,
recently, I noticed that Dear ImGui team are testing the docking feature, so I want to test the feature with the libigl's viewer, I've checked the source code of the viewer part, the libigl separate the main loop of imgui into several functions, which means all the imgui objects created between NewFrame() and End(), the layout I want to implement is quite like the picture illustrated following:
![image](https://user-images.githubusercontent.com/7833870/58403015-39845600-8094-11e9-8af9-1a906a7b4d3d.png)
so that, I can split the window into several parts, some for menus and some for OpenGL viewports. (the question I am asking probably more suitable called nesting windows)
do I need to write some class as a plugin of the viewer? I am not sure if this thought is right or not.
any suggestion would be helpful.

**Comment by JianqiangDing** [comment]
![46386974-e70eb780-c707-11e8-8583-be563ce3c11c](https://user-images.githubusercontent.com/7833870/58403591-a5b38980-8095-11e9-88f5-9e667b5994f1.gif)

**Comment by jdumas** [comment]
Hi,

I haven't had time to try out the new docking branch of ImGui. Is there anything in particular that is preventing it to work as intended within libigl?

**Comment by JianqiangDing** [comment]
Hi, Dr jdumas,

I've made some attempts, maybe somewhere wrong, always some small bugs exist, i'll keep you posted if there is any progress. thank you for your response.

Best
