### ISSUE TITLE
Question in setting texture

### ISSUE THREAD

**Issue by Juzhan** [libigl/libigl#886]
When I tried to set texture for an object like this:

 ```
  Eigen::MatrixXd V, TC, N, FTC, FN;
  Eigen::MatrixXi F;
  igl::readOBJ("../objects/textured.obj", V, TC, N, F, FTC, FN);
  igl::png::readPNG("../objects/textured.png", R,G,B,A);
  igl::opengl::glfw::Viewer viewer;
  viewer.data().set_mesh(V, F);
  viewer.data().set_normals(FN);
  viewer.data().set_uv(TC);
  viewer.data().show_lines = false;
  viewer.data().show_texture = true;
  viewer.data().set_texture(R,G,B);
  viewer.launch();
```

an error occurs for the function `set_uv()` : 
`ERROR (set_UV): Please provide uv per vertex.`

How can I solve this?

Or is there any tool that can convert models' uv coordinates into per-vertex uv?

**Comment by jdumas** [comment]
You probably need to duplicate the vertices of your mesh so that each triangle has it own vertex, with 1 position and 1 uv coordinate per corner. The problem is that uv coordinate for a vertex might be different depending on which triangle it comes from. In an obj file there is usually 1 array of vertex position and 1 array of uv coordinates, and for each face you specify different indices for the corner that point to 2 different arrays. But you can't have that in OpenGL (you need to index vertex attributes into the same array), so you need to duplicate vertices.

**Comment by RoyToren** [comment]
Hi,
I recently stumbled upon the same problem.
As @jdumas the representation of vertices in OpenGL is different and might conflict with the representation of vertices in a .obj file when a texture is added.
More information can be found here:  [1](https://stackoverflow.com/questions/29867926/why-does-the-number-of-vt-and-v-elements-in-a-blender-obj-file-differ), [2](https://stackoverflow.com/questions/27777349/handling-obj-files-why-is-it-possible-to-have-more-vertextextures-vt-than-ve) and [3](https://www.notion.so/roytoren/c-OpenGL-Index-buffers-difficulties-Stack-Overflow-39ed1947502f45c9bfaa88734195e8e0)
I found a few ways to solve this problem:

- If you must use a .obj file, you can implement the pseudocode shown at [3](https://www.notion.so/roytoren/c-OpenGL-Index-buffers-difficulties-Stack-Overflow-39ed1947502f45c9bfaa88734195e8e0), not too difficult, but you will now have duplicate vertices.

- If you are flexible with the type of object you are working with, I found that .ply is quite convenient, and the following can be done:
Convert your .obj files to .ply file, which will automatically duplicate the needed vertices, and as a result, a single uv will correspond to a single vertex you read. You can do so with [assimp](http://www.assimp.org/) or with converters that are available online.
In this case, you will also have duplicate vertices.

- If you can generate a .ply file from the start, you might get an even better representation for my taste, which looks like so:
```
ply
format ascii 1.0
element vertex 87498
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
element face 174992
property list uchar int vertex_indices
end_header
-7.53994 19.052 457.635 111 79 42
-7.52841 18.7904 457.484 113 80 45
-7.70518 18.8969 457.496 112 79 48
-36.1149 7.63263 457.563 91 70 43
-36.2176 7.71983 457.565 89 71 44
-36.0678 7.76024 457.57 88 71 38
-36.7334 8.16195 457.542 92 67 52
```
As you can see, each vertex is encoded with additional data that corresponds to the RGB values at the vertex. With this representation, there is no need to deal with uv values, only to use the setColor function and use the colors loaded from the file.
Using the readPLY function, the color information will be stored at VD (#V,*), which contains additional vertex data.
Since there are no duplicate vertices and each vertex has a single RGB value, it is also easier to perform additional processing to the shape and texture of the object
