### ISSUE TITLE
Comparison between libigl and cgal

### ISSUE THREAD

**Issue by manavbhatia** [libigl/libigl#899]
Hi, 

   I am new to this domain, so I am posting some very beginner level questions here. Thanks for your patience and help. 

   As a continuation to issue #898 I would appreciate some guidance on 

-  the primary differences between the Cgal and libigl 
-  if there are any differences with reference to double precision or arbitrary precision computation

Thanks! 
Manav

**Comment by jdumas** [comment]
CGAL and libigl have different purposes. The goal of libigl is to provide a collection of functions that are "simple" to use and on top of which you can build whatever you need. So there is no complicated typedef as in CGAL, and the basic types to represent meshes are Eigen matrices (plain arrays).

CGAL on the other hands offer a lot of functionalities, all of which are not present in libigl. It also offers kernels for exact computation/arbitrary precision. Incidentally, some of libigl's functions are built on top of CGAL, and make use of CGAL features (mostly for exact computation). Those are located in `include/igl/copyleft/cgal/ folder.

Since libigl functions are templated, you could technically use them with arbitrary precision coordinates, although you'd have to libigl in header-only mode for that.

**Comment by manavbhatia** [comment]
@alecjacobson  Could you please provide some more clarity on the robustness issue. 

Cgal's post on [exact computation paradigm](https://www.cgal.org/exact.html) states:
> Given this, the algorithms on top of it just work. Not in most cases, but always! 

So, they seem to be making an argument in favor of their robustness. Are there specific areas where Cgal lacks robustness and libigl provides better implementations?

**Comment by alecjacobson** [comment]
That's a really broad statement and robustness can be defined differently ways. 

for example, libigl's boolean operations accept a much broader set of input types than cgal's. So many inputs that work just fine for libigl will cause cgal to crash or produce meaningless output.

Besides booleans there aren't many algorithms that both cgal and libigl implement so a direct comparison is not necessarily appropriate. They complement each other rather well. 

Since libigl has a simpler API you might start there.

**Comment by manavbhatia** [comment]
Thanks! 

Is the mesh-mesh boolean operation implementation in libigl independent of Cgal? I am wondering if I need Cgal for any reason except to get access to its arbitrary precision kernel. 

I do not foresee stitching any domains together. For the most part, I need the boolean operations and tessellation done on subdomains after intersection.

**Comment by alecjacobson** [comment]
our booleans use CGALs (a) "lazy" number type, (b) their 2D constrained Delaunay triangulation and their (c) triangle-triangle intersections. 

(b) and (c) could be re-written instead, we just never needed to (CGAL's methods work well; and we're academics that don't need non-LGPL code).

(a) is harder to replace because CGAL has done a great job making the lazy type efficient. Switching to another type will take a performance hit. On the other hand, we'd still like to change at some point because CGAL's lazy type is not thread-safe (so it's hard to parallelize).
