### ISSUE TITLE
crash in igl::signed_distance

### ISSUE THREAD

**Issue by wtholliday** [libigl/libigl#905]
When running `signed_distance`, I'm getting an assertion failure:

    Assertion failed: (v_sqrlen != 0), function project_to_line, file libigl/include/igl/project_to_line.cpp, line 38.

I suppose I have a degenerate triangle, but it seems like libigl should recover from such a problem.

**Comment by wtholliday** [comment]
@jdumas Sure thing:

[chas.obj.zip](https://github.com/libigl/libigl/files/2413483/chas.obj.zip)

Thanks for your help!

**Comment by jdumas** [comment]
This is the mesh before or after cleanup? It looks quite good to me. It looks like pseudonormal test fails because of degenerate edges. Can you post a minimal example to reproduce the issue? (with and without the cleanup you mention in #906, that would be helpful!).

**Comment by wtholliday** [comment]
@jdumas That's before cleanup. I'll try to work on a minimal example.

**Comment by wtholliday** [comment]
Do you know how I can determine which query point is causing the crash? I could dump out all the query points I'm using, but that doesn't seem very minimal.

**Comment by jdumas** [comment]
Depends how many query points you have :p 
It's fine to dump it in a .xyz file and upload it here. Otherwise you could go into debug mode (either gdb or visual studio) and backtrack from there to display the coordinate of the query point that poses an issue. Another (more DYI) option is to do a dichotomic search: have your program takes 2 cli arguments `a` and `b` that specifies the range of query points you're passing to `igl::signed_distance`, and halves those until you find a range of small size that still makes the program crash :D

**Comment by wtholliday** [comment]
@jdumas Thanks!

This isn't particularly minimal, but I dumped out the data so you can reproduce the crash:

    Eigen::MatrixXd P(7576064,3);
    Eigen::MatrixXd V(681502,3);
    Eigen::MatrixXi F(1362992,3);
    
    auto file = fopen("repro.dat", "rb");
    assert(file);
    fread(P.data(), sizeof(double), P.size(), file);
    fread(V.data(), sizeof(double), V.size(), file);
    fread(F.data(), sizeof(int), F.size(), file);
    fclose(file);
    
    Eigen::MatrixXd S,C,N;
    Eigen::MatrixXi I;
    
    igl::signed_distance(P, V, F,
                         igl::SIGNED_DISTANCE_TYPE_PSEUDONORMAL,
                         0.0, 2048.0, S, I, C, N);

[repro.dat.zip](https://github.com/libigl/libigl/files/2415574/repro.dat.zip)

Does that reproduce the crash on your end?

**Comment by alecjacobson** [comment]
Try `SIGNED_DISTANCE_TYPE_FAST_WINDING_NUMBER` instead.
