### ISSUE TITLE
BBW on concave meshes

### ISSUE THREAD

**Issue by candycat1992** [libigl/libigl#94]
Hi, I've used BBW on a concave mesh in my project. The code was as below:
```C++
 Eigen::MatrixXd VV;
    // Tetrahedra
    Eigen::MatrixXi TT;
    // New surface faces FF
    Eigen::MatrixXi FF;
    if(!igl::mesh_with_skeleton(vertices,faces, controlPoints, controlPointIndices, BE, CE, 10, VV, TT, FF)) {
        qDebug() << "mesh_with_skeleton failed.";
        return ;
    }

    Eigen::VectorXi b;
    // List of boundary conditions of each weight function
    Eigen::MatrixXd bc;
    if(!igl::boundary_conditions(VV, TT, controlPoints, controlPointIndices, BE, CE, b, bc)) {
        qDebug() << "boundary_conditions failed.";
        return;
    }

    cout<<"b=["<<b<<"];"<<endl;
    cout<<"bc=["<<bc<<"];"<<endl;

    // compute BBW
    // Default bbw data and flags
    igl::BBWData bbw_data;
    if(!igl::bbw(VV, TT, b, bc, bbw_data, weightMatrix)) {
        qDebug() << "bbw failed.";
        return;
    }
```

The mesh looks like:
![2015-08-05 19 17 04](https://cloud.githubusercontent.com/assets/5907064/9084609/13018618-3ba8-11e5-8a74-ac80ed3fe9bc.png)

And the output was:
``` C++
tetgen begin()
Delaunizing vertices...
Delaunay seconds:  0.005136
Creating surface mesh ...
Surface mesh seconds:  0.000712
Recovering boundaries...
Boundary recovery seconds:  0.004854
Removing exterior tetrahedra ...
Exterior tets removal seconds:  0.000643
Recovering Delaunayness...
Delaunay recovery seconds:  0.002305
Refining mesh...
Refinement seconds:  0.011522
Optimizing mesh...
Optimization seconds:  0.001389
Jettisoning redundant points.

Writing nodes.
Writing elements.
Writing faces.
Writing edges.

Output seconds:  0.00017
Total running seconds:  0.027002

Statistics:

  Input points: 709
  Input facets: 1412
  Input segments: 2118
  Input holes: 0
  Input regions: 0

  Mesh points: 720
  Mesh tetrahedra: 2071
  Mesh faces: 4848
  Mesh faces on facets: 1412
  Mesh edges on segments: 2118
  Steiner points inside domain: 12

1412
tetgen end()
boundary_conditions failed. 
```

So, why boundary conditions failed? What's wrong with the mesh? 

The .obj file: https://drive.google.com/file/d/0BwWDClXCK5C1emxHbHNyeHF6RnM/view?usp=sharing
The libigl version: 1.1.5

**Comment by alecjacobson** [comment]
This doesn't have anything to do with the mesh being concave. Try
recompiling with VERBOSE defined. If igl::boundary_conditions is returning
false, then either 1) you're not passing any handles, 2) the boundary
conditions are empty because none of you're controls don't lie on top of
any mesh vertices or 3) some of the (bone/cage) handles didn't receive
proper weights (usually meaning some handles but not all passed case 2.).

Not knowing what value controlPoints has, I'd guess that these locations
don't actually lie in the interior of your solid mesh. Are they just
floating in space around the mesh? You could consider snapping them to the
closest vertex of the mesh.

Hope this helps.

**Comment by candycat1992** [comment]
You are right. The locations don't lie in the interior... By moving them to the closest vertex, it solved my problem.

Thanks! You are always so helpful!
