### ISSUE TITLE
drawing points in viewer

### ISSUE THREAD

**Issue by gcirio** [libigl/libigl#97]
The following code is correctly drawing the triangle mesh, but not the added point, no matter what point_size I specify:

```c++
igl::Viewer viewer;

Eigen::MatrixXd V(4, 3);
Eigen::MatrixXi F(2, 3);
Eigen::MatrixXd C(4, 3);

V.row(0) << -0.5, -0.5, 0.;
V.row(1) << 0.5, -0.5, 0.;
V.row(2) << 0.5, 0.5, 0.;
V.row(3) << -0.5, 0.5, 0.;

F.row(0) << 0,1,2;
F.row(1) << 0,2,3;

C.setOnes();

viewer.data.set_mesh(V, F);
viewer.data.add_points(V, C);

viewer.launch();
```

Am I missing something, or is there a bug somewhere?
By the way, the documentation for set_points has a small mistake (it should mention add_points, not set_points).
Thanks!

**Comment by danielepanozzo** [comment]
This is what I get (MacOSX Yosemite):
<img width="1353" alt="screenshot 2015-08-20 11 27 15" src="https://cloud.githubusercontent.com/assets/6785134/9380143/973562e2-472e-11e5-9e87-83a74a11dc6f.png">

However, the code above does not compile for me on the latest version of libigl, I had to fix line 1 with the additional namespace:

igl::viewer::Viewer viewer;

Could you try to update to the latest version of libigl to see if this problem is still there?

**Comment by gcirio** [comment]
Hi Daniele, thanks for your reply.
I updated to the latest sources, but the problem is still here. I get the square without the white dots.
I'm on (K)Ubuntu 15.04 on a NVIDIA 8800 GTX with the open source (nouveau) driver. 
Maybe the issue comes from the driver?

**Comment by danielepanozzo** [comment]
Strange, it might be a bug in the driver. Does it also happen with the official NVIDIA driver?

**Comment by gcirio** [comment]
I tried with the official NVIDIA drivers and everything is fine.
This is indeed a problem with the nouveau driver.
Thanks!
